### ISSUE TITLE
FidoAdapter not always setting "scores" in ProteinID items

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1166]
When run with seperate_runs=T or on a single run, the FidoAdapter does not add the calculated posterior to the ProteinIdentification item but only to the ProteinGroup information.
However following tools like FDR (on proteins) only look for the "scores" in the ProteinIdentification entries and are therefore not working correctly.

**Comment by hendrikweisser** [comment]
@jpfeuffer: This was actually a design decision: If the individual protein scores are still valid ("separate_runs" or single run), why overwrite them when the inference/grouping scores are already stored in the protein groups?
But you make a good point about downstream tools, and getting those working correctly is more important than preserving the original protein scores.
Could you make the necessary changes in the code (overwrite the scores, maybe store the previous values as "metavalue" entries, and update the documentation) and open a pull request?

**Comment by jpfeuffer** [comment]
Yes, I will do as you suggested. Seems like the best choice.

**Comment by mwalzer** [comment]
overwriting scores is never a good idea, especially if you have the metainfointerface at your disposal anyways. we have a lot of cv terms for describing scores, some even split up to tool level. And if not, we could suggest new ones. so exchanging the value and 'meaning' of the score value would be nicer.

**Comment by jpfeuffer** [comment]
Okay, I have a draft ready, where the old scores are saved as metainfo.
@mwalzer: Where can I look up existing CV terms and at which level should they be stored in the output XML File?
@hendrikweisser: Aren't there any tests for the FidoAdapter (except the thirdparty executable test)? Does it make sense to add one?

**Comment by hendrikweisser** [comment]
> Where can I look up existing CV terms and at which level should they be stored in the output XML File?

Why do you need CV terms? In other cases where scores are moved to metavalues, a metavalue with the name "[score type]_score" and the corresponding value is created. Since scores in idXML generally don't use CV terms, I wouldn't start adding them at this point.

> Aren't there any tests for the FidoAdapter (except the thirdparty executable test)? Does it make sense to add one?

No, there are no other tests. The code would have to be moved out of the TOPP tool into a library class to allow unit testing. I don't really see the need for that.
What kind of you test were you thinking of adding?

**Comment by jpfeuffer** [comment]
I thought, that because the CV terms were mentioned, it might be good practice to add them. But if you say, that  they are generally not used in idXML, I also don't see the need anymore.
There's only one small question remaining. What about the higher_score_better information? Should it be kept somewhere? I think, since the old scores can't be used in TOPP tools anymore (without much hassle), it is not really important to keep it, right?

For the tests, I didn't look close enough into the thirdparty tests. I thought that only the existence and rough functionality of the executable would be tested in there and that the actual class test would be included on TOPPTool level.
But it seems that the whole Adapter is sufficiently tested there.

**Comment by hendrikweisser** [comment]
You'd be opening a big can of worms if you wanted to map "free text" score types to CV terms. And FidoAdapter wouldn't be the right point to do that, anyway.

I wouldn't worry about the "higher_score_better" information. Leave it out.

There are two levels of tests in OpenMS: class tests (unit tests) and tool tests (could be considered integration tests). The third-party tests are just tool tests for TOPP tools that depend on external executables, and couldn't be meaningfully tested without those executables present. Since those executables are not packaged with OpenMS on all platforms, there have to be special provisions in the build system for the third-party tests.
