### ISSUE TITLE
FalseDiscoveryRate: handling of decoys

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#1167]
Currently FDR is removing all decoy peptides (when the flag add_decoy_peptides is not set).
For proteins, there is no such option. Should we also include it here for consistency or leave it to the user to manually filter them afterwards?

**Comment by hendrikweisser** [comment]
If there are decoy proteins left, it should only be those that share peptides with target proteins (because when decoy peptides are removed, the associated protein accessions should be removed, too). Is that correct?

In any case, I agree that the decoy protein accessions should be removed together with the decoy peptides. Otherwise users may even be confused about whether decoy peptides were removed, if they see decoy protein accessions in the output of e.g. TextExporter at the end of a pipeline.

**Comment by jpfeuffer** [comment]
This should be sufficiently implemented by now.
