### ISSUE TITLE
TOPP_FidoAdapter_4 test runs forever on linux

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1171]
Continued discussion started in: https://github.com/OpenMS/OpenMS/pull/1170
I noticed that the TOPP_FidoAdapter_4 test runs forever on our linux cluster. I canceled it after half an hour. On my Macbook, it runs just fine.

**Comment by hannesveit** [comment]
Keeps getting stranger. Wanted to run valgrind on FidoChooseParameters, so I rebuilt Fido with CMAKE_BUILD_TYPE=Debug. Now, however, TOPP_FidoAdapter_4 finishes after a few seconds and passes, but TOPP_FidoAdapter_4_out fails instead:

```
1625: Offending lines:			(tab_width = 8, first_column = 1)
1625: 
1625: in1:  /nfs/wsi/abi/coffein/usr/veit/Code/git-openms/OpenMS_build/src/tests/topp/FidoAdapter_4_output.tmp   (line: 597, position/column: 76/98)
1625: 			<UserParam type="string" name="indistinguishable_proteins_2" value="1,PH_!
1625: 			                                                                         21"/>
1625: 
1625: in2:  /home/veit/Code/git-openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_4_output.idXML   (line: 597, position/column: 76/98)
1625: 			<UserParam type="string" name="indistinguishable_proteins_2" value="1,PH_!
1625: 			                                                                         19"/>
```

If that rings a bell for anyone, please give me a clue. Otherwise, I'll now have a look with valgrind. Something seems to be fishy here.

**Comment by hendrikweisser** [comment]
I just tried it on our development server (Ubuntu 12.04) with the current "develop" branch, no problems there:

```
$ ctest -R FidoAdapter
Test project /nfs/t17_project/OpenMS/build
      Start 580: TOPPWRITEINI_FidoAdapter
 1/13 Test #580: TOPPWRITEINI_FidoAdapter ...............   Passed    0.10 sec
      Start 581: TOPPWRITEINI_FidoAdapter_SectionName
 2/13 Test #581: TOPPWRITEINI_FidoAdapter_SectionName ...   Passed    0.04 sec
      Start 908: TOPPWRITECTD_FidoAdapter
 3/13 Test #908: TOPPWRITECTD_FidoAdapter ...............   Passed    0.18 sec
      Start 1639: TOPP_FidoAdapter_1
 4/13 Test #1639: TOPP_FidoAdapter_1 .....................   Passed    2.33 sec
      Start 1640: TOPP_FidoAdapter_1_out
 5/13 Test #1640: TOPP_FidoAdapter_1_out .................   Passed    0.51 sec
      Start 1641: TOPP_FidoAdapter_2
 6/13 Test #1641: TOPP_FidoAdapter_2 .....................   Passed    1.65 sec
      Start 1642: TOPP_FidoAdapter_2_out
 7/13 Test #1642: TOPP_FidoAdapter_2_out .................   Passed    0.56 sec
      Start 1643: TOPP_FidoAdapter_3
 8/13 Test #1643: TOPP_FidoAdapter_3 .....................   Passed    1.43 sec
      Start 1644: TOPP_FidoAdapter_3_out
 9/13 Test #1644: TOPP_FidoAdapter_3_out .................   Passed    0.50 sec
      Start 1645: TOPP_FidoAdapter_4
10/13 Test #1645: TOPP_FidoAdapter_4 .....................   Passed    0.50 sec
      Start 1646: TOPP_FidoAdapter_4_out
11/13 Test #1646: TOPP_FidoAdapter_4_out .................   Passed    0.36 sec
      Start 1647: TOPP_FidoAdapter_5
12/13 Test #1647: TOPP_FidoAdapter_5 .....................   Passed    0.69 sec
      Start 1648: TOPP_FidoAdapter_5_out
13/13 Test #1648: TOPP_FidoAdapter_5_out .................   Passed    0.45 sec

100% tests passed, 0 tests failed out of 13

Total Test time (real) =   9.49 sec
```

The build type was "RelWithDebInfo".

**Comment by hendrikweisser** [comment]
Same result for build type "Release" for me.

**Comment by hannesveit** [comment]
And just to be sure, you have compiled Fido from the hendrikweisser/Fido fork, right?

The problem seems to be in Fido itself, not in our adapter. I can reproduce it when I run FidoChooseParameters directly on the generated fido_input_*.txt files. It seems to get stuck in BasicGroupBigraph::logLikelihoodConstant(...). I accidentally found a "fix" by adding three std::cout calls to this method, which is not a good sign, I guess ;)

We're on Scientific Linux 6 / gcc 4.4.7.

**Comment by hendrikweisser** [comment]
> And just to be sure, you have compiled Fido from the hendrikweisser/Fido fork, right?

Yes. I just pulled from the repo and recompiled to make sure (with GCC 4.6.3). Works fine for me.

**Comment by timosachsenberg** [comment]
@hendrikweisser can you upload your binaries to:
https://sourceforge.net/p/open-ms/code/HEAD/tree/THIRDPARTY/Linux/64bit/Fido
I would like to give it a try and see if it works with travis.

**Comment by hannesveit** [comment]
Hmm. This is really strange. I can now look at the infinite loop running forever when I add a cout to logAdd(double logA, double logB) in Numerical.h.

```c++
static double logAdd(double logA, double logB)
{
  //
  cout << "logA = " << logA << ", logB = " << logB << endl;
  //

  // returns log(a*b)
  if ( logA < logB )
  {
    return logAdd(logB, logA);
  }

  // assume logA <= logB

  // when one of the terms is very small, then just use the other term
  if ( isinf(logA) && logA < 0 )
    return logB;

  return log2( 1 + pow(2, logB-logA) ) + logA;
}
```

It seems to call itself forever because the condition logA < logB is true for logA = nan and logB = -inf and vice versa:

```
bash-4.1$ FidoChooseParameters ~/fido_input_graph.txt ~/fido_input_proteins.txt
logA = nan, logB = -inf
logA = -inf, logB = nan
logA = nan, logB = -inf
logA = -inf, logB = nan
logA = nan, logB = -inf
logA = -inf, logB = nan
logA = nan, logB = -inf
logA = -inf, logB = nan
logA = nan, logB = -inf
logA = -inf, logB = nan
logA = nan, logB = -inf
logA = -inf, logB = nan
logA = nan, logB = -inf
logA = -inf, logB = nan
logA = nan, logB = -inf
logA = -inf, logB = nan
...
```

But as I said, the infinite loop disappears and everything runs fine when I simply add a couple of std::cout calls in BasicGroupBigraph::logLikelihoodConstant(...). I have officially no clue anymore. I give up.

**Comment by cbielow** [comment]
What is the output for logAdd in the non-loop case?

And: does that t make sense to check for nan within logAdd?

Am 20. Januar 2015 21:06:11 MEZ, schrieb Johannes Veit <notifications@github.com>:
>Hmm. This is really strange. I can now look at the infinite loop
>running forever when I add a cout to logAdd(double logA, double logB)
>in Numerical.h.
>
>```c++
>static double logAdd(double logA, double logB)
>{
>  //
>  cout << "logA = " << logA << ", logB = " << logB << endl;
>  //
>
>  // returns log(a*b)
>  if ( logA < logB )
>  {
>    return logAdd(logB, logA);
>  }
>
>  // assume logA <= logB
>
>  // when one of the terms is very small, then just use the other term
>  if ( isinf(logA) && logA < 0 )
>    return logB;
>
>  return log2( 1 + pow(2, logB-logA) ) + logA;
>}
>```
>
>It seems to call itself forever because the condition logA < logB is
>true for logA = nan and logB = -inf and vice versa:
>
>```
>bash-4.1$ FidoChooseParameters ~/fido_input_graph.txt
>~/fido_input_proteins.txt
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>logA = nan, logB = -inf
>logA = -inf, logB = nan
>...
>```
>
>But as I said, the infinite loop disappears and everything runs fine
>when I simply add a couple of std::cout calls in
>BasicGroupBigraph::logLikelihoodConstant(...). I have officially no
>clue anymore. I give up.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenMS/OpenMS/issues/1171#issuecomment-70722989

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by hendrikweisser** [comment]
@timosachsenberg:
> can you upload your binaries to:
https://sourceforge.net/p/open-ms/code/HEAD/tree/THIRDPARTY/Linux/64bit/ and place it there into the folder Fido

I couldn't figure out how to do that, so I sent the files to you by e-mail.

**Comment by timosachsenberg** [comment]
thanks thats perfectly fine.

**Comment by hroest** [comment]
just for additional fun, the test also fails on Mac OS X: http://cdash.openms.de/testSummary.php?project=3&name=TOPP_FidoAdapter_4_out&date=2015-01-27

**Comment by hendrikweisser** [comment]
The failure on Mac seems to be the same problem that @hannesveit reported above (https://github.com/OpenMS/OpenMS/issues/1171#issuecomment-70643063).

**Comment by timosachsenberg** [comment]
another strangeness:
if I add:
```
#include <fenv.h>
...
feenableexcept(FE_ALL_EXCEPT & ~FE_INEXACT);  // Enable all floating point exceptions but FE_INEXACT
```
to the beginning of FidoChooseParameters main function, it runs through but reports other probabilities.

**Comment by jpfeuffer** [comment]
I don't know if this is good news or if I am just adding to the confusion, but I never had problems testing the FidoAdapter on the test data. I am currently changing the behaviour of writing its scores and creating new test outputs.
MacOS 10.10 here.

**Comment by timosachsenberg** [comment]
one more thing to try: compile with  -ffloat-store

**Comment by hannesveit** [comment]
Good idea, but unfortunately doesn't fix it...

**Comment by hannesveit** [comment]
OK, seems like we have a fix. I'll double-check and make a pull request tomorrow.

**Comment by hannesveit** [comment]
It's a -ffast-math problem. We explicitly set this compile flag in CMakeLists.txt. -ffast-math implicitly turns on the flag -ffinite-math-only which means that we cannot deal with infinity and/or NaN anymore. All floats are assumed to have finite value. That's why the isinf(logA) in Numerical::logAdd(...) doesn't work:

```c++
  static double logAdd(double logA, double logB)
  {
      // returns log(a*b)
      if ( logA < logB )
      {
          return logAdd(logB, logA);
      }

      // assume logA <= logB

      // when one of the terms is very small, then just use the other term
      if ( isinf(logA) && logA < 0 )
          return logB;

      return log2( 1 + pow(2, logB-logA) ) + logA;
  }
```

So, which way should we go about this? I think the easiest solution would be to just not use the -ffast-math flag. @hendrikweisser, do you think it has a tremendous effect on performance and should be kept? In this case, we could reformulate the "isinf(logA) && logA < 0" so that it does the right thing. It seems to be the only location in the code where we check for infinity.

**Comment by timosachsenberg** [comment]
```
-ffast-math
Sets -fno-math-errno, -funsafe-math-optimizations, 
-fno-trapping-math, -ffinite-math-only, -fno-rounding-math, -fno-signaling-nans and fcx-limited-range.
```
what if we set everything except -ffinite-math-only? This might at least reduce the perfomrance hit a bit.

**Comment by hannesveit** [comment]
Some of these also look a bit dangerous to me, e.g., -funsafe-math-optimizations could lead to trouble (http://stackoverflow.com/questions/25053186/funsafe-math-optimizations-same-formula-on-two-different-lines-different-resul).

But we could test it and see whether our tests pass on all platforms then...

**Comment by cbielow** [comment]
how much performance gain are we talking about if ffast-math is used?
and what are the absolute running times?
If it saves 2 min... why care?

If its a significant time saver, maybe we can still switch it off while 
finding other ways of reducing runtime? e.g. avoid repetitive 
computations, inlining etc...
(I have not really looked at the code)


Am 2/8/2015 um 11:14 AM schrieb Timo Sachsenberg:

**Comment by hendrikweisser** [comment]
@hannesveit:

> do you think it has a tremendous effect on performance and should be kept?

I don't know. I've taken these settings from the original Fido makefile, but haven't tested their impact.

If I understand it correctly, the whole point of the function "logAdd" is to calculate "log2(a + b)" given "log2(a)" and "log2(b)" in a clever way. (In the comment "returns log(a\*b)", the "\*" should be "+".)
The straight-forward way would be just: `return log2(pow(2, logA) + pow(2, logB));`
"logAdd" short-cuts to return just "log2(a)" if b is zero (or vice-versa) and otherwise saves one call to "pow".

Since there is currently a call to "isinf" in the code, I think compiling with "-ffinite-math-only" (implied by "-ffast-math") is simply not correct, so we can't really do that. I'm also not sure if we can actually do without handling infinities here, if we're taking logarithms of numbers that may be zero.

**Comment by cbielow** [comment]
shouln't
if ( logA < logB )
rather be 
if ( logA > logB )

because otherwise the assumption in the comment below
// assume logA <= logB
is false and pow(2, logB-logA) would actually be pow with negative exponent...

This seems wrong... or am I just blind?

**Comment by hendrikweisser** [comment]
@cbielow: Good point. I think a and b are probabilities (between 0 and 1), so "logA" and "logB" are negative. "logB - logA" in the "pow" expression then stays negative (although it shouldn't matter - either way should work).
The problem that I see is if "logA" is "-inf" initially. Then if "logB" is finite, both will be swapped, and the "isinf" test will be applied to the wrong value. Right?

**Comment by cbielow** [comment]
yep.  Hurray to class tests....

**Comment by hendrikweisser** [comment]
Alright, I've done some more testing. Fido(ChooseParameters) compiled with/without "-ffast-math", and with/without the "logA > logB" fix in "Numerical.h". Then ran the FidoAdapter tests with the different executables.

Without "-ffast-math", "logA > logB" or "logA < logB" doesn't matter. I think Chris is correct in that it should be "logA > logB", but if it's wrong and "logA" is initially "-inf", then the `pow(2, logB-logA)` expression becomes zero and the return value is "logA" ("logB" before the swap), which is still correct. The swap and the "isinf" test are actually unnecessary. They are intended to be an optimization, but that would only work if "logA < logB" is corrected.

The results without "-ffast-math" are slightly different from the "original" version, but not drastically.

With "-ffast-math" and the corrected "logA > logB", the results are different from both the "original" version and the one without "-ffast-math". Here, the parameter choices made by FidoChooseParameters differ from the other versions. Since in this version an "isinf" test is triggered in code compiled with "-ffinite-math-only", I assume the results are incorrect.

My suggestion would be to remove the "-ffast-math" compiler flag from the Fido CMake file, fix the "logA < logB" test in the Fido sources, and adapt the OpenMS FidoAdapter tests accordingly.

**Comment by cbielow** [comment]
+1 to that

And what about replacing the recursion with a simple
swap(logA, logB); 
?

**Comment by hendrikweisser** [comment]
I've made the changes to Fido and to the OpenMS test (see #1246).

@hannesveit, thanks for figuring out the root cause of the problem!

**Comment by hannesveit** [comment]
@hendrikweisser: You're welcome. But at least half of the glory goes to Oliver Serang, who was visiting us on Friday ;)
