### ISSUE TITLE
Windows installation fails due to $PATH length

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1241]
Installation failed because of path lenght:
![install_err](https://cloud.githubusercontent.com/assets/5805014/6078932/20d2e8ae-adff-11e4-9916-4a7fba165e41.png)

Installation LOG:
Current PATH length (1016) too long to modify in NSIS; set manually if needed. Missed entry was: 'C:\Program Files\OpenMS-head\bin'
Current PATH length (1016) too long to modify in NSIS; set manually if needed. Missed entry was: 'C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\pwiz-bin'
Current PATH length (1016) too long to modify in NSIS; set manually if needed. Missed entry was: 'C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\OMSSA'
Current PATH length (1016) too long to modify in NSIS; set manually if needed. Missed entry was: 'C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\XTandem'
Current PATH length (1016) too long to modify in NSIS; set manually if needed. Missed entry was: 'C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\MyriMatch'
Current PATH length (1016) too long to modify in NSIS; set manually if needed. Missed entry was: 'C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\MSGFPlus'
Current PATH length (1016) too long to modify in NSIS; set manually if needed. Missed entry was: 'C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\Fido'

PATH until failure:
C:\Program Files (x86)\Thermo\Foundation\;C:\Program Files\ChemAxon\JChem\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Calibre2\;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\Microsoft SQL Server\80\Tools\Binn\;C:\Program Files\Java\jre8\bin\;C:\Program Files\Thermo\Compound Discoverer 1.0\bin;C:\Program Files\Thermo\Proteome Discoverer 2.0\System\Release;C:\Program Files\OpenMS-head\bin;C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\pwiz-bin;C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\OMSSA;C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\XTandem;C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\MyriMatch;C:\Program Files\OpenMS-head\share\OpenMS\THIRDPARTY\64bit\MSGFPlus

So something has to be done, may we can use relative paths for the thirdparty tools and only add the OpenMS head directory to the PATH?

**Comment by cbielow** [comment]
relative path to what?
You cannot guaraentee what the workingdir of any TOPP tool (i.e. the 
adapters) is, thus relative paths wont help.

@TimoSachsenberg:
maybe NSIS 3 can help here?

Alternatively, we could teach the adapters to look for the executables 
in a path relative to their own location (which is more stable than 
working_dir), if the executable is not given as full path (which would 
be the default param). This is how TOPPAS currently finds its TOPP tools 
(they are in the exact same directory).


Am 2/6/2015 um 12:57 PM schrieb FabianAicheler:

**Comment by timosachsenberg** [comment]
This limitation seems also be present in NSIS 3. As a quick workaround we could just use one of the special builds at:
http://nsis.sourceforge.net/Special_Builds

Which increase string length from 1024 to 8192

"Please note that NSIS default build has a string limit of 1024 characters. If the PATH is bigger, this function will replace the whole PATH instead of just appending to it. Temporarily you can use the large strings build of NSIS to avoid this problem."

**Comment by jpfeuffer** [comment]
I am working on deploying the modified makensis.exe with its accompanied "Stubs" on our build machine. However, makensis crashes everytime without a meaningful error.

'''
!include: "EnvVarUpdate.nsh"
!define: "ENVVARUPDATE_FUNCTION"=""
----------------------------------------------------------------------

NSIS String Functions Header File 1.09 - Copyright 2004 Diego Pedroso

----------------------------------------------------------------------

 (C:\Program Files (x86)\NSIS\Include\StrFunc.nsh:52)
$ {StrTok} - Copyright 2004 Diego Pedroso - Based on functions by "bigmac666" (macro:STRFUNC_FUNC:11)
$ {UnStrTok} - Copyright 2004 Diego Pedroso - Based on functions by "bigmac666" (macro:STRFUNC_FUNC:5)
'''
It reports the above, where everything seems okay but then Windows suddenly throws an error:
"makensis stopped working..." etc.
Seems like one of the StringFunctions in the StrFunc script has problems. But I have no idea how to debug it further.

**Comment by cbielow** [comment]
If the 8k NSIS build does not work, here are the alternatives I can see:

1) put ALL thirdparty executables into a single bin directory (might be 
recipe for desaster, but would not bloat path). We can test if it works 
with the current tools. If they have no conflicting files (by name, or 
c++ runtimes or whatever), this is the easiest solution and the most 
save in terms of PATH-length.

2)
expanding PATH could be done using double-expansion, i.e.

SET OMS_TP=C:\.....\OpenMS-2.0\bin\thirdparty
SET PATH=%PATH%;%OMS_TP%\OMSSA;%OMS_TP%\XTANDEM; ...

This way, we might be able to restrict ourselves to 1k on most machines 
(depending on how long their PATH was before OpenMS installs).
It would also be friendly towards other NSIS installers, since we dont 
bloat PATH with our stuff too much.
(some care has to be taken on SYSTEM vs USER variables of PATH, see 
http://superuser.com/questions/27826/why-cant-windows-handle-an-environment-variable-in-path)

3) ship our installer with a decent third party tool, e.g.
http://www.p-nand-q.com/download/gtools/pathed.html
And replace the current path handling (append/delete) with calls to that 
(this probably gives any installers running after OpenMS some headaches, 
since the PATH is rather full then...)

cheers
Chris




Am 2/10/2015 um 8:56 PM schrieb jpfeuffer:

**Comment by timosachsenberg** [comment]
hmm
On older windows (Windows Server 2003 and XP) there seems to be a rather low limit we can't easily work around (http://support.microsoft.com/kb/906469?wa=wsignin1.0).
Don't know if we still want to support these.

**Comment by cbielow** [comment]
This would then argue for solution #1?!

But I'd not worry about Windows XP at all, since its 32bit for 99% of 
all installations (i.e. 2GB RAM userspace) and we can savely assume that 
most people have access to at least Vista, if not Windows 7.


Am 2/11/2015 um 11:05 AM schrieb Timo Sachsenberg:

**Comment by timosachsenberg** [comment]
Solution 2 also seems not ideal as we usually want to install OpenMS for all users. This wouldn't be possible if I understood the linked page.

So its 1 or 3 I guess? If we ship the pathed tool can we directly call it (e.g. are  elevations propagated to the called tool)?

**Comment by cbielow** [comment]
Am 2/11/2015 um 11:22 AM schrieb Timo Sachsenberg:
> Solution 2 also seems not ideal as we usually want to install OpenMS for all users. This wouldn't be possible if I understood the linked page.

IMHO it should be if we register OMS_TP as system variable. Then 
expansion works on the system PATH, right?

>
> So its 1 or 3 I guess? If we ship the pathed tool can we directly call it (e.g. are  elevations propagated to the called tool)?

Elevation is propagated AFAIK.

**Comment by timosachsenberg** [comment]
Yep, then it should work.

**Comment by jpfeuffer** [comment]
Seems like I got NSIS 3.0 working with the modified *.exe.
Can somebody test the new HEAD installer?
http://ftp.mi.fu-berlin.de/pub/OpenMS/nightly_binaries/

**Comment by timosachsenberg** [comment]
works

**Comment by timosachsenberg** [comment]
Can we close this? I think we also need to update the windows installer repository accordingly

**Comment by jpfeuffer** [comment]
Yes, although most changes are just modifications to NSIS which is of course not part of the repo. I will commit them ASAP.

**Comment by timosachsenberg** [comment]
releated to https://github.com/OpenMS/OpenMS/issues/1209
