### ISSUE TITLE
beta testing MyriMatchAdapter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1255]
I am testing the MyriMatchAdapter on the 10/02/15 Windows nightly build with MyriMatch [1].

On both command line and in TOPPAS the search does not finish over night. No crash. No progress is reported when loading the mzML file.

[1] MyriMatch Windows x86 64 release 2.2.140 http://fenchurch.mc.vanderbilt.edu/software.php

**Comment by cbielow** [comment]
MM tends to be REALLY slow, exponentially slower with each modifications 
(it starts to seriously hurt from 2-3 onwards).
If you used a big dataset, running over night is not uncommon.
If I remember correctly, we decided not to forward MM output to the user 
because it was just too much.
Try a smaller file, maybe?

Am 2/12/2015 um 2:09 PM schrieb Lars Nilse:

**Comment by lars20070** [comment]
Yep. A small subset (25MB, 50s) finishes in 4 min. So my complete 1.5GB file should be processed in 4 hours i.e. over night. But is not. An MS2 spectral search should behave linearly, right?

@cbielow But it would still be nice to report progress when loading.

**Comment by lars20070** [comment]
Ok. If MyriMatch is that slow, we might even think about taking it out. One less adapter to support.

**Comment by oliverschilling** [comment]
Hello - I did a few command line test with MyriMatch and I cannot replicate the long processing times that were observed when using the MyriMatch adapter. So rather than taking it out, we should find out why MM under OpenMS is much slower than compared to its direct usage at the command line.

Which leads to me the same question (and perhaps the same answer...) as before, when I asked the same thing for the tandem adapter: where does opens store the parameter etc that are passed on to MyriMatch?

**Comment by lars20070** [comment]
I have done some more testing of the adapter. A typical search finishes in 50 min to 1 hour. Different settings might take longer, see mods mentioned by @cbielow. If we find a discrepancy in results or runtime between command line and adapter, we can re-open the issue.
