### ISSUE TITLE
absolute path in TOPPAS workflows

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1265]
When toppas workflows are moved/copied to other folders, the paths to the input files are changed accordingly.

It would be better if all input files and their absolute paths remain unchanged. For example in the case of a second analysis with same database and input files. None of the inputs should change.

**Comment by mwalzer** [comment]
I cannot reproduce this. Maybe you did not specify the absolute path yourself? Also, mind the '~'

**Comment by lars20070** [comment]
@mwalzer Here an example. A test workflow in  
/Users/lars/Desktop/proteotypic/test.toppas
PeptideIndexer uses a fasta in the same folder.
/Users/lars/Desktop/proteotypic/EColi_uniprot_plus_shuffled.fasta

Copying the workflow to
/Users/lars/Desktop/test.toppas
changes the fasta to
/Users/lars/Desktop/EColi_uniprot_plus_shuffled.fasta

Reproducible in Windows and OS X.

**Comment by timosachsenberg** [comment]
can you copy the toppas files to a gist and provide them here

**Comment by Stortebecker** [comment]
I can reproduce this. Moving a .toppas file changes some input file paths. When moved e.g. from D:\folder\ to D:\another_folder\, the input file location also changes to D:\another_folder\.

Changing of the file paths happens only, if input datafiles are in the same folder (e.g. D:\folder\) as the .toppas file or in a subfolder to this (e.g. D:\folder\subfolder\). I the file path is completely different, it remains unchanged (e.g. D:\another_folder\). 

I guess its a question of taste, if moving should automatically change the paths.

**Comment by cbielow** [comment]
The behaviour you feel should be changed is desired.
TOPPAS currently stores relative paths. 
This allows you to:
 + move a TOPPAS project (with all its dependent files) from one machine to the next without having to worry about drive letters etc. Just maintain the file tree structure (which could be entirely flat).
 + move workflows across platforms: what would happen if Windows sees absolute paths starting with /usr/...? Right: it would have to throw them away completely, because there is no robust way to recover the relative paths.

If for whatever reason you really want absolute paths, then just write them manually into the TOPPAS file. Just make sure that you don't save the workflow within TOPPAS again -- it will revert them to relative paths.

**Comment by lars20070** [comment]
For moving projects between machines and platforms this behaviour makes sense.

Here is our use case. A central Windows server with access for all users. The fasta databases are stored in one location. Often the raw files stay in one place as well. But analysis workflows and results are shared and copied between users, i.e. paths to the fasta files often need to be adjusted. Since users make small changes in the workflows in TOPPAS, changing paths in *.toppas manually is not a good option.

A changed behaviour would make daily work with OpenMS easier for us. But I do not really feel strongly about this.
