### ISSUE TITLE
MSGF+ crash while generating index files

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1359]
Running MSGF+ on a new fasta database for the first time, the search engine generates index files *.canno, *.cnlcp, *.csarr and *.cseq. If two or more MSGF+ processes try to generate these index files simultaneously, one of the MSGF+ processes crashes. The problem was previously described here https://github.com/OpenMS/OpenMS/issues/1251#issuecomment-74062468.

Most biological datasets comprise of multiple fractions. So this issue does occur when running MSGF+ on such a multi-fraction dataset with a new database.

**Comment by ypriverol** [comment]
Can you explain this in details. I'm working in a new version of ms-gf+ with better performance and also a couple of features like misscleavage definition. Are all these process running in the same database?

**Comment by timosachsenberg** [comment]
There is no locking done for the index files so these might get written / read in parallel leading to a crash if multiple processes perform a search.

**Comment by mwalzer** [comment]
So this is basically not an OpenMS issue?

**Comment by hendrikweisser** [comment]
> So this is basically not an OpenMS issue?

It's not caused by OpenMS, but it affects OpenMS.

**Comment by jpfeuffer** [comment]
This came up again in recent Tutorials:

IMHO we should proceed like with OMSSA and as described by @cbielow in https://github.com/OpenMS/OpenMS/issues/1251#issuecomment-74062468
We should expect the index files to be present and otherwise return an error with instructions on how to create them.
Optionally we could provide an MSGFIndexer tool but the command to run is very basic and we do not have an OMSSAIndexer either. (Maybe we can provide supplementary KNIME nodes)
See @cbielow last suggestion:
```
Next solution: MSGFAdapter expects index files to be present and quits
otherwise, giving you a commandline like:
std::cout << "Execute: java -Xmx3500M -cp " <<
str_MSGFjar_with_full_path << " edu.ucsd.msjava.msdbsearch.BuildSA -d "
<< fasta_from_Param_with_full_path << " -tda " << TDA_from_Param << "\n";
Since this is not dependent on the working directory, the user can
simply open a terminal and copy&paste the code.
```
