### ISSUE TITLE
IDPosteriorErrorProbability does not finish

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1376]
The IDPosteriorErrorProbability tool runs for >12 hours on this file [1] but does not finish. Tested on Windows and OS X. Neither warnings or progress are given. The toppas pipeline [1] shows the previous steps of the workflow.

[1] https://www.dropbox.com/sh/21jrrokl3rl2tjr/AABuqUt5BiMbhxuSh3LOucpSa

**Comment by timosachsenberg** [comment]
which version? OpenMS 2.0? current develop?

**Comment by lars20070** [comment]
Current develop.

**Comment by timosachsenberg** [comment]
does the exact same pipeline run through on OpenMS 2.0?

**Comment by lars20070** [comment]
No. Same problem on 2.0. IDPosteriorErrorProbability module not finished after 70 min.

**Comment by jpfeuffer** [comment]
We experienced the same issue while analyzing simulated data.
We guessed that the algorithm is not able to fit a negative distribution to the scores (because the simulation is "too good"), therefore not converging.
Maybe you also have a distorted score distribution. It would be interesting to look at it.
However, I might as well be just a bug in the code.

**Comment by lars20070** [comment]
@jpfeuffer Did you use MSGF+ in your analysis of simulated data. We see no problems with X!Tandem.

**Comment by timosachsenberg** [comment]
did it ever work for MSGF+?

**Comment by lars20070** [comment]
Yes. We beta tested XTandem/Fido and MSGF+/Fido on SILAC and dimethyl data on develop a few days before the release.

**Comment by jpfeuffer** [comment]
That is a good question. I think MSGF+ was also involved in our analyses (maybe indirectly through ConsensusID). Hopefully @liangoaix can clarify this.
Maybe the only_top_hits parameter makes a change, since MSGF+ reports multiple candidates (as opposed to XTandem).
What I found out (on a first quick look): There is indeed no other stopping criterion than a goodness of fit in PEPModel.cpp
That means when it can't fit well, it doesn't stop. It should at least stop after a certain amount of iterations.

**Comment by oliverschilling** [comment]
PEP worked fine with the exact same mzML data but using tandem.

**Comment by liangoaix** [comment]
MSGF+ does not support simulated RAW data due to the missing of native spectrum identifier format.

**Comment by liangoaix** [comment]
i did not find the original paper of our IDPEP model. We should take a closer look at it.

**Comment by timosachsenberg** [comment]
"It should at least stop after a certain amount of iterations."
Maybe we should output the the goodness of fit and see how it behaves.

**Comment by timosachsenberg** [comment]
Also - can somebody also plot the scores from the idXML lars provided or (if they are transformed in the IDPEP tool the transformed ones?)
We should easily see if the scores a degenerated (e.g. no bumps visible).

**Comment by lars20070** [comment]
+1 We should add the distribution as additional debug output to IDPEP.

**Comment by jpfeuffer** [comment]
So EM stops, when ML doesnt get better anymore. These are the improvements after each step.
As you can clearly see, EM gets stuck in never ending loop. The two solutions are: stop EM after a while and take a possbily bad result (quick), or make EM more robust (I think there are some methods preventing it from getting into loops).

ML improvement4857.55
ML improvement419.25
ML improvement4390.57
ML improvement4106.98
ML improvement2064.61
ML improvement1851.69
ML improvement5206.14
ML improvement4857.55
ML improvement419.25
ML improvement4390.57
ML improvement4106.98
ML improvement2064.61
ML improvement1851.69
ML improvement5206.14
ML improvement4857.55
ML improvement419.25
ML improvement4390.57
ML improvement4106.98
ML improvement2064.61
ML improvement1851.69
ML improvement5206.14
ML improvement4857.55
ML improvement419.25
ML improvement4390.57
ML improvement4106.98
ML improvement2064.61
ML improvement1851.69
ML improvement5206.14 ...

Scores look almost perfectly bimodal.
![hek-lysate_scoreplot](https://cloud.githubusercontent.com/assets/8102638/7392655/77fd7e9e-ee89-11e4-8191-4b37ad2ce3c9.png)

**Comment by liangoaix** [comment]
It seems this distribution does not contain decoys. Or did you only plot target distribution?

**Comment by timosachsenberg** [comment]
thanks! wow - looks very nice indeed.

Could we e.g. after at e.g. 15000 steps just take the best fit from the last 5000 steps?
I mean it is a hack but would select a local optimum

**Comment by lars20070** [comment]
Let's use Timo's hack as hot-fix, but resolve this properly for 2.1. It's a textbook distribution and shouldn't run into endless loops.

**Comment by jpfeuffer** [comment]
Another suggestion: We could also force the algorithm to reinitialize when it gets stuck.
WHEN the algorithm is converging, it is usually really quick. So several runs are no problem.

**Comment by timosachsenberg** [comment]
Probably simpler but not guaranteed to work - should we try this?

**Comment by lars20070** [comment]
+1 Good enough, if this works on the above example.

**Comment by hendrikweisser** [comment]
I'd say do both - limit the number of iterations in the optimization (adjustable via an advanced parameter); if the optimization doesn't converge, try again with a different seed (number of tries adjustable via an advanced parameter); if it never converged, pick the best fit out of all tries and report a warning.

**Comment by timosachsenberg** [comment]
also a possibility but note that mere convergence after restart doesn't mean that the fit is now better than one encountered during the oscillation

**Comment by jpfeuffer** [comment]
Long story short for @lars20070 : Set the "smallest_e_value" to "10^(-40)" and it should work for a quick hack or wait for the PR.

So after long debug sessions with @liangoaix, we found out that the actual problem lies in the "smallest_e_value" parameter, which is set to 1e-20 by default but reaches 1e-40 in your results.
The code will set all the e-values below to this value which will give a huge peak at this "best" score.
Then it initializes the correct distribution to this value (the mean of the values above 70th quantile, which might be a bad initialization strategy in general).
Now, EM starts with a perfect mean for one Gaussian and the SD for it goes to 0, leading to numeric instabilities which runs into a loop somehow.

In the new PR, I suggest a removal of the "smallest_e_value" parameter and set it to the smallest possible double value.
Although the problem would be resolved by that, I also introduced the max_nr_iterations parameter that applies when the algorithm does not converge.
Another change is that I let the algorithm fail, when the likelihood decreases, which should never happen in EM (except with numeric instabilities).

An open question is the improvement of the initialization strategy and @hendrikweisser 's suggestion of multiple runs. Other improvements could include a better convergence criterion.

In general we think, that IDPEP indeed seems to be a rather unfinished tool, with quite some hacks.
E.g. it actually only fits Gaussians as opposed to the description and the parameters.

**Comment by lars20070** [comment]
Very good. So everything below the smallest_e_value is not thrown away but collected at the smallest_e_value.

@jpfeuffer We will wait for #1403 and then test again.

**Comment by oliverschilling** [comment]
I don't seem to be able to enter a "smallest e-value" below 1e-019. I can enter higher values, but for smaller ones IDPEP jumps back to 1e-019. What am I missing here? Thanks!

**Comment by lars20070** [comment]
@jpfeuffer Can we please merge #1403?
