### ISSUE TITLE
 Use add_compiler_export_flags in the build system

### ISSUE THREAD

**Issue by wtbxsjy** [OpenMS/OpenMS#1397]
I am building OpenMS on an old x86_64 CentOS server(CentOS 5.5), everything seems fine until final make step.(cmake version: 3.2.2;qt version: 4.7.1)
the source code is download from github, and all the contributions are installed properly with no warnings or errors.(As it is said on page http://ftp.mi.fu-berlin.de/pub/OpenMS/release2.0-documentation/html/install_linux.html)

then 'make targets' and choose OpenMS library, OpenMS library can be maked properly.
but when building TOPP, several errors come out as below:

```
  1 CMakeFiles/EICExtractor.dir/EICExtractor.cpp.o: In function `main':
  2 EICExtractor.cpp:(.text+0x76): undefined reference to `OpenMS::String::String(char const*)'
  3 EICExtractor.cpp:(.text+0x85): undefined reference to `OpenMS::String::String(char const*)'
  4 EICExtractor.cpp:(.text+0x9c): undefined reference to `OpenMS::String::String(char const*)'
```

......(more than 6000 lines)

all of the errors are such 'undefined reference to' error.

could you please help me to solve it?

**Comment by kennyluck** [comment]
(I am a colleague of @wtbxsjy.) This seems to have to do with the fact that CMake-generated `OpenMS/OpenMSConfig.h` had

    #define OPENMS_DLLAPI

instead of the expected

    #define OPENMS_DLLAPI  __attribute__((visibility("default")))

so the workaround was to remove the `-fvisibility=hidden` line from `cmake/compiler_flags.cmake`. The problem is perhaps caused by having two GCC versions on our machine, one of which supports `-fvisibility=hidden` and the other not.

While this is mostly our problem, I think you could use [`add_compiler_export_flags`](http://www.cmake.org/cmake/help/v3.0/module/GenerateExportHeader.html) instead of manually adding `-fvisibility=hidden` in `cmake/compiler_flags.cmake` to avoid a problem like this.

**Comment by aiche** [comment]
@kennyluck Good point, I will integrate your suggestions into the build system. We need to discuss with whether this should go to a 2.0.1 or 2.1 release.

**Comment by jpfeuffer** [comment]
I am currently preparing a PR for this. One question that I have to other developers is, if we should make visibility=hidden and inline-visibility-hidden a standard.
One thing that I had problems with is that you also have to build your dependent libraries with the exact same settings, otherwise clang complains with thousands of warnings like:
```
ld: warning: direct access in function '___cxx_global_var_init' from file 'CMakeFiles/OpenMS.dir/source/ANALYSIS/ID/IDDecoyProbability.cpp.o' to global weak symbol 'boost::math::lanczos::lanczos_initializer<boost::math::lanczos::lanczos17m64, long double>::initializer' from file '/usr/local/lib/libboost_math_c99-mt.a(erf.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
Since the standard choice for BOOST_USE_STATIC is On, the warnings are also there by default on MacOS with homebrew Boost (which seems to use the visibility flag only for the shared libraries, with no obvious option to change it). You can overcome this, though, by building Boost on your own or changing the flags in the contrib CMakes.
Any opinions on what to change and how to set the defaults?

**Comment by hendrikweisser** [comment]
> One thing that I had problems with is that you also have to build your dependent libraries with the exact same settings, otherwise clang complains with thousands of warnings like:

Are there just warnings with no other negative consequences? If so, an option might be to just suppress the warning with a clang flag (like we do for some others already).

**Comment by jpfeuffer** [comment]
While I did not see any negative consequences like new failing tests, I am not sure if there is a flag to suppress/disable it. There might be some ways to hide/limit them though  (http://stackoverflow.com/questions/3409448/how-do-you-suppress-gcc-linker-warnings).
I am also not quite sure about the severity. I think for an end user or OpenMS developer this should be fine. It might give problems, when somebody uses e.g. boost and OpenMS in another project but then the warning is quite explanatory.

**Comment by hendrikweisser** [comment]
> Since the standard choice for BOOST_USE_STATIC is On, the warnings are also there by default on MacOS with homebrew Boost (which seems to use the visibility flag only for the shared libraries, with no obvious option to change it). You can overcome this, though, by building Boost on your own or changing the flags in the contrib CMakes.

Can we just make sure that we have one (mostly fail-safe) way for people to install OpenMS on Mac, that works as documented in our installation instructions? If that involves building Boost from source then so be it.

**Comment by hroest** [comment]
The main reason for visibility hidden was for developers to have a similar setup on Linux as on Windows where hidden visibility is the default, see #833 

I dont think we should therefore have to change too much on our workflow, as long as travis tests use visibility hidden
