### ISSUE TITLE
TOPPAS: derive output names from inputs passed to "in"

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1480]
In TOPPAS, the names of output files of a tool are derived from the names of the input files (ideally just the file extension changes). However, when a tool receives inputs from multiple different parameters, a decision has to be made which input parameter to use as source for the output filenames. Currently the numbering of the nodes seems to be used as a criterion. Unfortunately, this can lead to cases where e.g. for PeptideIndexer, the output idXML is named after the input FASTA file, not after the input idXML.

The prevalent convention in OpenMS is to use the parameter name "in" for the primary input of a tool. Based on this, it would make sense to add a special case to TOPPAS, whereby output filenames are derived from filenames passed to the "in" parameter of a tool, if a parameter of this name exists.

**Comment by cbielow** [comment]
agreed. I think I have a branch somewhere which does this (and other 
things). Until I find the time to fix this: If you provide more than one 
input file and only a single FASTA file (in recycling mode), TOPPAS will 
currently take the -in automatically, since recycled modes cannot be 
used in this case. Untested: If you have single inputs and set one of 
them to recycle (a NOOP in this case), it might already take the one you 
want :) (all these are workarounds, I know).

Am 6/25/2015 um 12:21 PM schrieb hendrikweisser:
