### ISSUE TITLE
MapAlignerPoseClustering naming of output files incorrect

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1574]
Let map_1, map_2, ... map_12 be twelve input featureXML. The tool writes map_10, map_10.0, map_10.1, ... map_10.10 to the featureXML output. That breaks our subsequent workflow.

**Comment by lars20070** [comment]
The subsequent MapRTTransformer tool crashes with `Trailing text argument(s)` [1].

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/TOPPBase.cpp#L244

**Comment by VOOginga** [comment]
On Monday, we updated our OpenMS pipeline and what followed next is the MapRTTransformer crashing. There most likely cause is that the output of the MapAlignerPoseClustering is numbered or named differently leading to a crash. Would you kindly please correct this error?

**Comment by lars20070** [comment]
Guess it's related to these [2] recent changes in #1531.

[2] https://github.com/OpenMS/OpenMS/pull/1531/files#diff-6c4546aeb9f343ca6a1c60911979030cR117

**Comment by hendrikweisser** [comment]
> Let map_1, map_2, ... map_12 be twelve input featureXML. The tool writes map_10, map_10.0, map_10.1, ... map_10.10 to the featureXML output.

This is just the way TOPPAS names output files and hasn't changed in quite some time, as far as I'm aware. Sorted lexicograpically, "map_10" is the first input file, so this name is used for the first output file. Subsequent outputs are named by appending ".0", ".1", etc.
There's an old ticket for this [here](https://github.com/OpenMS/OpenMS/issues/620) and a partial fix that hasn't been merged yet [here](https://github.com/OpenMS/OpenMS/pull/942).

**Comment by hendrikweisser** [comment]
The actual cause for the problems here seems to be the change from input file list to single input file in MapRTTRansformer in #1531, as pointed out by Lars above.

> Why was the file list changed to a file?

Because I didn't see any reason for the added complexity of dealing with a list of files (see first point [here](https://github.com/OpenMS/OpenMS/issues/1523#issue-95664529)). Obviously I didn't anticipate that it wouldn't work in TOPPAS any more - sorry for that.
If there is no easy change to a TOPPAS pipeline that will make it work, I'll change it MapRTTransformer back to using a file list.

**Comment by lars20070** [comment]
@hendrikweisser I agree with both comments. Please revert MapRTTransformer to file list. Thanks.
