### ISSUE TITLE
KNIME FidoAdapter "prob_param" not working

### ISSUE THREAD

**Issue by julianu** [OpenMS/OpenMS#1575]
I played a bit around with the FidoAdapter in KNIME and came across a problem with the prob_param. I need to run IDPosteriorErrorProbability with "prob_correct=false" in my case.

I am not sure, whether the input of this param is evaluated at all or erronous in some cases, tested scenario:
workflow 1: IDPosteriorErrorProbability with "prob_correct=true", FDR calculation and filtering, FidoAdapter with "prob_param=Posterior Probability_score"
workflow 2:  IDPosteriorErrorProbability with "prob_correct=false", FDR calculation and filtering, FidoAdapter with "prob_param=Posterior Error Probability_score"

I would assume from the FidoAdapter documentation to get the same results here, but the results are different. I think (but this is not thoroughly tested), that in one workflow the correct score from the UserParam is used, in the other, though, the score-tag of the PeptideHIt, which is a q-value at this moment.

For now a workaround for me is to re-write the idXML file and edit the score-tag to be the PosteriorProbability for Fido only. With this workaround the results between the FidoAdapter and a standalone call of Fido are identical.

**Comment by hannesveit** [comment]
If I understand this correctly, your assumption implies that FidoAdapter, based on whether the UserParam it is supposed to read the scores from, also changes the way it treats these scores, i.e., that FidoAdapter would know it is dealing with error probabilities instead of probabilities when you set "prob_param=Posterior Error Probability_score"... is that correct?

I'm not really familiar with the code, but I think FidoAdapter *always* expects the scores to be peptide probabilities and not error probabilities. The prob_param just tells FidoAdapter where it can find the probabilities.

**Comment by julianu** [comment]
Yes, that is what I thought, as the documentation says, the scores have to be posterior probabilities, but "Inputs from IDPosteriorErrorProbability (without prob_correct) or from ConsensusID are treated as special cases".
If I just got this wrong, the adapter works perfectly.

**Comment by liangoaix** [comment]
Hi,
how different are your results? Are they rather similar or totally different? I think FidoAdapter can work in this way if you don't run FDR and filter before the FidoAdapter. Because these two special cases (as described in the documentation) are only possible to be considered when they are the scores  but not the user_param (If you run FDR after the IDPEP, then the Posterior error probability score is stored in the user_param).

**Comment by julianu** [comment]
Ok, then I just got the documentation wrong.
The results are totally different, but that's perfectly normal if the error probabilities are treated as probabilities.

**Comment by liangoaix** [comment]
I tested the second workflow without FDR and set "prob_correct=false" in IDPEP, "prob_param=" in FidoAdapter, the results were the same then.

**Comment by julianu** [comment]
I think, we sorted this out and it was a misunderstanding by me.
Seems like for know the input must come from IDPosteriorErrorProbability or ConsensusID, and not from FalseDiscoveryRate.
I would suggest to probably mark this solved and make this a wish for future releases.

**Comment by hendrikweisser** [comment]
I've addressed this in pull request #1631. Instead of using FidoAdapter's "prob_param" (now removed), run the dedicated IDScoreSwitcher utility to define which score to use. In your case, that means:
- workflow 1: `IDScoreSwitcher -in ... -out ... -new_score "Posterior Probability_score" -new_score_orientation higher_better -new_score_type "Posterior Probability"`
- workflow 2: `IDScoreSwitcher -in ... -out ... -new_score "Posterior Error Probability_score" -new_score_orientation lower_better -new_score_type "Posterior Error Probability"`

FidoAdapter should then work correctly in both cases.
