### ISSUE TITLE
TOPPAS crash in OS X

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1589]
RTAnnotator crashes in one of my TOPPAS workflows with the following error message.

`14:22:27 NOTICE: RTAnnotator of node #6 started. Processing ...
Annotated 63698 peptides.
Error: File not found (the file '/var/folders/1r/lb4bxs4d2gx93zsb18_b65100000gn/T/2015-09-04_141121_immz1179.molmed.uni-freiburg.de_8800_1/TOPPAS_tmp/FDR5/006_RTAnnotator/out/SILAC_2_centroided_MS1_MS2.idXML_tmp2' could not be found)`

On the command line RTAnnotator runs through without problems.

**Comment by cbielow** [comment]
This is really hard to reproduce, so you'll need to do some digging yourself:

TOPPAS has internal limits on how long a filepath (220 chars) and certain subdirectories can be, due to certain OS limitations (e.g. NTFS).
Looking at the file above, that does not seem to be the issue here (179 chars, if I count correctly).

The error seems to occur only AFTER RTAnnotator has supposedly written its output and TOPPAS wants to copy it to an output node (or use it in the downstream node) -- hard to tell since I don't know your pipeline.

So:
Q1: does the path exist?
Q2: is RTAnnotator creating the file? (if yes, under a different name???; if no, why does RTAnnotator not crash while trying to create it??)

**Comment by lars20070** [comment]
The directory exists. The file in it does not.

I also specified a  new temp folder in OpenMS.ini. Same crash.

**Comment by lars20070** [comment]
Here the workflow. https://gist.github.com/lars20070/cd227550a8ee5584e323

**Comment by cbielow** [comment]
use

$> TOPPAS --debug

in a console, run the pipeline, let it fail and then re-run the 
RTAnnotator command (which is shown in the command window) separately 
(leave TOPPAS open while doing it!).

Is the file created now?


Am 9/7/2015 um 3:42 PM schrieb Lars Nilse:

**Comment by lars20070** [comment]
`immz1179:~ lars$ RTAnnotator -in /Users/lars/temp/OpenMS/2015-09-07_161502_immz1179.molmed.uni-freiburg.de_2320_1/TOPPAS_tmp/FDR5/003_IDFileConverter/out/SILAC_2_centroided_MS1_MS2.idXML -in_msref /Users/lars/Projects/20150709_FixedRatio_TripleTOF_Joern/SILAC_2_centroided_MS1_MS2.mzML -out /Users/lars/temp/OpenMS/2015-09-07_161502_immz1179.molmed.uni-freiburg.de_2320_1/TOPPAS_tmp/FDR5/005_RTAnnotator/out/SILAC_2_centroided_MS1_MS2.idXML_tmp2 -ini /Users/lars/temp/OpenMS/2015-09-07_161502_immz1179.molmed.uni-freiburg.de_2320_1/TOPPAS_tmp/FDR5/005_RTAnnotator/RTAnnotator.ini
Annotated 64191 peptides.
Error: File not found (the file '/Users/lars/temp/OpenMS/2015-09-07_161502_immz1179.molmed.uni-freiburg.de_2320_1/TOPPAS_tmp/FDR5/005_RTAnnotator/out/SILAC_2_centroided_MS1_MS2.idXML_tmp2' could not be found)`

Crash reproduced from command line.

**Comment by lars20070** [comment]
`/Users/lars/temp/OpenMS/2015-09-07_161502_immz1179.molmed.uni-freiburg.de_2320_1/TOPPAS_tmp/FDR5/005_RTAnnotator/out`

The folder exists and is empty.

**Comment by lars20070** [comment]
Looks good to me. https://github.com/OpenMS/OpenMS/blob/develop/src/utils/RTAnnotator.cpp#L179

**Comment by lars20070** [comment]
On the command line, an -out file of the form `*.idXML` does not crash. But any -out file of the form `*.idXML_tmp2` does.

**Comment by cbielow** [comment]
actually:

https://github.com/OpenMS/OpenMS/blob/develop/src/utils/RTAnnotator.cpp#L176

is very dangerous, since it will first check the filename, and if the extension is unknown, it will check the content (of a file which is not yet created).
Clearly, this check needs to be done on the filename only, and we need an out_type (as done for many other tools, such as FileConverter).

**Comment by hendrikweisser** [comment]
Before you make fixes to RTAnnotator, note that I've removed it in pull request #1587.

**Comment by lars20070** [comment]
Thanks for spotting this @cbielow. Now the `File not found` makes sense to me.

@hendrikweisser There is no tool replacing `RTAnnotator` in #1587, right? At the moment, I use MS-GF+ (without adapter) / `IDFileConverter` / `RTAnnotator` to generate search results for Q Star and TOF data. The `MSGFPlusAdapter` does not work on all data. https://github.com/OpenMS/OpenMS/issues/1409#issuecomment-104916064

**Comment by hendrikweisser** [comment]
@lars20070:
> There is no tool replacing RTAnnotator in #1587, right?

IDFileConverter has gained the ability to add RTs to mzid (which you requested in #1437). I wouldn't have removed RTAnnotator without a replacement of its functionality.

**Comment by lars20070** [comment]
Ah, I did not see this. Thanks a lot @hendrikweisser. - Then this issue is resolved.
