### ISSUE TITLE
UserParam with CV only should also contain the name as comment in XMLs 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1697]
Writing plain CVs in UserParams to XML e.g. "MS:0001234" might be extended by placing the CV name in the same line by the XML writer (if it is a known CV term).

**Comment by hendrikweisser** [comment]
This is a good point. One use case to consider here is switching between different ID scores after importing an mzIdentML file (IDFileConverter -> IDScoreSwitcher). As far as I know, scores from the mzIdentML will be represented by their CV terms in the idXML; this makes it difficult for users to know what the scores mean (without consulting the vocabulary) and to switch between different ones.

**Comment by mwalzer** [comment]
What I might add regarding that is that 
  - xml's are sometimes advertised as human readable, but their intended main usecase is machine readability (with added ease of development and debugging as there is the chance of eyeballing it)
  - and  IDScoreSwitcher could for example do the lookup in the CV and eventually give the user more than just a name but a description as well. 
  - lastly CV accessions because there is the family (i.e. for each search engine) of MS:1001872 ! distinct peptide-level e-value and then there is e-value EValue evalue and the user still does not know whether that value is psm or peptide-level or from which search engine - at least it is supposed like that, of course there is room for improvement at the CV but that improvement will increase if we force the use of CVs.

**Comment by mwalzer** [comment]
so, in the end I support that idea
