### ISSUE TITLE
FileMerger with fasta input files

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1728]
Often one needs to combine different databases for a search. For example, a species database with contaminants and mycoplasma. `FileMerger` should allow `fasta` files as input, and therefore appending databases within the workflow.

**Comment by hendrikweisser** [comment]
I'm not opposed to this, but on a UNIX system you can simply use "cat" to append multiple (FASTA) files.

If we add this functionality to FileMerger, there should be a check for duplicate protein accessions in the files, because those would trip up some search engines (e.g. Mascot). Ideally there should be options for handling the duplicates (renaming the accessions, removing the duplicate entry if the sequences are the same, ...).

Also nice to have: An option to add prefixes to the accessions to keep track of which file/database they came from.
