### ISSUE TITLE
Mass tags with delta masses are treated as unmodified residue

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1757]
Hi @hendrikweisser,
we are currently working on some cross-linking related code and found some unexpected string parsing. Maybe you can give some input why we currently treat delta mass tags as new, unmodified residues instead of a known residue with unknown modification.

take a look at following example output caused by the code in the first line and some associated tests we wrote:

```
AASequence seq19 = AASequence::fromString("PEPE[+999.9]TIDEK");

Warning: unknown modification '+999.9' of residue 'E' - adding it to the database
adding non-modified residue: +999.9
TEST_STRING_EQUAL(seq19.toUnmodifiedString(),"PEPETIDEK"): got "PEP TIDEK", expected "PEPETIDEK"
TEST_STRING_EQUAL(seq19.toString(),"PEPE[+999.9]TIDEK"): got "PEP[1146.9531592871]TIDEK", expected "PEPE[+999.9]TIDEK"
TEST_STRING_EQUAL(seq19[(Size)3].getModification(),""): got "", expected "true"
```

so basically we end up with a new residue called [+999.9], that is not modified and has single letter code ' '. This gets converted to [1146.9531592871] on calling toString() because it is unmodified and has ' ' as single letter code and no short name. 
We would expect a modified residue Glutamic Acid with delta mass 999.9 and single letter code 'E'

**Comment by hendrikweisser** [comment]
I agree that this behaviour is unexpected and suboptimal. However, looking at the code (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/AASequence.cpp#L912 and below), it seems to be handled the way it is very deliberately. It looks to me like a strange design decision rather than a clear-cut bug. (I'm pretty sure it was that way already before I refactored AASequence.)

The only reason I can imagine for why a new residue is added instead of a new mod. of an existing residue, is that the latter is not possible (or was, when the parsing code was written). Is it possible to add a new "anonymous" modification in OpenMS given only a delta mass? If yes, AASequence should be changed to behave like you said.

**Comment by timosachsenberg** [comment]
Ok perfect. Just wanted to be more certain there is no important reason we currently don't realize yet.
I think we could simply use the mass string as name ofr a new modification. That way it should also work with the other look-up code.
