### ISSUE TITLE
Silent install of OpenMS issues

### ISSUE THREAD

**Issue by grahampatterson** [OpenMS/OpenMS#1811]
Hi,

I'm an IT technician at Newcastle University. A academic has asked me to deploy OpenMS on a number of machines. I've attempted to do so using the below command although I get two prompts regarding .NET, please see attached. How do I tweak the instillation to prevent / pass switches to these prompts?

start /wait OpenMS-2.0_Win32_setup.exe /S

Any assistance would be greatly appreciated

Graham Patterson

![openms_prompt1](https://cloud.githubusercontent.com/assets/17168047/12962252/94dc6256-d03c-11e5-89a0-6a023b120105.png)
![openms_prompt2](https://cloud.githubusercontent.com/assets/17168047/12962253/94e6f5e0-d03c-11e5-8cae-08ee52b024d6.png)

**Comment by cbielow** [comment]
Hi Graham,

the two .Net installers get installed because Proteowizard is selected 
for installation 
(https://github.com/OpenMS/windows-installer/blob/master/OpenMS_installer.nsi#L328).

I think with the current setup and invokation from the command line, the 
installer cannot be silenced (unless you modify the installer code).
Maybe someone with a  ready-to-go OpenMS 2.0 build can help you to 
create one. The modifications are minimal.

I've opened a ticket 
(https://github.com/OpenMS/windows-installer/issues/3), which will 
adress the issue.
If someone knows how to invoke the installer from cmdline with 
installation type "2" by default, this would also solve your problem (it 
would simply skip proteowizard installation, and install it manually if 
needed).

Last alternative: there are scripting engines (e.g. 
https://www.autoitscript.com) out there which detect message boxes and 
send a keypress... nasty, but could work.

cheers
Chris


Am 2/10/2016 um 22:24 schrieb grahampatterson:
> > Hi, > > I'm an IT technician at Newcastle University. A academic has 
asked me > to deploy OpenMS on a number of machines. I've attempted to 
do so > using the below command although I get two prompts regarding 
.NET, > please see attached. How do I tweak the instillation to prevent 
/ > pass switches to these prompts? > > start /wait 
OpenMS-2.0_Win32_setup.exe /S > > Any assistance would be greatly 
appreciated > > Graham Patterson > > openms_prompt1 > 
<https://cloud.githubusercontent.com/assets/17168047/12962252/94dc6256-d03c-11e5-89a0-6a023b120105.png> 
 > >
openms_prompt2 
<https://cloud.githubusercontent.com/assets/17168047/12962253/94e6f5e0-d03c-11e5-8cae-08ee52b024d6.png>
> > — Reply to this email directly or view it on GitHub > 
<https://github.com/OpenMS/OpenMS/issues/1811>. >

**Comment by timosachsenberg** [comment]
I close this issue as this belongs to the windows-installer repository
