### ISSUE TITLE
Suboptimal ConsensusID performance when combining results from different search engine

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1823]
This workflow [1] combines MS-GF+ and X! Tandem (Piledriver) search results using the `PEPMatrix` and `PEPIons` algorithms of the `ConsensusID` tool based on four fractions of _Sciex TripleTOF 6600_ data.
Here the results after 5% FDR peptide level filtering:
- MS-GF+ only: **5,729** PSMs
- X! Tandem only: **3,190** PSMs
- MS-GF+ & X! Tandem (`PEPMatrix` algorithm): **4,071** PSMs
- MS-GF+ & X! Tandem (`PEPIons` algorithm): **4,100** PSMs

In the `ConsensusID` publication [2], the combined search results outperform the individual search results. In the test, Consensus ID identifies 28% PSMs less than MS-GF+ alone.

Is this expected or a bug?

[1] https://gist.github.com/lars20070/05a9c496796c0f095dcf
[2] http://pubs.acs.org/doi/pdf/10.1021/pr2002879

**Comment by hendrikweisser** [comment]
Have you configured both search engines so that they give multiple hits per spectrum (i.e. not just the best one)?

**Comment by lars20070** [comment]
No. - MS-GF+ has the `matches_per_spectrum` parameter. Is there an equivalent parameter in X! Tandem?

**Comment by hendrikweisser** [comment]
> Is there an equivalent parameter in X! Tandem?

I don't know. But ConsensusID with "PEPMatrix" or "PEPIons" doesn't make much sense unless you have multiple hits per spectrum.

**Comment by cbielow** [comment]
If ConsensusID only finds one hit per spectrum, it should report a warning, or even better: fail.
Otherwise a user might never realize that the input is not optimal.
We could also go for a flag "failOnSingleHit" (default: true), so the user has the option to run single-hit data -- but not by default.

**Comment by ypriverol** [comment]
@hendrikweisser @timosachsenberg @lars20070 what the users expect with ConsensusID is to have more PSMs because it will be a huge impact on Identifications, Quantitation, etc . Any turning parameter in OpenMS should respond to that. ConsensusID is one of the examples that should not run if the previous nodes are not configure properly. In terms of usability, ConsensusID should be (by default) configure to get as mush as possible from the data and should provide an easy way to do it. 
It is difficult to use something that basically you need to perform benchmarks to realice if is working well, specially if you expect that the get more out of the data. Agree with @cbielow proposal about the ConsensusID .. it should fail if the corresponding nodes are configure in a wrong way.

**Comment by lars20070** [comment]
+1 @cbielow and @ypriverol 

X! Tandem reports per default only a single peptide hit. I cannot find a search engine parameter to change that. @naepfel How was this done in the paper [2]?

[2] http://pubs.acs.org/doi/pdf/10.1021/pr2002879

**Comment by hendrikweisser** [comment]
> If ConsensusID only finds one hit per spectrum, it should report a warning, or even better: fail.

It's not quite so clear-cut. First, this only applies to the "PEP..." algorithms. They work when they get similar sequences from different sources. If your search engines only report the best hit, but you use many search engines, it might also work.

But I agree that at least a warning should be given if a "PEP..." algorithm is selected and there are only best hits.

**Comment by lars20070** [comment]
Updated results with 10 peptide hits per spectrum from MS-GF+ and one peptide hit per spectrum (by default) from X! Tandem.
- MS-GF+ only: **5,729** PSMs
- X! Tandem only: **3,190** PSMs
- MS-GF+ & X! Tandem (`PEPMatrix` algorithm): **5,361** PSMs
- MS-GF+ & X! Tandem (`PEPIons` algorithm): **6,203** PSMs

IMO, a consensus ID workflow should never report worse results (5,361 < 5,729) but automatically default to the single best search engine result.

**Comment by hendrikweisser** [comment]
> IMO, a consensus ID workflow should never report worse results (5,361 < 5,729) but automatically default to the single best search engine result.

The workflow can't do that without running an FDR analysis.

**Comment by timosachsenberg** [comment]
seems resolved to me, I will close it. If you need specific improvements like warnings etc. please open a different issue

**Comment by lars20070** [comment]
FYI, on 28/02/17 I emailed Ron Beavis regarding multiple hits (i.e. not just the best) in the X!Tandem output. So far I had no reply.
