### ISSUE TITLE
Decharger tool, used solver lib

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/OpenMS#1985]
Hi, as far as I can see, the solver used for Decharging uses glpk. Does anyone have experience how much effort it would be to switch to coinor/coin-mp? Reasons:
- A collegue told me that glpk was slow compared to the coinor cbc :D
- For Windows, I want to use the Decharger tool for a community node in Thermo Fisher Compound Discoverer. It would be nice to be able to say that all the stuff people install is under BSD 3-clause

Concerning the current status I found https://github.com/OpenMS/contrib/issues/9
Is that still the current state or were there further discussions I am not aware of? As far as I can see, we currently do not ship coinor/coin-mp with Windows OpenMS, is that correct?

Thanks

**Comment by cbielow** [comment]
1) your colleage is right, CoinMP is (a lot) faster than GLPK and we should kick GLPK -- if you are at it anyways, any volunteers? :)

2) (citing myself, dont quote me on it though) COIN-MP is EPL [1], which is compatible with BSD [2]

3) We have a an LPWrapper[3], which makes switching between GLPK and COINOR a nobrainer
It should be possible to use COINOR by just switching it on in the build system, i.e. -DUSE_COINOR=ON, see src/openms/cmake_findExternalLibs.cmake:if (${USE_COINOR})
Shipping for the Windows installer should not be required, since the libs are statically linked (there's libClp.lib, libOsi.lib, etc... in the contrib/lib directory)

[1] https://projects.coin-or.org/CoinMP/browser/releases/1.8.0/CoinMP/LICENSE
[2] https://eclipse.org/legal/eplfaq.php#COMPILEWOMOD
[3] http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/classOpenMS_1_1LPWrapper.html

**Comment by timosachsenberg** [comment]
When I use CoinOR I get an error in LPWrapper_test.
Anyone can confirm this?
```
50: checking (void readProblem(String filename, String format)) ...
50:  +  line 311:  TEST_EXCEPTION(Exception::NotImplemented,lp.readProblem("/bla/bluff/blblb/sdfhsdjf/test.txt","LP")): OK
50: : passed
50:
50: checking (void writeProblem(const String &filename, const WriteFormat format) const ) ...
50:  -  line 346:  TEST_EXCEPTION(Exception::NotImplemented,lp.writeProblem("/bla/bluff/blblb/sdfhsdjf/test.txt",LPWrapper::FORMAT_LP)): wrong exception thrown!  "Exception"
50: : failed
50:
50: checking (Int solve(SolverParam &solver_param, const Size verbose_level=0)) ... Coin0001I At line 1 NAME          LPWrapper_test.lp
50: Coin0001I At line 2 ROWS
50: Coin0001I At line 7 COLUMNS
50: Coin0001I At line 15 RHS
50: Coin0001I At line 18 BOUNDS
50: Coin0001I At line 21 ENDATA
50: Coin0002I Problem LPWrapper_test.lp has 3 rows, 2 columns and 6 elements
50:
50:  +  line 359:  TEST_EQUAL(lp2.getColumnValue(0),1): got 1, expected 1
50:  +  line 360:  TEST_EQUAL(lp2.getColumnValue(1),1): got 1, expected 1
50: Coin0001I At line 1 NAME          LPWrapper_test.lp
50: Coin0001I At line 2 ROWS
50: Coin0001I At line 7 COLUMNS
50: Coin0001I At line 17 RHS
50: Coin0001I At line 20 BOUNDS
50: Coin3002W Bad image at line 23 <  UI BOUND       y       5 >
50: Coin3002W Bad image at line 24 <  UI BOUND       x       5 >
50: Coin0001I At line 25 ENDATA
50: Coin0002I Problem LPWrapper_test.lp has 3 rows, 2 columns and 6 elements
50: LPWrapper_test: OsiClpSolverInterface.cpp:2782: virtual int OsiClpSolverInterface::loadFromCoinModel(CoinModel&, bool): Assertion `integerType' failed.
1/1 Test #50: LPWrapper_test ...................***Exception: Other  0.06 sec

0% tests passed, 1 tests failed out of 1
```

**Comment by FabianAicheler** [comment]
I also get that test error, but will have to read up what the test does.
