### ISSUE TITLE
PeptideIndexer problems with ambiguous amino acids

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#1989]
I'm seeing some strange behaviour of PeptideIndexer with regards to ambiguous amino acids. As an example, the following peptide wasn't matched to its protein, despite having "aaa_max" at the default value of 4 (without "full_tolerant_search"):
- peptide: GTVAAPSVFLFPPSDEQLK
- protein: XTVAAPSVFLFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC

It should match right at the beginning.

I then played around with the test cases, and weird things happen in "TOPP_PeptideIndexer_7", "TOPP_PeptideIndexer_8" and "TOPP_PeptideIndexer_9" when I introduce an "X" into the sequence of a target protein in the FASTA file ("PeptideIndexer_1.fasta"), e.g.:
```
>tryptic_cleavage_test_protein1
MBCDEFGKXBCRAAAKAARPBBBB
```
(changed "A" to "X").

In the tests, PeptideIndexer aborts with "no decoy matches", because the unrelated decoy peptide "DFIANGER" isn't matched to its decoy protein any more!

I would appreciate if someone could help me investigate this, as I'm supposed to finish a paper now, but the results in it depend on the correctness of PeptideIndexer.
@enetz, I've noticed that the class test for the PeptideIndexing class is still missing. Could you maybe add one and check some of these cases in it?

**Comment by enetz** [comment]
The description of the parameter "full_tolerant_search" says "If set, all peptide sequences are matched using tolerant search. ...".
The description for "aaa_max" says "[tolerant search only] Maximal number of ambiguous amino acids (AAAs) ..."
So as I understand it, if "full_tolerant_search" is not set, then "aaa_max" is not applied (or treated as 0).
Since the default value for "mismatches_max" is 0, I think what you want (matching up to 4 AAAs without real mismatches) is supposed to work by setting "full_tolerant_search" to true.

**Comment by hendrikweisser** [comment]
> So as I understand it, if "full_tolerant_search" is not set, then "aaa_max" is not applied (or treated as 0).

I don't think that's correct. Rather, the documentation is misleading.
By default (i.e. without "full_tolerant_search"), PeptideIndexer will do an exact search first, followed by an error-tolerant search only for peptides that could not be matched using the exact search. In this second pass, "aaa_max" should take effect.

**Comment by cbielow** [comment]
@hendrikweisser: your assumption is correct :)


Regarging the problem:
I think I've tracked it down to a problem with translating matched peptide/protein indexes in the object which holds the actual mapping of peptides to proteins.
When using  `-full_tolerant_search` for TOPP_PeptideIndexer_7 with the modified FASTA db, the test runs through. The console output is also identical when switching between the two FASTA versions (as long as full_tolerant_search is used).
Since the protein indices are corrected for when using a smaller protein DB, I think it should be the peptide hits which get mixed up.

**Comment by cbielow** [comment]
after some more digging, the bug is fixed (PR here #1996).

**Comment by cbielow** [comment]
closing this, since #1996 should resolve the problem.
Please confirm and reopen if necessary.

**Comment by hendrikweisser** [comment]
@cbielow, thanks a lot for finding and fixing the problem!
