### ISSUE TITLE
MSGFPlusAdapter doesn't work for compressed inputs (mzML.gz)

### ISSUE THREAD

**Issue by hendrikweisser** [OpenMS/OpenMS#2074]
TOPP tools can generally accept gzip-compressed variants of their input files, e.g. mzML.gz instead of mzML (not sure if it works for all formats). Such files are decompressed when they are read in by OpenMS. However, in the MSGFPlusAdapter, the path is just passed on to the MS-GF+ Java call, and MS-GF+ can't read gzipped input. The problem is that this isn't caught by the input parameter checks (OpenMS thinks mzML.gz is fine for an mzML input file).

In the MSGFPlusAdapter, a compressed input file needs to be decompressed explicitly into a temporary file, which can then be used with MS-GF+.

**Comment by timosachsenberg** [comment]
I know this might be controversial but I think in general we should discourage the use of compressed files in the inner processing parts of an OpenMS pipeline. The reason is, that this greatly complicates many aspects like the direct visualization of indexed files and compatibility with downstream tools. I would prefer a solution that uses the e.g. FileConverter to convert compressed mzML to indexed uncompressed mzML. All other tools should, in general, only accept indexed mzML. This would also simplify tracing of spectral references etc. for writing proper mzIdenML /mzTab files.

**Comment by hendrikweisser** [comment]
I don't get the connection between indexed mzML and spectral references. Isn't the problem there that we don't keep the appropriate reference in the idXML?

In any case, I think supporting compressed files directly is convenient. There's nothing stopping you from creating an indexed mzML if you need the benefits of that.

**Comment by timosachsenberg** [comment]
My comment is mostly about keeping complexity and maintenance efforts to a minimum while maintaining compatibility with other tools. As you realized problems are showing up when we directly forward files to wrapped third-party tools. Same holds for the growing number of KNIME plugins from other sources that support (albeit rarely to the extent we do) PSI standards. Convenience comes with a price and it might be worth to think about finding a common ground with these tools. This may mean we could be less promiscuous in what we accept as input / output files. Just my two cents...

**Comment by hendrikweisser** [comment]
Okay, I get it. Fair point.
