### ISSUE TITLE
Update XTandem for OpenMS 2.1

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2093]

**Comment by timosachsenberg** [comment]
Latest release:   VENGEANCE (2015.12.15)

**Comment by timosachsenberg** [comment]
I think #2057 is not related to this but it might be worth to check if this problem persists on the newer version.

**Comment by timosachsenberg** [comment]
updated in OpenMS/THIRDPARTY
might require testing of 32/64bit on linux

**Comment by mwalzer** [comment]
Did you do some testing already? Otherwise, I'll have a look into that.

**Comment by timosachsenberg** [comment]
only if "it runs"

**Comment by Stefan-N** [comment]
[https://github.com/OpenMS/OpenMS/issues/2057](url) seems to be fixed in this version.
i just tried it with two files, one of them uploaded here [1]. Still get multiple hits for some spectra that look identical at the first sight [2]
But taking a detailed look you can see that they have different **"protein_refs=**" This is occurs when a peptide sequence is not unique and is imo the correct behaviour.

[1]https://gist.github.com/Stefan-N/993a02da4b625385938c9605e32ec7f0
[2]https://gist.github.com/Stefan-N/8b5c9d30f6bd14099ddce7dee143d370

**Comment by hendrikweisser** [comment]
> But taking a detailed look you can see that they have different "protein_refs=" This occurs when a peptide sequence is not unique in the provided fasta file and is imo the correct behaviour.

No, in OpenMS we would like to get one peptide hit with references to multiple proteins in this case.
