### ISSUE TITLE
Update docu on installing the PyOpenMS distribution

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2181]
What is the current recommended way to get pyopenms for production use (e.g. for the tutorial).
It seemed to me on my MacOS that pyopenms 2.0 is not available via easy_install (latest is 1.11) but only via pip. Is that correct or did I do something wrong?
Is it recommended now to use pip? The documentation on https://pypi.python.org/pypi/pyopenms and  seems to propose easy_install for Linux and pip for other platforms. Our doxygen docu only mentions easy_install for production use.

**Comment by uweschmitt** [comment]
The documentation on pypi is correct. It was changed since we new build wheel files for Mac OS and Windows (which pip can install), but not yet for Linux (this is in development: https://github.com/pypa/manylinux). pip on Linux would try to build pyopenms from scratch, easy_install can install binary packages.

**Comment by jpfeuffer** [comment]
Okay great. Then let's not forget to update the pyOpenMS docu for the release.

**Comment by jpfeuffer** [comment]
Maybe we should link to the pypi page for the binary installation procedure if this is a reference that will be kept uptodate?

**Comment by jpfeuffer** [comment]
Okay. From now on we link to the install instructions on PyPI. Closed.
