### ISSUE TITLE
[UserMeeting] OpenSwathChromatogramExtractor usage

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2185]
We had a question during our 2016 user meeting concerning OpenSwathChromatogramExtractor:
- How does it handle multiple input mzMLs?
- In which case would you input a list of files to it? In the tutorial for example it takes a list of mzML files and we were wondering what these files represent.

Maybe one of the SWATH experts could help us out there.

**Comment by grosenberger** [comment]
The OpenSwathChromatogramExtractor expects a single mzML to contain spectra belonging to the same precursor isolation window width. So if you have DIA data that was acquired with 32 windows of 25 Da each, you would use all 32 files as input to extract the ion chromatograms. These individual files can be generated using: https://github.com/msproteomicstools/msproteomicstools/blob/master/analysis/data_conversion/split_mzXML_intoSwath.py

Since OpenMS 2.0, there is a new tool called OpenSwathWorkflow. It integrates all steps, including OpenSwathChromatogramExtractor, OpenSwathRTNormalizer, OpenSwathAnalyzer & OpenSwathFeatureXMLToTSV in a single executable and is much faster and requires less resources. Also, it expects the 32 files to be from a single mzML, as can be converted since recently with ProteoWizard.

**Comment by jpfeuffer** [comment]
Thanks a lot, that explains everything for now. We will look into either upgrading the Tutorial or describe it in more detail.

**Comment by grosenberger** [comment]
@hroest recently wrote a very comprehensive tutorial that is already available on bioRxiv and that might be a better starting point than the one that is currently included as part of the OpenMS tutorials: http://biorxiv.org/content/early/2016/03/19/044552.full.pdf+html

**Comment by hroest** [comment]
yes, I really suggest to also include links to the tutorial as it is quite comprehensive and goes through every step really carefully...

**Comment by hendrikweisser** [comment]
Questions have been answered.
