### ISSUE TITLE
Unrecognized modifications in SpecLibSearcher

### ISSUE THREAD

**Issue by DinosaurInSpace** [OpenMS/OpenMS#2353]
Hi:

I am an analytical chemist with extensive experience in the experimental (wet-lab) portion of mass spectrometry workflows.  I have some experience with bioinformatics, for example I know some Python and can frequently get command line bioinformatics packages to run, but am not an expert in this area.

Recently I have been looking at some of the OpenSource pipelines (e.g. Skyline, OpenMS (Knime), TPP) as alternatives to vendor software for various issues in data analysis and wanted to share some user feedback.  I am attracted to your solution in particular due to the easy automation and workflow analysis with Knime.  I have had previous experience with Knime for cheminformatics processing.  I have previously had success with the Topas implementation of OpenMS.

The main issue I have found is that the 3/4 MS2 peptide search algorithm adapters I have investigated in the default OpenMS installation do not appear to work "out of the box":

MSGFPlusAdapter: Works!

SpecLibSearcher: Fails due to mismatch between modification in .msp spectral database "C,Carbamidomethyl", which is not identified as the same as  "Carbamidomethyl (C)" in the adapter.

OMSSA: .fasta.phr, .fasta.pin, and .fasta.psq not generated in workflow.

X!tandem: No default configuration template file available.

Any advice would be greatly appreciated!  Ideally it would be great to have the adaptors work "out of the box" or at least have solutions documented.  

Thanks!

-Chris

**Comment by jpfeuffer** [comment]
Hi!

I will start to give you suggestions for some of the problems:

> OMSSA: .fasta.phr, .fasta.pin, and .fasta.psq not generated in workflow
This is intended. As the tool [documentation](http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_OMSSAAdapter.html) states, these index files need to be generated with the NCBI `makeblastdb` tool first and put in the same folder as the original fasta database.

> X!tandem: No default configuration template file available.
Which version of KNIME and OpenMS are you using. We had problems with this in earlier versions of our OpenMS plugin.

The SpecLibSearcher problem needs some more investigation since I do not have much experience with it myself. But for other developers it might be worth knowing where you got the library from / how it was generated.

Cheers,
Julianus

**Comment by DinosaurInSpace** [comment]
Wow thanks for the prompt response!

1. My apologies re:OMSSA.  That seemed to do the trick.

2. I am running KNIME 3.3.1 downloaded with all community plugins with OpenMS 2.1.0.201611191105.

3. For SpecLibSearcher I am using the NIST standard library for E. coli (http://chemdata.nist.gov/dokuwiki/doku.php?id=peptidew:lib:e_coli).  This library works in Spectrast.  My thought is that although the same modification is noted in both the spectral database and adapter, the software isn't recognizing them as synonymous.  

Thanks again!

-Chris

**Comment by jpfeuffer** [comment]
Concerning 2.:
That is indeed the most current version. I can not reproduce the problem on Mac (btw: can you specify your operating system?). And could you post the error log for XTandem in the KNIME Console? If you do not find it you can access the error log also when you right-click the XTandemAdapter node and select View: XTandemAdapter Error Output.

**Comment by DinosaurInSpace** [comment]
Hey:

Thanks again for your prompt response!

I am running Windows 7 Professional.  I actually just uninstalled then reinstalled the Knime and Open MS environment.  This seems to have resolved the issue for X!Tandem!

This does not resolve the error for SpecLibSearcher:

ERROR SpecLibSearcher      2:11       Failing process stdout: [Error: Unexpected internal error (The value 'Carbamidomethyl' was used but is not valid! Retrieving the modification failed. It is not available for the residue '' and term specificity 1.)]
ERROR SpecLibSearcher      2:11       Failing process stderr: []
ERROR SpecLibSearcher      2:11       Execute failed: Failed to execute node SpecLibSearcher

![image](https://cloud.githubusercontent.com/assets/25156645/21996516/79df071a-dbdf-11e6-9d17-cd195f151fb8.png)

**Comment by jpfeuffer** [comment]
Since the other problems were solved with a reinstall, I renamed it to the last, probably real issue.

Yes, there is a mismatch between the representation in the MSP file and the unimod representation but we seem to have a special parser that should take care of this translation:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/MSPFile.cpp

We would need to investigate further, however there is currently an effort to reactivate the SpectraST Adapter, which might be a great alternative (https://github.com/OpenMS/OpenMS/pull/2359)

**Comment by DinosaurInSpace** [comment]
Thanks again for your help!

Further question: it looks like the MSPFile.cpp is a c++ program that I will need to compile?  Can you provide any advice in this process.  I have experience with interpreted languages such as Python but have never touched C++ before.

Having Spectrast implemented in Knime OpenMS would be terrrific!

**Comment by jpfeuffer** [comment]
Hey,
I would say the solution for now is to try the new SpectraST adapter (SpectraSTSearch) in the nightly build. We will decide on how to proceed with the very old SpecLibSearcher (deprecation, fix or removal).
Please reopen the issue if you have more questions.

**Comment by hroest** [comment]
@jpfeuffer finding a solution for the old speclib searcher would be great as it was also a big pain for #2477 due to it using `MSExperiment<RichPeak1D>` as one of the few (only?) tools.
