### ISSUE TITLE
Error validating idXML file against XML schema

### ISSUE THREAD

**Issue by SharmeelaAshwin** [OpenMS/OpenMS#2366]
On running the "`fileinfo -v -in CC271.idXML`" on CC271.idXML file  below pasted errors are displayed

```
-- General information --

File name: CC271.idXML
File type: idXML

Validating idXML file against XML schema version 1.4
Validation error in file 'CC271.idXML' line 33 column 207: value 'controllerType
=0 controllerNumber=1 scan=26981' does not match regular expression facet '[+\-]
?[0-9]+'
Validation error in file 'CC271.idXML' line 64 column 207: value 'controllerType
=0 controllerNumber=1 scan=6989' does not match regular expression facet '[+\-]?
[0-9]+'
Validation error in file 'CC271.idXML' line 95 column 207: value 'controllerType
=0 controllerNumber=1 scan=17644' does not match regular expression facet '[+\-]
?[0-9]+'
Validation error in file 'CC271.idXML' line 126 column 208: value 'controllerTyp
e=0 controllerNumber=1 scan=22967' does not match regular expression facet '[+\-
]?[0-9]+'
Validation error in file 'CC271.idXML' line 157 column 207: value 'controllerTyp
e=0 controllerNumber=1 scan=13794' does not match regular expression facet '[+\-
]?[0-9]+'
Validation error in file 'CC271.idXML' line 188 column 208: value 'controllerTyp
e=0 controllerNumber=1 scan=24365' does not match regular expression facet '[+\-
]?[0-9]+'
Validation error in file 'CC271.idXML' line 219 column 208: value 'controllerTyp
e=0 controllerNumber=1 scan=17680' does not match regular expression facet '[+\-
]?[0-9]+'
Validation error in file 'CC271.idXML' line 250 column 207: value 'controllerTyp
e=0 controllerNumber=1 scan=29897' does not match regular expression facet '[+\-
]?[0-9]+'
Failed - errors are listed above!
FileInfo took 0.06 s (wall), 0.02 s (CPU), 0.00 s (system), 0.02 s (user).
```

Please find the link to the uploaded file CC271.idXML here : https://gist.github.com/SharmeelaAshwin/df58e22565c442ea29a495db3274a6fd

**Comment by jpfeuffer** [comment]
Hi!

Where does the idXML come from? From conversion with IDFileConverter?
If so, please check the documentation and consider setting the scan_regex option of the tool.
http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_IDFileConverter.html

**Comment by SharmeelaAshwin** [comment]
Hi,

The idXML file was not created using IDFileConverter. It was created using OpenMS workflow.
The Toppas file is being attached here for the workflow: 
https://gist.github.com/SharmeelaAshwin/8005ccaed9bdedeb77106370889ceed1
and the 20th output node of the workflow generated the CC271.idXML file.

**Comment by jpfeuffer** [comment]
@mwalzer What is the status on IDs? Do we want to store native spectrum IDs?
I think we need a schema update then, right?
https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/SCHEMAS/IdXML_1_4.xsd#L252

Additionally, can we point to the schema in git instead of the old sourceforge and where would I have to change that?

**Comment by mwalzer** [comment]
We definitively do not want to discard the native spectrum ids. Esp. because we need that for mzid and the like and if we expect people to be able to submit their results later on. This is why idXML was called internal development format (dunno by whom). Though our internal object representation also deviated somewhat from the idXML schema in any case. 
It does not make much sense to me putting much effort in an old format. That fix, however, is done quickly.

**Comment by hroest** [comment]
@timosachsenberg @mwalzer is this fixed?
