### ISSUE TITLE
additional MS2 filtering / quality metrics

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2412]
this issue is intended to collect some useful links on complementary fragment filtering from the eupa-bioinformatics mailing list:

https://www.ncbi.nlm.nih.gov/pubmed/23725413
https://www.ncbi.nlm.nih.gov/pubmed/25978296
https://www.ncbi.nlm.nih.gov/pubmed/27329701

We mostly presented this as a way to go deeper in the proteome, but it, certainly, can be used as a quality filter as well.

Additionally, I can think of something similar to DIAUmpire https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4399776/, that can also be used to identify fragments behaving similarly and, thus, fishing out relevant informaton.

**Comment by hroest** [comment]
this is also especially useful for DIA / SWATH-MS type of experiments as they are multiplexed by design. Taking the elution profiles into account would be going more down the route of DIA-Umpire where maybe an adaptor is the better solution 

@grosenberger are there any plans to build such an adaptor in OpenMS? maybe Isa could comment (whats her github account?)

**Comment by mwalzer** [comment]
Could we get access to the fragments group data from DIA-umpire? That would be really interesting.

**Comment by grosenberger** [comment]
An adaptor would definitely be nice and I think wrapping the main component of DIA-Umpire should be feasible, similarly to the LuciPHOr 2 adapter (Java, ini-based parameterisation). As far as I know, there no plans at the moment, but there is work ongoing by @isabell-bludau and colleagues to improve the compatibility with OpenMS/OpenSWATH.
