### ISSUE TITLE
review FileConverter

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2466]
make advanced:
- in_type
- UID_postprocessing <method>
- out_type
- lossy_compression
- lossy_mass_accuracy

rethink default:
- write_mzML_index is currently no index

```
Options (mandatory options marked with '*'):
  -in <file>*                   Input file to convert. (valid formats: 'mzData', 'mzXML', 'mzML', 'cachedMzML', 'dta', 'dta2d', 'mgf', 'featureXML', 'consensusXML', 'ms2', 'fid', 'tsv',
                                'peplist', 'kroenik', 'edta')
  -in_type <type>               Input file type -- default: determined from file extension or content
                                (valid: 'mzData', 'mzXML', 'mzML', 'cachedMzML', 'dta', 'dta2d', 'mgf', 'featureXML', 'consensusXML', 'ms2', 'fid', 'tsv', 'peplist', 'kroenik', 'edta'
                                )
  -UID_postprocessing <method>  Unique ID post-processing for output data.
                                'none' keeps current IDs even if invalid.
                                'ensure' keeps current IDs but reassigns invalid ones.
                                'reassign' assigns new unique IDs. (default: 'ensure' valid: 'none', 'ensure', 'reassign')
  -out <file>*                  Output file (valid formats: 'mzData', 'mzXML', 'mzML', 'cachedMzML', 'dta2d', 'mgf', 'featureXML', 'consensusXML', 'edta', 'csv')
  -out_type <type>              Output file type -- default: determined from file extension or content
                                Note: that not all conversion paths work or make sense. (valid: 'mzData', 'mzXML', 'mzML', 'cachedMzML', 'dta2d', 'mgf', 'featureXML', 'consensusXML', '
                                edta', 'csv')
  -write_mzML_index             Add an index to the file when writing mzML files (default: no index)
  -lossy_compression            Use numpress compression to achieve optimally small file size (attention: may cause small loss of precision; only for mzML data)
  -lossy_mass_accuracy <error>  Desired (absolute) m/z accuracy for lossy compression (e.g. use 0.0001 for a mass accuracy of 0.2 ppm at 500 m/z, default uses -1.0 for maximal accuracy)
                                (default: '-1')
```

**Comment by hroest** [comment]
the issue  with the index is that the flag is a true flag instead of what we should have done `write_mzML_index true/false`

so its hard to change that but I suggest to  basically switch to a new parameter that has true/false
- `write_indexedMzML true/false` which is now true by default
- keep `write_mzML_index` as as flag for backwards compat but it basically doesnt do anything since the index gets written whether the flag is set or not (we can throw an exception in case the first flag requires no index and the second flag is set)

**Comment by cbielow** [comment]
concerning the 'out_type' we should discuss how its required in different workflow engines. In TOPPAS you need it, thus it would be bad to make it advanced. Not sure about other implementations.

Regarding deprecation of flags/parameters: I strongly vote for just making the change without backwards compatibility (which is not provided here anyway), since:
 1) it complicates the code,
 2) will lead to invalid param files anyway once we remove the deprecated flag (i.e. there is 0 benefit for the user, except more confusion)

About the default of 'true', please consider https://github.com/OpenMS/OpenMS/issues/2350.

**Comment by hendrikweisser** [comment]
I agree with Chris - just fix the problematic flag once and for all. Make it e.g. "omit_index" with a default of false.

**Comment by timosachsenberg** [comment]
adressed in https://github.com/OpenMS/OpenMS/pull/2521
