### ISSUE TITLE
Pubchem support for AccurateMassSearch

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2555]
In the process of the KNIME integration of MetFrag, it would be nice to be able to search
PubChem in AccurateMassSearch to filter candidates for MetFrag.
We discussed possible implementations:
- REST API, not so complex but limited amount of calls before DDOS blocking
- PostgreSQL, existing 300GB Docker container in Halle but additional dependency?
- SQLite, we would need to create such a DB, no new dependencies, size?, performance?

**Comment by hroest** [comment]
We already have a SQLite dependency in OpenMS since a few weeks, so that may be a good solution. I dont see how that could be slower than something over the web, e.g. a rest api so I dont see a performance downside. It seems like they offer SDF and XML ftp://ftp.ncbi.nih.gov/pubchem/Compound/CURRENT-Full/

**Comment by jpfeuffer** [comment]
I have a workflow for creating and updating such a database. We could proceed at some point. Need a chat with the Halle guys.
@sneumann @oliveralka

**Comment by sneumann** [comment]
@meier-rene and @c-ruttkie can comment here. MetFrag has connectivity to postgres so far, 
we can either add sqlite support to MetFrag, and need to make sure the table schema 
looks like what we expect, of have a small call to sqlite CLI to extract a CSV with SMILES 
as candidate list. Yours, Steffen
