### ISSUE TITLE
Filetypes: support of chromatograms (regarding: #2660)

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/OpenMS#2661]
Another question in regard to #2660 would be if the chromatograms should be independent of the featureXML (FeatureFinderMetabo) and consensusXML (Decharger, FeatureLinkerUnlabeledQT). Right now the chromatograms are processed as optional output of the FeatureFinderMetabo (one mzML for each sample). To process them in the end together with the data of all samples there are several options available:

1. Merge/Append the mzML into big mzML file with all the samples and use it as input for a new tool, which does the chromatogram correlation.
2. Write the chromatogram data into the featureXML and drag it along all the way. This consensusXML can then be used as tool input. 

Any ideas/suggestions which would be more applicable in the long run also in regard to visualisation of the overlay of chromatograms of different features at the same rt, which may belong to the same metabolite.

**Comment by timosachsenberg** [comment]
probably better to store them in mzml. other files might get huge

**Comment by timosachsenberg** [comment]
I guess we could add a meta value that contains the chromatogram id as value in the featureXML / consensusXML. This could reference the id in the mzML file.

**Comment by hroest** [comment]
since these chromatograms are "auxiliary files" that are only used within OpenMS, we could also use the sqmass format that I recently wrote. It is substantially smaller than mzML and does not require us to load the whole file into memory. This means we can use SQL queries to get individual chromatograms.

But yes, mzML is also a good idea and worked well for us in the swath world even though they become unwieldly when you have many of them since the files tend to get really large.

> I guess we could add a meta value that contains the chromatogram id as value in the featureXML / consensusXML. This could reference the id in the mzML file.

why not make the id in the featureXML the same as the mzML  ? that would make things easier ... :-)

**Comment by timosachsenberg** [comment]
the feature ID match the mzML ID? don't know if this is a good idea as feature IDs get reassigned by some tools.

**Comment by hroest** [comment]
> as feature IDs get reassigned by some tools.

maybe that is not a good idea? shouldnt these ids be static and relate to a specific unchanging entity. But yes, we could also solve this with a meta value
