### ISSUE TITLE
Unicode handling in OpenMS is inconsistent and error-prone

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2701]
```
src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(110): While loading 'error2.idXML': invalid byte 'p' at position 2 of a 3-byte sequence( in line 1 column 39)
```
link to minimal example:

**Comment by timosachsenberg** [comment]
```
0000120: 3c53 6561 7263 6850 6172 616d 6574 6572  <SearchParameter
0000130: 7320 6964 3d22 5350 5f30 2220 6462 3d22  s id="SP_0" db="
0000140: 463a 5c53 6368 e470 655c 3137 3035 3131  F:\Sch.pe\170511
0000150: 5f45 7363 6865 7269 6368 6961 2063 6f6c  _Escherichia col
0000160: 695f 7374 7261 696e 204b 3132 5f4c 6163  i_strain K12_Lac
```

**Comment by timosachsenberg** [comment]
the culprit is e4 (byte 146 displayed as '.') which is two bytes in UTF-8
```
U+00E4	ä	195 164	LATIN SMALL LETTER A WITH DIAERESIS
```

**Comment by timosachsenberg** [comment]
[error.zip](https://github.com/OpenMS/OpenMS/files/1073917/error.zip)

**Comment by timosachsenberg** [comment]
@mwalzer @cbielow what would be the best way to fix this? use Qt to convert the db name to UTF-8?

**Comment by timosachsenberg** [comment]
we currently handle the db string with:
```
    << "db=\"" << writeXMLEscape(params[i].db) << "\" "
```
but only:
```
      static String writeXMLEscape(const String& to_escape)
      {
        String _copy = to_escape;
        // has() is cheap, so check before calling substitute(), since substitute() will usually happen rarely
        if (_copy.has('&')) _copy.substitute("&","&amp;");
        if (_copy.has('>')) _copy.substitute(">","&gt;");
        if (_copy.has('"')) _copy.substitute("\"","&quot;");
        if (_copy.has('<')) _copy.substitute("<","&lt;");
        if (_copy.has('\'')) _copy.substitute("'","&apos;");

        return _copy;
      }
```
are escaped.
Just add escaping here?

**Comment by timosachsenberg** [comment]
```
Ä      &#196;
Ö      &#214;
Ü      &#220;
ä      &#228
ö      &#246;
ü      &#252;
ß      &#223;
``

**Comment by hroest** [comment]
@timosachsenberg we need to distinguish between escaping and UTF8 issues. We escape things that are not valid if they occur in a name or attribute inside the XML and writing them would lead to invalid XML itself. In principle, an XML that contains UTF8 is perfectly valid ... maybe here we are more dealing with the fact that C++ and OpenMS  are not UTF8 aware? 

So the question is rather why "ä" was not written as 00E4 but instead as "E4" which is invalid ASCII and invalid UTF8 ... if it was read correctly from an XML file, it should have been in proper UTF16 (xerces) and then UTF8 (C-string) and when writing to disk it should have been 00E4, right? How was that idXML file generated?

Escaping a few german umlauts will never cover all of UTF8, I think we need a more general solution here - but maybe its a start?

**Comment by hroest** [comment]
ok, now I am a bit confused because E4 is the unicode code point whereas the hex description should be `c3a4` (see http://www.utf8-chartable.de/ and https://en.wikipedia.org/wiki/UTF-8) and it seems only the unicode code points below U+0080 are direct representations to bytes whereas other code points are split to two bytes. So there should never be a unicode code point memory - or written to disk -  above 0080 - see https://en.wikipedia.org/wiki/UTF-8#Description

so really the question is how was this file generated? how was the input "F:\Schäpe\..." read into OpenMS? through xerces?

**Comment by timosachsenberg** [comment]
"it seems only the unicode code points below U+0080 are direct representations to bytes whereas other code points are split to two bytes. So there should never be a unicode code point memory - or written to disk - above 0080 -"
That's how I understand it, too. I think  E4 is valid extended ASCII for ä under ISO 8859-1  (also ISO Latin-1. So I guess the ASCII string might be written directly in the XML file without proper encoding as multi-byte UTF-8

**Comment by timosachsenberg** [comment]
One way around this would be to just escape it using the table I posted above (Escaping these, I though, is mandatory in XML but I might be wrong)

**Comment by hroest** [comment]
hmm ok, I see

but I am not sure that you are correct, because then it seems what happened was that we wrote ISO 8859 into a file that was supposed to be unicode. So the correct solution is *not* to use XML encoding but to use the proper UTF8 encoding. How would you even test for this in C++? You would have to test every character against different, possibly multi-byte encodings to check whether it represents "ä" under any of these encodings and then replace it with `&#228;` -- I dont think that is feasible or desireable. The correct way to deal with this is to keep all data in C strings in Unicode to begin with -- so the question is why we have a file that claims to be unicode but actually is ISO 8859. Our XML says `<?xml version="1.0" encoding="UTF-8"?>` so it should never have been ISO 8859 in memory. Again, can you explain how the file was generated exactly? I think the error is not *writing* the file but *reading* the input which should have been converted to UTF8 and not to ISO 8859 in memory. 

We never discussed this but the implicit assumption I had was that all C-strings in OpenMS are either  ASCII or UTF8 but never ISO 8895, correct?

**Comment by hroest** [comment]
> So I guess the ASCII string might be written directly in the XML file without proper encoding as multi-byte UTF-8

again, I think the error happened earlier when the string was generated - it should have been properly encoded when *reading* already!

**Comment by hroest** [comment]
> One way around this would be to just escape it using the table I posted above (Escaping these, I though, is mandatory in XML but I might be wrong)

https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents

```
XML escape characters

There are only five:

"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;
```

I think you were thinking about HTML escape characters which are different from XML, see also here https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references so I am not sure whether using any other than the 5 is even valid XML ?

**Comment by timosachsenberg** [comment]
I see. Yeah, I probably mixed this up with the HTML characters.
I think the db string is set in the search engine adapter:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp#L567

**Comment by timosachsenberg** [comment]
"We never discussed this but the implicit assumption I had was that all C-strings in OpenMS are either ASCII or UTF8 but never ISO 8895, correct?"

That's a good question and I think it is not defined anywhere. 
Internally, all std::strings are  single byte per entry and agnostic to the actual encoding in most parts of the library. 

I need to look into this a bit deeper after my holidays but maybe we need to check if file names are returned by the/Some operating system encoded as UTF-8 and we just thread them as plain ASCII.

**Comment by hroest** [comment]
> "We never discussed this but the implicit assumption I had was that all C-strings in OpenMS are either ASCII or UTF8 but never ISO 8895, correct?"
> That's a good question and I think it is not defined anywhere.

well, it somehow is by convention as we start our XMLs with a certain encoding. However we are not very consistent: 

```
$ grep "xml version" source/FORMAT/HANDLERS/*
source/FORMAT/HANDLERS/MzDataHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
source/FORMAT/HANDLERS/MzIdentMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
source/FORMAT/HANDLERS/MzMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
source/FORMAT/HANDLERS/MzQuantMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
source/FORMAT/HANDLERS/MzXMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
source/FORMAT/HANDLERS/TraMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << "\n";
```
so basically we use the same underyling encoding but sometimes write out files where we promise they are going to be 8859 and sometimes we promise they will be UTF8 ... hmmm ... seems like there is "room for improvement" --- and whoever thought ISO-8859 was a good idea? Well overall we have a pretty good mixture in the whole source code it seems:

```
$ grep -R "xml version" source/
source/ANALYSIS/ID/HiddenMarkovModel.cpp:    out << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << endl;
source/TEST/VISUAL/parameters.ini:<?xml version="1.0" encoding="ISO-8859-1"?>
source/APPLICATIONS/TOPPBase.cpp:      lines.replace(0, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
source/APPLICATIONS/TOPPBase.cpp:    os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << endl;
source/FORMAT/XQuestResultXMLFile.cpp:    xml_file << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << std::endl;
source/FORMAT/XQuestResultXMLFile.cpp:    spec_xml_file << "<?xml version=\"1.0\" encoding=\"UTF-8\"?><xquest_spectra compare_peaks_version=\"3.4\" date=\"Tue Nov 24 12:41:18 2015\" author=\"Thomas Walzthoeni,Oliver Rinner\" homepage=\"http://proteomics.ethz.ch\" resultdir=\"aleitner_M1012_004_matched\" deffile=\"xquest.def\" >" << std::endl;
source/FORMAT/XQuestResultXMLFile.cpp:    spec_xml_file << "<?xml version=\"1.0\" encoding=\"UTF-8\"?><xquest_spectra compare_peaks_version=\"3.4\" date=\"Tue Nov 24 12:41:18 2015\" author=\"Thomas Walzthoeni,Oliver Rinner\" homepage=\"http://proteomics.ethz.ch\" resultdir=\"aleitner_M1012_004_matched\" deffile=\"xquest.def\" >" << std::endl;
source/FORMAT/XTandemInfile.cpp:    os << "<?xml version=\"1.0\"?>" << "\n"
source/FORMAT/QcMLFile.cpp:    os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
source/FORMAT/HANDLERS/MzMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
source/FORMAT/HANDLERS/MzQuantMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
source/FORMAT/HANDLERS/MzXMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
source/FORMAT/HANDLERS/MzIdentMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
source/FORMAT/HANDLERS/MzDataHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
source/FORMAT/HANDLERS/TraMLHandler.cpp:      os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << "\n";
source/FORMAT/ConsensusXMLFile.cpp:    os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
source/FORMAT/IdXMLFile.cpp:    os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
source/FORMAT/ParamXMLFile.cpp:    os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n";
source/FORMAT/TransformationXMLFile.cpp:    os << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << "\n";
source/FORMAT/PepXMLFile.cpp:    f << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" << "\n";
source/FORMAT/FeatureXMLFile.cpp:    os << "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
```


> I need to look into this a bit deeper after my holidays but maybe we need to check if file names are returned by the/Some operating system encoded as UTF-8 and we just thread them as plain ASCII.

yes, this is actually what we do in all XML data, e.g. xerces returns UTF16 data we convert it through the StringManager using `XMLString::transcode` (see L281 https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp#L281 ) which we then transcode to whatever the "local code page is" (probably UTF8, see https://stackoverflow.com/questions/9826518/purpose-of-xmlstringtranscode ) - it seems what xerces actually does will depend on the local platform and setttings which is not so great and maybe part of the problem? See here for the docs: https://xerces.apache.org/xerces-c/apiDocs-3/classXMLString.html#a91b02742b80418fbc6c54b7dd353ad8c

so currently we cannot control what encoding comes out in the C-string which just seems like a horrible idea!  it seems we  are not the only ones with that issue: https://xerces.apache.org/xerces-c/faq-parse-3.html#faq-19 and we could use `XMLPlatformUtils::fgTransServer->MakeNewTranscoderFor()` to transcode UTF16 to whatever we want (probably UTF8).

**Comment by hroest** [comment]
Well regarding this question it seems pretty easy to understand why this happens. We basically almost randomly write files that claim to be encoded with either UTF8 and ISO 8859 and then write string into them that are of unknown encoding (conforming to the local "platform native encoding" that may be different on Win/OSX/Linux) and then its not surprising that this whole mess backfires...

**Comment by timosachsenberg** [comment]
I think much of these file formats date back to a time where UTF8 did not exist / was not well established. Choosing UTF8 as the default encoding might be a good choice.
As I understand it this means that we need to natively support UTF8 in some of our internal data structures (like DataValue). Do you know what the best way is to handle plain strings? Assuming every std::string is now an UTF8 string will probably not work very well. Using a UTF8 string for everything will be also detrimental for performance. My guess is that we need to identify every string that needs to be UTF8 encoded and do a manual conversion using Boost.Locale, Qt, or similar.

**Comment by hroest** [comment]
> Do you know what the best way is to handle plain strings?

since this is C++, there is no "real" way see here: https://stackoverflow.com/questions/3011082/c-stdstring-and-utf-8 

however the question is whether we *need* it, e.g. being UTF8 aware is only necessary if we need to perform string operations but not if we are just "passing it through", e.g. reading the string and writing it again. However if you want to compute on the string (iterate, get its length etc) then you would need to be aware that its UTF8 and then we better use a library. Also the question is whether things like substring selection and comparison will work (I think it will if you have the same byte order but sometimes you would need to normalize your UTF8 first if you have multiple ways to encode a character such as Umlauts). also things like toUpper etc will be affected. The question is again how often we would really need that (and how often we need it on non-ASCII data) - we should probably do it for file paths :-) 

> Assuming every std::string is now an UTF8 string will probably not work very well. 

why not? We just need to make sure that all input gets converted to UTF8 before we store it in one of our internal data structures. When we read the strings we ensure that they are properly converted, e.g. from the xerces XML parser they come in as UTF16, so we convert them to UTF8 and store them in our std::string. 

> Using a UTF8 string for everything will be also detrimental for performance.

depends, most data will be ASCII and there should be no difference in performance. I think you can achieve the same performance for pure ASCII with only a performance issue when you are actually dealing with unicode. Also converting file path to unicode will not be a performance bottleneck but we need to make sure that reading FASTA files does not suffer.

**Comment by timosachsenberg** [comment]
Ok. So I guess UTF8 strings might come from:
- the command line parameters (e.g., file names)
- XML files
And these parts are probably easy to handle.
Generic text files etc. might be a bit more involved right now.

**Comment by timosachsenberg** [comment]
I don't know if it is thaaat easy. For the ini file we might assume that it is UTF-8 - ok that's fine and should not pose any problems. 
But for the command line the situations seems to be a bit more difficult.
See e.g. https://stackoverflow.com/questions/5408730/what-is-the-encoding-of-argv
Seems qt solved that problem:
https://stackoverflow.com/questions/39379119/how-can-i-get-qt-main-function-argv-parameter-as-unicode-encoding-format

**Comment by timosachsenberg** [comment]
so one way to do this would be to use qt to convert the unicode argv using toUtf8

**Comment by hroest** [comment]
> so one way to do this would be to use qt to convert the unicode argv using toUtf8

I agree, since we already have Qt why not use to read the command line string options and then directly "do the right thing" ? Once we have it converted to UTF8 then we can store it internally in a `std::string` if we like with the guarantee that its UTF8

> XML files

proper XML files have their encoding embedded and xerces will deal with it and convert it to UTF16 internally from whatever encoding they come from.

**Comment by hroest** [comment]
Another issue that follows from this: since we dont know the encoding of the underlying C-string that is contained in `OpenMS::String`, we cannot properly pass this to Python. We only know that Xerces has converted this at some point from UTF16 to the "local code page" [1]. In OpenMS we use the `xercesc::XMLString::transcode` function to convert from UTF16: 

https://github.com/OpenMS/OpenMS/blob/3bf4fc9b390c6bcabb1f81fb31fef568ed883ca1/src/openms/include/OpenMS/FORMAT/HANDLERS/XMLHandler.h#L89-L95

According to [2] the resulting string may be encoded either in iso-8859-1 or windows-1252 or potentially something else, but it is hard to know which it is. This makes it also hard to know for Python and difficult to return anything but bytes for Python.

Ref 1: https://xerces.apache.org/xerces-c/faq-parse-3.html#faq-19
Ref 2: https://xerces.apache.org/xerces-c/faq-parse-3.html#faq-17

**Comment by timosachsenberg** [comment]
any update here?

**Comment by hroest** [comment]
@timosachsenberg @oliveralka yes we could transcode to UTF8 if we want to make everything UTF8 in OpenMS which is where we seem to be going anyways. I am not sure what the implications would be on Windows and how commandline arguments would be handled.

**Comment by ekawaler** [comment]
Hello! What is the current status of this issue?

**Comment by poshul** [comment]
This is still open and marked critical what is the state of it?

**Comment by jpfeuffer** [comment]
Still a mess
