### ISSUE TITLE
eigen3 include

### ISSUE THREAD

**Issue by ysagon** [OpenMS/OpenMS#2830]
I have an issue to build OpenMS from source. I'm trying to use as many external lib as possible and it's the case with eigen3

In this file:
    
    OpenMS/blob/develop/src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/OptimizePick.h

line 49, there is an include for eigen3
    
    #include <eigen3/Eigen/Core>

Is this correct to prefix Eigen with eigen3?

My Eigen 3 library is installed without the eigen3 directory and thus the build is failling.

**Comment by hroest** [comment]
the easiest way to install is to follow the install instructions: http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_linux.html

can you indicate which system you are using? AFAIK it is only possible on Ubuntu systems 17.04 or higher to completely use system libraries and not install any libraries through contrib. Since these systems work out of the box, I also believe the prefix is correct. See also the ubuntu package: https://packages.ubuntu.com/zesty/all/libeigen3-dev/filelist

```
[...]

/usr/include/eigen3/Eigen/CholmodSupport
/usr/include/eigen3/Eigen/Core
/usr/include/eigen3/Eigen/Dense
/usr/include/eigen3/Eigen/Eigen
/usr/include/eigen3/Eigen/Eigenvalues
/usr/include/eigen3/Eigen/Geometry
[...]
```

**Comment by ysagon** [comment]
Yes I agree that the easiest way is to follow the instructions on the link.

I'm the sysadmin of an HPC cluster and I wanted to install this software globally.
In this cluster we are using CentOS 6.9.
All the softwares we provide to the endusers are provided/installed with the help of [EasyBuild](http://easybuild.readthedocs.io/en/latest/)
In EasyBuild, eigen3 is provided without the eigen3 directory.

If you have a look in the [getting started page of eigen3](https://eigen.tuxfamily.org/dox/GettingStarted.html), you can see in the example source code that they don't specify eigen3 as include path as well.

**Comment by hroest** [comment]
hmm I agree when looking at their own docu, it seems like they use `Eigen/Core` for includes: https://eigen.tuxfamily.org/dox/GettingStarted.html but there may be a reason for debian to use eigen3 in order to prevent name clashes - e.g. maybe its possible to install eigen2 and eigen3 at the same time?

in either case, it seems like `eigen3` is actually only used in 3 places:
```
$ grep -R 'include.*eigen3' src/openms
src/openms/source/TRANSFORMATIONS/RAW2PEAK/TwoDOptimization.cpp:#include <eigen3/Eigen/Core>
src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/OptimizePick.h:#include <eigen3/Eigen/Core>
src/openms/include/OpenMS/TRANSFORMATIONS/RAW2PEAK/OptimizePick.h:#include <eigen3/unsupported/Eigen/NonLinearOptimization>
```

so it should be straight forward for you to fix it. For OpenMS, it would probably also work as in my case CMake finds the inner path when using `find_package(Eigen3)`, e.g. it produces `-isystem /home/hr/openmsall/builds/contrib-all-old/include/eigen3` which means that using `eigen3/Eigen` is actually wrong.
