### ISSUE TITLE
XMLHandler's StringManager needs to go!

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#2899]
just documenting this here; implementation will probably take 1-2 days, but could be done piece-by-piece.

while looking at the read/write performance of our XML files, I stumbled upon our long-forgotten `StringManager` class which is part of the XMLHandler and therefore affects all our Xerces-based xml reading. In short, it takes ownership of every string which is passed from xerces to our internal datastructures (usually from XMLCh to char*).

For a common idXML this means the following number of pointers (to heap allocated characters) are created
xml_strings: #14086589  c_strings: #21363930
this alone amounts to about 280 MB, not counting the actual data being pointed to (which is probably about 5x as big). Note: only the last few entries in these arrays are used, and only once!
This wasteful style also explains why we need 2300 MB Peak Memory to read in a 200 MB idXML file.

Not storing the array pointers (effectively creating a memory leak for the moment), saves 10% of loading time and the mentioned 280 MB RAM.

The proper solution IMHO would be to remove the StringManager completely and use unique_ptr with a custom deleter (which calls `xerces::XMLString::release(ptr)`). In in the mentioned example, this would mean 10% faster, and approx 1/2 the RAM for loading.

**Comment by cbielow** [comment]
another workaround: using the vectors as before but as a ring-buffer of fixed size (here 100), this is what happens to the Mem & runtime:
```
FileInfo took 31.06 s (wall), 28.19 s (CPU), 0.86 s (system), 27.33 s (user).
Peak Memory Usage: 2412 MB
```
after:
```
FileInfo took 24.28 s (wall), 24.18 s (CPU), 0.56 s (system), 23.62 s (user).
Peak Memory Usage: 1244 MB
```

That's **30% speed increase and 50% memory decrease**. We can expect similar improvements for many XML formats (when reading). PR coming up.

**Comment by timosachsenberg** [comment]
Nice find!
I would probably prefer automated memory management with unique_ptr instead of the ring buffer. 
Something in the line of:
```
    auto xerces_deleter = [](XMLCh * a) { xerces::XMLString::release(a); };
    std::unique_ptr<XMLCh, decltype(lambda)> f(XMLString::transcode(str), xerces_deleter);
```

**Comment by cbielow** [comment]
Agreed. But this change was doable in 10min. The other one takes more time to implement but should also be a bit faster due to hot caches.

-- 
Sent via mobile phone.

Am 9. September 2017 20:35:20 MESZ schrieb Timo Sachsenberg <notifications@github.com>:

**Comment by timosachsenberg** [comment]
by the way. Why do these need to be stored?
Can't we just free them after transcoding like in this example:
https://resources.oreilly.com/examples/9780596007614/blob/master/14-4.h
From the C++ cookbook?

**Comment by hroest** [comment]
yes, the only reason we need to store them is when the caller assumes that  the StringManager takes ownership of the `char *` ptrs. However, changing who owns these ptrs this late into the game *will* lead to memory leaks. Just look at what `StringManager::convert` does:

```
279     char * StringManager::convert(const XMLCh * str) const
280     {
281       char * result = XMLString::transcode(str);
282       c_strings_.push_back(result);
283       return result;
284     } 
```

so the StringManager takes ownership and all the ptrs are valid until the StringManager gets deleted. With a lot of strings that are used often directly after calling the StringManager, this leads to a lot of waste. Also, this seems like a perfect application of the move semantics, e.g. generate a `std::string` and move it out of the StringManager scope ... 

> another workaround: using the vectors as before but as a ring-buffer of fixed size (here 100), this is what happens to the Mem & runtime:

this seems very dangerous, how do you know when the caller is done with the c_string ? What if the caller tries to use a c_string after processing 100 different strings and there is a completely new string at that location. The safe thing to do is to add a new fxn to StringManager:

```
279     OpenMS::String StringManager::convertString(const XMLCh * str) const
280     {
281       char * result = XMLString::transcode(str);
283       return result;
284     } 
```

now this will have better performance than @cbielow proposed solution, but be much safer since a new `OpenMS::String` gets generated and ownership is clearly not with StringManager any more

**Comment by hroest** [comment]
also we should maybe remove some abstraction layers and really think about where these strings ultimately end up. Often we only need them for very short time, and often we can make some safe assumptions (e.g. they are all ASCII and dont need to be modified). See e.g. MzMLHandler

```
// MzMLHandler.cpp: void MzMLHandler::startElement
const XMLCh* const qname // fxn argument
String tag = sm_.convert(qname);
...
if (tag == "spectrum")
...
```
which will execute the following

```
279     char * StringManager::convert(const XMLCh * str) const
280     {
281       char * result = XMLString::transcode(str);
282       c_strings_.push_back(result);
283       return result;
284     } 
```

first of all, `StringManager::convert` has to assume that the tag may contain unicode which it clearly doesnt for all our file formats. So calling `XMLString::transcode` is complete overkill for ASCII and has to do a lot of additional unicode checks that we dont need. Then we execute a `std::vector::push_back` that we do not really need and finally we call `String::String(const char* s) : std::string(s)` to generate the `OpenMS::String` from the `char *` which copies the whole data around again. Now compare this to something more efficient with fewer abstractions:

```
// MzMLHandler.cpp: void MzMLHandler::startElement
const XMLCh* const qname // fxn argument
String tag;
// safer than strlen
size_t xml_len = 0;
for (const XMLCh* it = qname; (char)*it != '\0'; it++, xml_len++) {}
tag.resize( strlen(xml_len) ); //only works for ASCII
std::string::iterator str_it = tag.begin();
for (const XMLCh* it = qname; *it != '\0'; it++)
{
  *str_it = (char)*it;
  ++str_it;
}
```

now obviously for `(char)*it` and determining the length to work, we cannot have unicode in there. Obviously any unicode char in there would create big problems. However if we know that its all ASCII, which we often do, we could improve our function above to 

```
OpenMS::String StringManager::convertStringASCII(const XMLCh * str) const
{
  String result;
  // safer than strlen
  size_t xml_len = 0;
  for (const XMLCh* it = str; (char)*it != '\0'; it++, xml_len++) {}
  tag.resize(xml_len); 
  std::string::iterator str_it = tag.begin();
  for (const XMLCh* it = str; *it != '\0'; it++)
  {
    *str_it = (char)*it;
    ++str_it;
  }

  return result;
} 

```
which in C++11 due to RVO (https://stackoverflow.com/questions/17473753/c11-return-value-optimization-or-move
) will be used to `move` the `result` variable out of the function, avoiding
unnecessary copies. We have to iterate twice through the string since it is probably faster to do that and then `resize` a `std::string` than to iterate once but keep appending a string and thus keep allocating new memory. Just my guess.

**Comment by hroest** [comment]
PS: for conversions from `char *` to `XMLCh *` I think using Timos approach with the unique_ptr is the best way to go.

**Comment by hroest** [comment]
> For a common idXML 

@cbielow can you provide an example file for testing?

**Comment by timosachsenberg** [comment]
ok I think we can close this issue. Still room for improvements though.
