### ISSUE TITLE
 ConvertTSVToTraML error (Could not convert string '' to a double value)

### ISSUE THREAD

**Issue by eseble** [OpenMS/OpenMS#2927]
Hi I am trying to convert a spectral library to TraML and I get the following error
Error: Unexpected internal error (Could not convert string '' to a double value)

The library was created using spectrast2tsv.py

Any idea what could be the problem?

**Comment by grosenberger** [comment]
Could you please provide an example file (as small as possible)? One common reason for this are modifications that are not natively supported by ``spectrast2tsv.py``. If this is the case, you can either supply a custom [modification file](https://github.com/msproteomicstools/msproteomicstools/blob/master/msproteomicstoolslib/data_structures/modifications_default.tsv) using the option ``-m`` to ``spectrast2tsv.py`` or you can generate a ``.MRM`` file with SpectraST (``spectrast -cM``) and use this as input to ``ConvertTSVToTraML``. In the latter case, make sure to filter the TraML afterwards with ``OpenSwathAssayGenerator``.

**Comment by eseble** [comment]
I attach the library I am trying to convert. I have checked the modification_default file and it is the same as in your link. I tried converting again and the error message now is
Error: Unexpected internal error (The value 'UniMod:26' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'C' and term specificity 0.)

If I edit the library.csv file to delete all the peptides with UniMod;26 then the error changes to UniMod:27.

[SpecLib_consMaturaOver20_EA_5_100_openswath_mod2.zip](https://github.com/OpenMS/OpenMS/files/1333273/SpecLib_consMaturaOver20_EA_5_100_openswath_mod2.zip)

**Comment by grosenberger** [comment]
UniMod:26, UniMod:27, UniMod:28 are all N-terminal modifications, however, they are reported as residual modifications by ``spectrast2tsv.py``, e.g. C(UniMod:26)PEPTIDEK. Since recently, OpenMS is parsing AASequences more explicitly and thus the peptide sequence should be provided as (UniMod:26).CPEPTIDEK. The ``.`` indicates N- or C-term modifications.

I have changed your file accordingly and this converts to a TraML now. My suggestion would be to either fix this manually or to use the suggested workflow converting from MRM to TraML directly, since this uses the OpenMS AASequence parser, which I hope is more robust.
[SpecLib_consMaturaOver20_EA_5_100_openswath_mod2_fixed.tsv.zip](https://github.com/OpenMS/OpenMS/files/1333399/SpecLib_consMaturaOver20_EA_5_100_openswath_mod2_fixed.tsv.zip)

**Comment by eseble** [comment]
Thank you. However I have tried using the fixed file you provided and I still get an error

Error: Unable to read file (Cannot convert string to amino acid sequence: unexpected character '.' in:(UniMod:26).CAEENC(UniMod:4)FIQK)
Does it need to have another "." at the end of the sequence i.e. (UniMod:26).CAEENC(UniMod:4)FIQK.?
This happens both trough the command line and using the knime interface for OpenMS
I have OpenMS  2.1.0. which I think is the last version?

I'll try to use the MRM workflow and see if I have better luck.

**Comment by grosenberger** [comment]
Sorry about that, I conducted my tests with OpenMS/develop and I believe the changes are implemented only since OpenMS 2.2, which was a source-only release. Please note that ``ConvertTSVToTraML`` has been renamed to ``TargetedFileConverter`` and provides additional functionality.

It might potentially also work with OpenMS 2.1, if you remove the ``.`` between to N-term (UniMod:26) and C.
