### ISSUE TITLE
TOPPView peak annotation merges user annotations and mz annotations in a strange way.

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2956]
When I add the m/z value to an assigned peak and I click on another spectrum or save the annotation as a new idxml. The peak label and the m/z value are merged. Unfortunately in a way that only the m/z and the charge is left. Same is true for adding a peak annotation manually and a m/z. Seems like only using the label function works kind of but this doesn’t help for the already annotated peaks. 

e.g. two labels with “y1 +1” and “m/z 147.1127” becomes “147.1127 +1” 

BTW, I liked it better in the older versions when it read “2+” instead of “+2”. And it is a bit annoying that ToppView doesn’t automatically zoom into the appropriate m/z range for each MS2 but instead keeps the zoomed range of the previous spectrum.

**Comment by enetz** [comment]
@timosachsenberg 
I looked into this a bit. The issue is this:
The annotations on the Spectrum and the annotations of the PeptideHit are not directly connected,
but synchronized every time there is a change.
Currently only one annotation is allowed per peak, it should be the latest one that was placed.
If the newest annotation does not have something recognizable as a charge, the old one stays, otherwise it will also be replaced.

The main issue preventing multiple annotations is this:
during the synchronization we do not know which annotations were newly added and which were edited. If we try to compare the annotations and only add the ones that were not there before, we will keep the old annotation before the editing and the new one after editing. I think things would be much easier, if we removed the editing function (instead just remove one annotation and add another). The removing of annotations already works and without the edit function we could just add all annotations that do not match the existing ones. That would still not allow multiple equal annotations, but I don't see an alternative with our current way of doing this.

We could try to separate the editing and adding of annotations, but for that we would need to keep the annotation before editing somewhere to know which one we need to update.

**Comment by enetz** [comment]
Maybe I can make this work as it is. If we delete all PeptideHit annotations by default and replace them with the current Spectrum annotations, it should solve all these issues.
I will try that and make a PR if it works.

**Comment by enetz** [comment]
The thing with the charge representation is another issue.
It might be more difficult to parse the charge from such a String, e.g. y66+ vs y6+6.
This might be an ugly notation, but even with something as simple as that it would be obvious, that the +6 is a charge in the second example. Since we are parsing the charges from strings and also from manual annotations, it would make it difficult to put the plus at the end by default.

And I have no idea how to set the zoom range yet.
