### ISSUE TITLE
Background subtraction on smoothed chromatograms

### ISSUE THREAD

**Issue by dmccloskey** [OpenMS/OpenMS#2975]
Allow for background subtraction on the smoothed chromatogram.  For noisy acqusition data, the background can be over estimated due to spurious points in the raw chromatogram that are filtered out during the smoothing process.

**Comment by hroest** [comment]
sounds like a good idea -- another idea would be to use a median value of the area around the peak that is not actually part of the peak: 

- take +/- 1 minute around the peak borders and calculate the median value of that

**Comment by hroest** [comment]
to actually implement this and get access to the smoothed chromatograms, I suggest

One option to solve this issue is to store the smoothed chromatogram as a member of the PeakPickerMRM and then keep it around for later processing:
```
- 107     MSChromatogram smoothed_chrom = chromatogram;
+ 107     smoothed_chrom_ = chromatogram;
```
and make smoothed_chrom_ a member of PeakPickerMRM and then give access to it through a function. I have to say its not a very clean solution because PeakPickerMRM is supposed to be an algorithm that is not dependent on internal state, -- the other way to do it would be to change the interface to
```
void PeakPickerMRM::pickChromatogram(const MSChromatogram& chromatogram, MSChromatogram& picked_chrom)
{
  MSChromatogram s;
  pickChromatogram(chromatogram, picked_chrom, s);
}

void PeakPickerMRM::pickChromatogram(const MSChromatogram& chromatogram, MSChromatogram& picked_chrom, MSChromatogram& smoothed_chrom)
```

this way one can still use the old interface. I think I would prefer that to the member solution as I dont like the idea of having internal state in algorithm classes.

**Comment by dmccloskey** [comment]
I will go with the latter option then and implement the interface how you have outlined.

**Comment by dmccloskey** [comment]
#2944 should take care of this.
