### ISSUE TITLE
User-defined mods in MSGFPlusAdapter

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#2977]
Hi.

If I got it right, custom mods can be added to the MSGFPlusAdapter by manually modifying the mods.txt file. 

Wouldn't it be more user-friendly to allow for mod definition in the settings of MSGFPlusAdapter? A solution like this is provided in the [Galaxy-Wrapper](https://github.com/Stortebecker/tools-galaxyp/blob/master/tools/msgfplus/msgfplus.xml) for MSGF+, see lines 35-37 and 142-196. The custom mods are automatically appended to the mods.txt. Its pretty straight-forward and the user would not have to cope with the unimod syntax.

Greetings, Flo

**Comment by timosachsenberg** [comment]
Hi,
For consistency (and because we want to carry this information over to other tools) reason, OpenMS writes out the modifications stored in unimod (several hundreds) to the mods.txt file used by MSGFPlus.
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp#L345

Do you need a custom modification not contained in unimod?
If so you can search for the CUSTOM0-N entries in unimod.xml in the share/OpenMS/CHEMISTRY folder of OpenMS and add it there. Would this also work for you?

**Comment by Stortebecker** [comment]
Your solution would work locally, but it is difficult to implement into the galaxy wrapper for MSGFPlusAdapter. We would have to automatically create a modified file and use this instead of the normal one. I am not sure if this would work.

To clarify: I am not searching for a special modification, it was just an idea to enable custom mods for normal users.

**Comment by timosachsenberg** [comment]
Ok I think I understand now. 
Maybe there is a way how we could handle modifications not contained in unimod in the future if we carry along enough meta information in the resulting identification files.

**Comment by jpfeuffer** [comment]
Let's continue in #1915
