### ISSUE TITLE
TOPPView resets colours when new layer is opened

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3012]
`TOPPView` allows to change the colour of `featureXML` and `consensusXML` layers. When an additional layer is opened, the colours of the *previous layers are reset to default*.

Previously, this was not the case and the colours of the layers remained unchanged. Can we go back to the old behaviour?

**Comment by timosachsenberg** [comment]
can you confirm that this is not a result of different intensity ranges?

**Comment by hroest** [comment]
@lars20070 how did you set the colors? Did you set them globally through File->Preferences or by right-clicking on a canvas and then setting the colors? It seems that TOPPView currently behaves as follows


-    setting color preferences by right-clicking on a canvas only changes it for that canvas (is a nice feature, allows individual settings -- I think it is a good feature but may not make sense for everybody)
-    setting color preferences globally through File->Preferences does not change any of the current layers (may be surprising)
-    setting color preferences globally through File->Preferences will set the color gradient for all maps (peak / feature / consensus)


> Previously, this was not the case and the colours of the layers remained unchanged. Can we go back to the old behaviour?

I tried this with TOPPView 2.1 and the behavior is the same with 2.1 as with the current development branch. It does not seem as if we had changed that behavior. I think your problem is a combination of (ii) and (iii) above: there is currently no way to change the color and apply that change to *all current layers and all future layers* - you can only do one or the other.

**Comment by lars20070** [comment]
@hroest This issue concerns only local colour changes i.e. right-clicking a canvas.
Exactly what you describe in issue (iv) above.

**Comment by enetz** [comment]
I think I found the code that causes this:
`Spectrum2DCanvas::finishAdding_()` is called after a new layer was added and calls
`intensityModeChange_();`. That function is defined here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp#L1060

`Spectrum2DCanvas::intensityModeChange_()` applies the same gradient (seems to be the default gradient) to all layers and recalculates the gradients with these two lines:
```
      layers_[i].param.setValue("dot:gradient", gradient_str);
      recalculateDotGradient_(i);
```

The second line updates the colours in the case that the range of intensities is changed, e.g. when the new layer has a new maximal intensity. If this is not done, then using the same gradient the same intensity value might have a different colour between layers.

But the first line applies a default gradient colour scheme to all layers.
This might be necessary when changing from linear scale to logarithmic and back or in other cases (this function is called at other places as well), but probably not when adding a new layer.

@lars20070 you can try to remove this line and see how TOPPView behaves with multiple different featureXMLs or when changing the intensity scale:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp#L1073
Maybe we can add another `intensityModeChange_()` without this line specifically for adding new layers, if that works.
