### ISSUE TITLE
Nightly windows install does not have all libraries

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3410]
When installing the nightly installer (from April 9th): https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/

I get the following errors when trying to start TOPPView or TOPPAS: `Code execution cannot proceed because X was not found` and it seems at least the following libs are missing

- Qt5Widgets.dll
- Qt5Svg.dll
- Qt5Gui.dll

the other TOPP tools seem to work. Maybe this was addressed by 4cce057e5e119b97b82ec020a302424df4811c8c ? In my own tests (see #3409 ) I have seen that Qt also needs to have `libEGL.dll` for the 3D stuff and it needs to have a `platforms/qwindows.dll` folder with the windows-specific dll in there.

**Comment by jpfeuffer** [comment]
Hey. Yes the QT5 GUI libs and the QT5 plugins were fixed recently again #3383 . However we did not yet have problems with libEGL.dll. Probably the QT installer build indeed uses a different flag for -opengl.
The last build is here https://abibuilder.informatik.uni-tuebingen.de/jenkins/view/OpenMS/job/openms_nightly_packaging/compiler=msvc-14,os_label=win10_64/240/artifact/build/
It was not uploaded because of failing InspectAdapter tests.

**Comment by hroest** [comment]
Ok, great these work now and it looks like all the nightly tests pass so we should see these get uploaded soon? http://cdash.openms.de/index.php?project=OpenMS&date=2018-04-25
