### ISSUE TITLE
protein inference support in Percolator adapter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#3466]
Protein inference in `Percolator` is a powerful algorithm. In our tests, the tool scales well and performs similarly to `ProteinProphet`. It would therefore be very useful to implement support for the protein inference part of `Percolator` in the `PercolatorAdapter` as well.

**Comment by MatthewThe** [comment]
I think there's already support for this, have you tried setting `protein-level-fdrs` to true?

**Comment by wenjiebi** [comment]
@MatthewThe In the aspect of protein inference, I compared PercolatorAdapter with FidoAdapter. The workflow, filtered mzML file, database and results are [Here](https://www.dropbox.com/sh/gv2r0gol4ztd1hl/AACk3B5eXLHqIbnWL_8PdjGOa?dl=0). There are much fewer protein generated by Percolator

  | Percolator | Fido
-- | -- | --
PRT | 5725 | 8784
PSM | 9092 | 9054

I don't know if the parameters were set correctly. Can you please help to check it?

**Comment by MatthewThe** [comment]
There are several independent issues at play here:
- FidoAdapter creates protein groups based on the observed peptides (last column in the mzTab = `indistinguishable_group` instead of `single_protein`). If you just count the `single_protein` rows you will also have 5725 proteins.
- If you're trying to assess the performance based on the number of _significant_ proteins, you will have to set some threshold, instead of simply counting _all_ proteins as you do now. However, this is a bit tricky since FidoAdapter only seems to report the `Posterior Probability` and no FDR. One way to compare would be to compare "1 - `Posterior Probability`" of the FidoAdapter output to the field `MS:1001493` (Percolator:PEP, which is the Posterior Error Probability) of the PercolatorAdapter output. You can also calculate the FDR from the FidoAdapter results by sorting by "1 - `Posterior Probability`" in ascending order and calculate a running average of the resulting Posterior Error Probabilities until this exceeds your FDR threshold.
- It seems your workflow has not incorporated #3462 yet, so the PercolatorAdapter results are not really useful at the moment.

**Comment by wenjiebi** [comment]
Thank you very much for your response.
To the first point, indeed the amount of `single_protein` are the same in FidoAdapter and PercolatorAdapter. Can we also get the `ìndistinguishable_group` in PercolatorAdapter? Because they are also useful information so we would expect them in the output of PercolatorAdapter.

**Comment by MatthewThe** [comment]
Percolator does not support protein grouping, since we do not find the estimates to be reliable (see our paper: `The, M., MacCoss, M. J., Noble, W. S., & Käll, L. (2016). Fast and Accurate Protein False Discovery Rates on Large-Scale Proteomics Data Sets with Percolator 3.0. Journal of the American Society for Mass Spectrometry, 27(11), 1719.`)

**Comment by lars20070** [comment]
@jpfeuffer Without protein groups, will the greedy algorithm in `ProteinQuantifier` work?

**Comment by jpfeuffer** [comment]
Greedy association of peptides will work but is currently only part of FidoAdapter. You will have to refactor it.
But group based quantification (which yields more uniquely associatable peptide quantities) won't. However it only needs indistinguishable groups, whose annotation (without actual inference) can be factored out, too, from the PeptideProteinResolution class I think.

**Comment by algom** [comment]
There are two options that if I understand correctly, might come in hand -although I don't know if they are implemented on the adapter- that would keep the information about proteins that a priori can be distinguished. One is the -c; --protein-report-fragments option which will make a comma-separated entry of the proteins in which it is not possible to differentiate a subset of a protein from other, though based on the whole sequence not on the identified peptides. On the other hand the -g; --protein-report-duplicates would do something similar but if entries contain the same peptides.

**Comment by lars20070** [comment]
@wenjiebi @algom and me want to make the `Fido --> Percolator` replacement in our workflows, since `Fido` does not scale as @MatthewThe correctly discusses in *The et al. (2016)*.

What is still missing in the adapter, and what are the recommended settings?

<img width="861" alt="screen shot 2018-06-05 at 16 40 29" src="https://user-images.githubusercontent.com/6149805/40983414-de40ce26-68df-11e8-9899-e9bd6f8f28d2.png">

**Comment by jpfeuffer** [comment]
It should work. But without grouping and greedy association of peptides.

**Comment by jpfeuffer** [comment]
You can refactor the functions in https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/ID/PeptideProteinResolution.h
et al.

**Comment by wenjiebi** [comment]
@MatthewThe Using the newest nightly build, the issue #3462 is not a problem anymore, I compared again `Percolator` with `Fido`. This time I used a reversed database instead of a shuffled one. And the data I got are quite surprising: this time even less `single protein `are from Percolator


  | Percolator | Fido
-- | -- | --
Single_protein | 7058 | 9820
PSM | 10399 | 8562

I'm not sure about the parameters, because they are not comparible

**Comment by wenjiebi** [comment]
![grafik](https://user-images.githubusercontent.com/35566652/41043775-f5fbacd2-69a4-11e8-9406-897faa5254c4.png)
![grafik](https://user-images.githubusercontent.com/35566652/41043811-07720808-69a5-11e8-97b3-57152d5cb66e.png)

**Comment by wenjiebi** [comment]
[Here](https://www.dropbox.com/sh/0x6y9762d1iebj2/AAC4VmR2AekDWzK8sKFncsnxa?dl=0) is the link to the workflow and files

**Comment by MatthewThe** [comment]
Is this filtered at 1% protein-level FDR? 

Could you share the mztab or idXML files coming from Percolator/FidoAdapter? I don't have the greatest internet connection at the moment..

**Comment by wenjiebi** [comment]
@MatthewThe @algom Sorry, it's my mistake forgetting to filter with FDR again.

One thing is still not clear for me: if I set `peptide-level-fdrs` in `PercolatorAdapter` to `true`, do I still need `FalseDiscoveryRate` after?

**Comment by wenjiebi** [comment]
It seems more weird for me to add `FalseDiscoveryRate` after. Because the data look like this:


  | Percolator | Fido
-- | -- | --
Single_protein | 157 | 1277
PSM | 257 | 3027

@MatthewThe I will add the mztab files to the same folder as above.

**Comment by lars20070** [comment]
*"... for the Swiss-Prot + TrEMBL database they typically contained just one or two proteins."*
The eta al. (2016).

@MatthewThe As I understand your paper, the *protein groups* are smaller (often trivial i.e. one protein) but `Percolator` still reports protein groups and consequently writes them to `mzTab` (see `single_protein`, `protein_group`, `indistinguishable_group`).

**Comment by MatthewThe** [comment]
@wenjiebi I don't know what FidoAdapter does, but I have the suspicion that the q-values of the `single_protein` rows are not calibrated at all. If you look at the `protein_group` rows, there are actually no rows with q < 0.01. Regarding the `peptide-level-fdrs` (and for that matter also `protein-level-fdrs`) there is no need for using the `FalseDiscoveryRate` node, other than for consistency when comparing to other approaches.

@algom the `--protein-report-fragments` and `--protein-report-duplicates` are currently not implemented in the adapter. In the context of OpenMS it might actually make sense to always set them (we'll then of course also have to change the parser of the protein results).

@lars20070 the protein groups are indeed smaller and often trivial. However, since the flags that @algom mentions are not implemented, we will currently not get them as `protein_group` but instead only get the first protein in alphabetical order as a `single_protein`.

**Comment by jpfeuffer** [comment]
I do not think we support FDR on protein groups, yet. What you see in the protein groups is probably still the posterior.

**Comment by wenjiebi** [comment]
@MatthewThe @jpfeuffer The `ProteinQuantifier` crashes because of there is no `protein_groups` coming out from `PercolatorAdapter`
Here is the error message`Error: Unexpected internal error (No information on indistinguishable protein groups found in file`

**Comment by jpfeuffer** [comment]
yes, this is expected and needs to be added in the code. If you can/want use groups from Percolator you have to parse the pout file a bit more. If you want to use the protein grouping from Fido, you need to call the functions in https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/ANALYSIS/ID/PeptideProteinResolution.h

**Comment by timosachsenberg** [comment]
I think it would be a good idea to collect the individual sub-tasks we need to tackle at the top of this issue. @lars20070 can you do that?

**Comment by lars20070** [comment]
I see just two sub-tasks. The first one will be quick.
- Add [`PeptideProteinResolution`](https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FidoAdapter.cpp#L483) i.e. *greedy resolution* to the `PercolatorAdapter`. Alternatively, move this step from the adapters to the `ProteinQuantifier`.
- Build complete example workflows, check for sensible results (same ball park as ProteinProphet or Fido) and upload to Knime workflow repository. The [current results](https://github.com/OpenMS/OpenMS/issues/3363) still appear to be incorrect. I would suggest three workflows.
1. XTandem (no Percolator re-scoring) --> Percolator protein inference --> protein FDR --> mzTab export
2. MS-GF+ --> Percolator re-scoring --> Percolator protein inference --> protein FDR --> mzTab export
3. MS-GF+ --> Percolator re-scoring -->  Percolator protein inference --> protein FDR --> protein quantification in `ProteinQuantifier`

**Comment by jpfeuffer** [comment]
Yes moving resolution of shared peptides to the quantifier would make sense, too.
