### ISSUE TITLE
Rename `opt_global_MS:1002053` as `opt_global_MS:MS-GF:EValue`

### ISSUE THREAD

**Issue by wenjiebi** [OpenMS/OpenMS#3490]
In the `mzTab` file I found it's hard to understand the column `opt_global_MS:100205`. Although @timosachsenberg explained it in #1446, it would be much easier for me to understand if, for example, rename `opt_global_MS:1002053` as `opt_global_MS:MS-GF:EValue`.

**Comment by timosachsenberg** [comment]
I agree that this is not human readable but partly because that's how additional meta information is annotated in the idXML file. Currently, the standard encourages to use cv terms instead of string identifier and that's what currently focus on. I think you could a simple lookup or replace with a script if you want a string representation.

**Comment by wenjiebi** [comment]
@timosachsenberg Thank you for the answer. As a biologist not knowing so much about bioinformatics, I can't make the scripts myself. Is it possible to attach it in the end of the tool in OpenMS, like `MSGF+`?

**Comment by timosachsenberg** [comment]
I think one approach would be to detect these CV terms in the mzTab exporter and map them automatically to the name of the CV term (maybe as optional flag "human_readable_CV_terms" in the mzTab exporter).
