### ISSUE TITLE
FalseDiscoveryRate q-value calculation for rank > 1 hits might be suboptimal

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3725]
@jpfeuffer kind of half questions / half observation.
If fdr is configured to keep decoys and assign q-values to all ranks (use_all_ranks option) it includes rank > 1 hits into q-value calculation.
I think it might make more sense to calculate the q-value distribution only based on the top scoring hits only but assign q-values also to the rank > 1 hits.

**Comment by tjeerdijk** [comment]
My two cents: the standard Bejamini-Hochberg FDR control procedure assumes independence of the p-values. This assumption is usually wrong but is certainly less violated when only the top hit is picked.

**Comment by hroest** [comment]
It is not clear what the rank 2 q-value should be since it is unlikely to be true, I think the best option would be to compute the q-values on the top rank only and then assign the q-values based on where the lower ranks would be in the rank-1 distribution. So I think we should do all computation on top rank only, that is also what we do in pyProphet if I understand correctly (@grosenberger ? )

**Comment by grosenberger** [comment]
Yes, that's correct. By default, PyProphet estimates q-values using the top peak groups and Percolator now also supports that strategy. However, there are scenarios when it makes sense to compute the q-values on all peak groups, e.g. when searching/querying for phosphopeptides, where the PSMs or peak group candidates are only selective on the peptide sequence and PTM-level, but not in respect to site-localization.
