### ISSUE TITLE
IDPosteriorErrorProbability: Gumbel distribution not effectively available [377]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#377]
Submitted by azerck on 2011-11-24 15:30:23

Even if the Gumbel distribution is chosen as distribution for the incorrect scores, it is never used in the code.

Line 81-89 of PosteriorErrorProbabilityModel.C say:

```
if(param_.getValue("incorrectly_assigned") == "Gumbel")
{
   ...
  //TODO: compute directly with gauss. Workaround:   
  calc_incorrect_ = &PosteriorErrorProbabilityModel::getGauss;
  getNegativeGnuplotFormula_ = &PosteriorErrorProbabilityModel::getGumbelGnuplotFormula;
}
```

As I don't understand the commentary line, I didn't simply want to change it to

```
 calc_incorrect_ = &PosteriorErrorProbabilityModel::getGumbel;

```

However, when I tested it with the Gumbel distribution for my Ids the distributions of correct and incorrect scores "switched places" during the fit, resulting in misleading PEPs in the end (without a warning or anything).

**Comment by jpfeuffer** [comment]
iirc it is used in the end to calculate the probability with Bayes. But since Gumbel does not have a closed form solution for the M-step and the LM numerical optimizer is complex it seems like the Gaussian mean and sd was just used as a final estimate.
I agree that it is a major defect and we should think about non/semi-parametric fitting algorithms like kernel density estimation and/or use decoy information if available.

**Comment by jpfeuffer** [comment]
#2172 #937

**Comment by timosachsenberg** [comment]
why can't we just do a LM and let the other extensions as feature request?

**Comment by timosachsenberg** [comment]
@jpfeuffer I think you did something regarding this issue. Still relevant?

**Comment by jpfeuffer** [comment]
Yes. I think it is not yet available in the tool. But the functions exist and work with tests.
