### ISSUE TITLE
Evaluate / Enable link time optimization

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3895]
https://stackoverflow.com/questions/31355692/cmake-support-for-gccs-link-time-optimization-lto

**Comment by hroest** [comment]
so basically add this to our Cmake?

```
cmake_minimum_required(VERSION 3.9.4)

include(CheckIPOSupported)
check_ipo_supported(RESULT supported OUTPUT error)

add_executable(example Example.cpp)

if( supported )
    message(STATUS "IPO / LTO enabled")
    set_property(TARGET example PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
else()
    message(STATUS "IPO / LTO not supported: <${error}>")
endif()
```

seems simple enough. Any idea how that impacts build time and disk space?

- Link Time Optimization (LTO) gives GCC the capability of dumping its internal representation (GIMPLE) to disk, so that all the different compilation units that make up a single executable can be optimized as a single module. This expands the scope of inter-procedural optimizations to encompass the whole program (or, rather, everything that is visible at link time). 
- https://gcc.gnu.org/wiki/LinkTimeOptimization#Using_LTO

this seems like a pretty involved process, so it may not be ideal to enable it by default.
