### ISSUE TITLE
FeatureFinderMultiplex detects feature pairs twice

### ISSUE THREAD

**Issue by enetz** [OpenMS/OpenMS#3936]
test workflow with mzML, ini and my result files:
[doublebox.zip](https://github.com/OpenMS/OpenMS/files/2787247/doublebox.zip)

this is how it looks like for me:
![doubleboxes](https://user-images.githubusercontent.com/15832022/51607086-f9f60380-1f13-11e9-8190-aafb2aad1c53.png)

**Comment by enetz** [comment]
These double-pairs are found at many locations across a much bigger map, so it is not a local effect.

**Comment by timosachsenberg** [comment]
@cbielow do you think this is mainly a misassignment of monoisotopic peak or something different (e.g. deamidation)

**Comment by cbielow** [comment]
the isotope profiles of light vs. heavy don't really match well. According to averagine, the light partner looks as expected, but the heavy partner has a weird peak in front.
Deamidation increases mass by ~+1, so that does not explain it (unless light is fully deamidated and heavy to a lesser degree -- highly unlikely I guess).
What kind of data is this? Could be another modification... or an artifact of labeling?

**Comment by enetz** [comment]
@cbielow this is a cross-linking MS dataset with a labeled linker. So each feature are two unlabeled peptides linked by a ligher or heavier linker.

**Comment by cbielow** [comment]
> s a cross-linking MS dataset
I should have known :)

mhh.. is the heavy linker good quality (i.e. all heavy?). Because if not, then some of the supposedly haevy atoms will be light (-1 Da), leading to the picture we are observing. ITRAQ&Co have the same problem, although more severe since it lead to channel carryover. Not the case here since the spacing is large, but its still a bias in quantification since you basically underestimating the heavy partner when ignoring the -1 bleed.

**Comment by enetz** [comment]
I am using the FeatureFinder in this case to connect pairs of MS2 spectra. The MS2 spectra from the lighter feature should be paired with MS2 spectra from the heavier feature. So, although quantification will be important at some point, my current issue here is that I will process the pairs twice in this case, because I have two consensus features linking the same MS2 spectra.

**Comment by enetz** [comment]
@lars20070 @cbielow  it is deuterium labeling (12 hydrogen replaced by 12 deuterium), which has the possibility to exchange with the hydrogen in water. I can't find any specific data on the purity of this labeled cross-linker, but 95% does not seem to be far off for the 12d species. There is probably around 4% 11d and 1% 10d mixed in.

**Comment by lars20070** [comment]
@enetz Just FYI. If you switch on [this flag](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/MultiplexFilteringCentroided.cpp#L42) you get additional debug output (the filter results as `consensusXML`).

**Comment by lars20070** [comment]
See blue dots here. Where does your feature start? 616.11 or 616.36?
![screenshot from 2019-01-24 15-22-55](https://user-images.githubusercontent.com/6149805/51684261-f33abf80-1feb-11e9-806f-997bf82eca9a.png)

**Comment by lars20070** [comment]
As discussed with @enetz on the phone, light at `616.36` and heavy at `619.3` might be the correct answer here. But in this case, the mass shift needs to be changed.

`rt_band` should be of the order of the RT shift i.e. here 7 sec.

**Comment by lars20070** [comment]
@enetz Can/should we close this issue? Anything for me to fix?
