### ISSUE TITLE
Missing charge annotation if annotation was generated in TOPPView Identification view

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#3970]
In IdentificationView:
If a PeptideHit has empty peak annotations, the annotations are generated based on the sequence. Clicking on "show" in PeakAnnotations column displays missing charge information.

![image](https://user-images.githubusercontent.com/5803621/52725937-6d8aae00-2fb2-11e9-95cf-35f0001700d6.png)

**Comment by timosachsenberg** [comment]
@enetz if you find time would be great if you could take a look at that

**Comment by enetz** [comment]
@timosachsenberg I think I at least identified where to look for the problem:

`TOPPViewIdentificationViewBehavior::addTheoreticalSpectrumLayer_` generates the Theoretical Spectrum and the graphical peak annotations directly.
Then `LayerData::updatePeptideHitAnnotations_` parses the text and turns it into `PeptideHit::PeakAnnotation`.
There is probably a disconnect between these two, `updatePeptideHitAnnotations_` may be confused by the second line of the text label, which we usually don't have for OpenPepXL or RNPxl annotations?
The charge is here in the middle of the string, followed by a newline and more text.

I will try to figure out what exactly the parsing does in this case and why it doesn't work.

**Comment by enetz** [comment]
@timosachsenberg 
the used RegExp to find the position of the charge in the text label is this: `([\\+|\\-]\\d+)$`
This looks for something like a +3 or -2 at the end. Otherwise the function just counts the `+` or `-` signs at the end of the string. Both only work for a charge at the end of the label text.
I will try to split by a newline before doing that. That should cover this specific case.
