### ISSUE TITLE
IDPosteriorErrorProbability crashes on OMSSA data

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4022]
Hi,
I use IDPosteriorErrorProbability after OMSSA but it crashes with the next message:

terminate called after throwing an instance of  'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::domain_error> >'
  what():  Error in function boost::math::normal_distribution<double>::normal_distribution: Scale parameter is -nan, but must be > 0 !
Aborted (core dumped)

As I understand the tool didn't manage to obtain the scale parameter, but why can this be ? Is there anything to be done to avoide thes problem ?

**Comment by jpfeuffer** [comment]
Hi @mash23 

This can happen when your score distributions have unexpected shapes. This _can_ come from suboptimal search engine (OMSSA) settings. Especially the precursor tolerance affects the score distributions. If you can upload the idXML I can have a look at the scores.

Other options are:
- Using another search engine
- Using another tool to generate probabilities from scores (this would be PercolatorAdapter)

**Comment by mash23** [comment]
Hi @jpfeuffer , thank you for your response!
Here is the OMSSA's output (it doesn't accept the idXML itself, so I had to zip it..) : 

[oms.zip](https://github.com/OpenMS/OpenMS/files/3012977/oms.zip)

**Comment by hendrikweisser** [comment]
See also #3991.

**Comment by jpfeuffer** [comment]
After looking at the distribution it seems like you have quite bad scores. I think there should be at least some scores on the right side of the plot.
Did you use the correct database for searching? How much of the database do you expect to be in your sample?

![Bildschirmfoto 2019-03-28 um 12 24 19](https://user-images.githubusercontent.com/8102638/55154183-7398b080-5154-11e9-95b6-ebd98c893bfe.png)

**Comment by mash23** [comment]
I took two defferent experiments from PRIDE archive: 
https://www.ebi.ac.uk/pride/archive/projects/PXD005272
https://www.ebi.ac.uk/pride/archive/projects/PXD000036

For the first project I was expecting to see Myosin-II, and in the second - Albuminome. 
To create a database I downloaded human proteome from Uniprot, applied DecoyDatabase from the OpenMS and at the end I used makeblastdb to create a .psq file as OMSSA required it. 
I also ran XTandem for the albuminome project and it worked good, here is the result:
[ALBU_tandem.zip](https://github.com/OpenMS/OpenMS/files/3017822/ALBU_tandem.zip)

**Comment by jpfeuffer** [comment]
Hmm but it seems like the first Project PXD005272 is a SILAC labelled experiment.
You need to include SILAC modifications as possible variable modifications in your search engine.

The second looks like an unlabelled experiment. So that should be ok. I think here you need to enable the option in IDPosteriorErrorProbability "top_hits_only". since OMSSA often reports many matches for one spectrum from which all but the first ones are very bad.

**Comment by hroest** [comment]
Also our error message is not really that helpful and we should improve
that and not throw an Exception here

**Comment by jpfeuffer** [comment]
True, it actually has some checking mechanisms for bad fits, but apparently the parameters of the curves are not checked for NaNs.

**Comment by Arthfael** [comment]
Similar problem here while testing an X!Tandem-only workflow on a co-IP run - sadly for other reasons I have to use this engine. Due to the low sample complexity we would expect a poorer distribution fit, could this be the problem? In addition, X!Tandem seems to be different than other search engines in that it provides non-tryptic identifications, could this mean that non-real values in the scores vector are disruption the node's workings here?
For now I will be using PercolatorAdapter instead.

**Comment by jpfeuffer** [comment]
There were some additions to IDPEP that allow for outlier removal, however I always suggest to look at the gnuplot output and double check. Then adjust search engine settings. In the worst case, switch the search engine or use Percolator.
