### ISSUE TITLE
CompNovoCID write_ini test takes over a minute

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#4072]
In debug mode. Therefore the test timeouts on our build machines.
This should be impossible for simply writing the ini file, there has to be something wrong.
The same happens for CompNovo itself and I think also ConsensusID but less pronounced.
I do not have admin rights on the build machines, so I can't do performance analysis. Someone with windows has to check this. @cbielow ? You like to play around with Perf anyway right? Maybe you could have a short look next time you are in a Debug build.

**Comment by cbielow** [comment]
The is an updateMembers_() which takes way to long because isotope distributions are calculated each and every time.
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/ANALYSIS/DENOVO/CompNovoIdentificationBase.cpp#L754
If this line is removed, the time drops from 43sec to 7sec. Still quite long, but a drastic improvement.
Its not totally obvious how to get rid of it, because the distributions which are precalculated depend on other parameters (max_isotope_ and max_mz_) which are only known at this point.

**Comment by cbielow** [comment]
has it always been this slow or is that a recent regression in computing isotope profiles or alike?

**Comment by jpfeuffer** [comment]
Aah no it was not necessarily always this long. So this is probably the reason.

**Comment by jpfeuffer** [comment]
But once the members are updated from the ini, they are stored in the class. Why can't the init method be called first when it is needed. And can't the state be cached?
Like this: When members are updated, you set a "dirty" flag. And when the isotopes are needed, the "dirty" flag is read and the init method is called again only if needed.

**Comment by cbielow** [comment]
in theory yes, but this is the base class and derived classes can just access the member. So you'd need to make the isotope distribution private and only allow access via a protected method which checks the dirty-flag first.

**Comment by timosachsenberg** [comment]
@hroest recently changed precalculation of isotope distributions I think. Do you know if this is related to that change?

**Comment by hroest** [comment]
not sure that was me, I worked on the fine isotope distribution - did
you mean that?

**Comment by timosachsenberg** [comment]
hmm it's coarse... shouldn't take that long to generate 4000 isotope patterns
