### ISSUE TITLE
How does the ConsensusID work ?

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4173]
Hi everyone,
Could somebody explain to me how the tool actually works, particularly the PEPMatrix algorithm?
I have read this article: https://www.ncbi.nlm.nih.gov/pubmed/21644507, but I still have a few questions left.
Why was the Needleman-Wunsch algorithm chosen for comparing peptide sequences and not for example Smith-Waterman or some other?
How is the alignment of peptides in which modifications were found presented, like this one _(Acetyl)TLEEM(Oxidation)ELR_?
Where did the formulas for calculating the consensus value come from?
Can I find somewhere the exact PAM30MS matrix? And how exactly is it adapted to the I/L and Q/K ambiguity?

**Comment by jpfeuffer** [comment]
Hi!
Since I am not the author of the algorithm, I will tell you what I see from the code and what I think:
- I think you want to penalize sequences of different lengths, therefore global alignment with NW.
- Modifications are ignored/removed before calculating similarity
- the matrix is here: https://github.com/OpenMS/OpenMS/blob/5a70018d9e03ce32e64fcbb1c985b7a1256efc7a/src/openms/include/OpenMS/ANALYSIS/ID/ConsensusIDAlgorithmPEPMatrix.h#L58

HTH

**Comment by hendrikweisser** [comment]
Questions have been answered, so I'm closing this.

**Comment by mash23** [comment]
Hi again, 
Still I have some questions. 
In this article: [](https://www.ncbi.nlm.nih.gov/pubmed/21644507) there is an example of how does the consensusID work (Figure 1. page 3334). The example seems to be clear but what if there were more than one peptides in the list of X!Tandem ?

**Comment by jpfeuffer** [comment]
Hi,
what exactly is unclear? The results are shown for every sequence occurring in any of the three search engine. If a sequence is missing in one of the search engines, the score of the one with the highest similarity is taken for the formula.

**Comment by mash23** [comment]
But do I need to compare hits that were assigned to the same identification in the same engine?

**Comment by jpfeuffer** [comment]
I think you look at the union of all possible sequences from all search engines that could explain this spectrum. Then you calculate a score for each of them. For this you need to look if this sequence was found in a search engine. If so, you take the score with a full weight. If not, you use the score from the most similar sequence for that search engine and weigh it by the similarity.

**Comment by mash23** [comment]
Still it's not clear for me..
Say I have three engines. For each of them the result of peptide seasch gives me a number of PeptideIdentification each containing several hits. So the consensus keeps all of these hits from all of engines? It doesn't remove any of them, it just specifies the scores using the results of all three engines ?
So for each of peptide identifications in the resulting consensus file I would have hits from all search engines but with modified scores ?

**Comment by jpfeuffer** [comment]
Yes almost.
Example:

- Mascot:
  PepID (=spectrum) mz=100, rt=200:
    - PepHit DFPANGER score = 0.8
    - PepHit GIRAFFER score = 0.81
- XTandem:
  PepID (=spectrum) mz=100, rt=200:
    - PepHit AALGER score = 0.7
    - PepHit GLRAFFER score = 0.75

  PepID (=spectrum) mz=100, rt=300:
    - PepHit GRAGRAR score = 0.86
- MSGF:
  PepID (=spectrum) mz=100, rt=200:
    - PepHit GIRAFFER score = 0.7

Possible result (I didnt use the exact formula)
- ConsensusID:
  PepID (=spectrum) mz=100, rt=200:
    - PepHit GIRAFFER score = 0.67
    - PepHit GLRAFFER score = 0.67
    - PepHit AALGER score = 0.7
    - PepHit DFPANGER score = 0.8

  PepID (=spectrum) mz=100, rt=300:
    - PepHit GRAGRAR score = 0.86

Note that GIRAFFER and GLRAFFER got a better score now and are on rank 1 since they have a similarity of 1 and were found in all search engines, while the others were not rescored because I assume their similarity to the other Hits is so low that it is has a similarity score of 0. Unless you specify a minimal coverage of search engines (e.g. 2 out of 3) with a parameter, I don't think that a Hit is removed. They are just "merged" and their scores updated.

**Comment by mash23** [comment]
Ok, thank you. 
And what obout the total amount of PepIDs in different engines ? I mean if Mascot has 10 000, XTandem - 5000 and MSGF - 7000. What will be with PepIDs that are presented only in one of engines ? 
As I understand there can be some differences in mz and rt values between engines and I think Consensus has to use some kind of machine epsilon hasn't it ? But still there may remain some PepIDs that were not taken into account.

**Comment by jpfeuffer** [comment]
Yes true, currently we have no mechanism to match the spectra by their vendor ID, so we match them by a mz and RT threshold (and yes it compensates for reporting differences in the search engines). This threshold defines how many combined PeptideIDs you will have in the end. For spectra that have no matching spectra in the other search engines, I think they are by default just taken over without a consensus scoring. So for your example I assume it would be a bit more than the maximum 10,000. Maybe the others found something matching to a spectrum, where Mascot did not.

**Comment by mash23** [comment]
Oh, ok than. 
And what PepID will be written to the Consensus result ? 
For example if I have:

Mascot
PepID (=spectrum) mz=100, rt=200
XTandem
PepID (=spectrum) mz=100, rt=199.99
MSGF
PepID (=spectrum) mz=100, rt=200.01

They are very close and after there hits are compared the resulting hits are to be written with some mz and rt. So which PepID will be taken as the result ? Any of my choose ?

**Comment by jpfeuffer** [comment]
Ah I understand. I think it will be the median or mean of those values. I need to check.

**Comment by mash23** [comment]
Hm.. Ok thank you ! 
It's much clearer to me now.

**Comment by jpfeuffer** [comment]
You are welcome. I am closing it for now. Feel free to reopen if you have another question about this.
