### ISSUE TITLE
schema location in CTD files does not exist

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4174]
Currently it is: `xsi:noNamespaceSchemaLocation="http://open-ms.sourceforge.net/schemas/Param_1_6_2.xsd"`

Also some tags that are used in the generated ctd files don't exist in the schema file, e.g., tool. 

Last but not least a question: where in the ctd files is the actual program/binary encoded that is supposed to be called?

**Comment by jpfeuffer** [comment]
Hi!

I think this is fixed in more recent versions (e.g. nightlies)
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/ParamXMLFile.cpp#L92
I also fixed our CTD schema quickly, so it matches upstream https://github.com/OpenMS/OpenMS/commit/c29851d584519d3f99f25e75cc1a73dad2b307dc

Concerning the "tool" element, it should be here:
https://github.com/WorkflowConversion/CTDSchema/blob/master/CTD.xsd#L6
Or did you mean something else? Remember there is the parent schema CTD and it includes a section about its parameters which is defined in the ParamXML schema.

Concerning the program/binary: By default we use the "name" element but you can override the actual executable name and path with the "executableName" and "executablePath" elements.

**Comment by bernt-matthias** [comment]
Thanks for the information. In this case shouldn't the ctd files refer to 

https://github.com/WorkflowConversion/CTDSchema/blob/master/CTD.xsd

?

**Comment by jpfeuffer** [comment]
Yes I dont know what is best. We will always ship the schema that we currently support such that our Validators can validate the schemata offline, so we went for our "local" copy.

**Comment by jpfeuffer** [comment]
I will close it for now. I think it is reasonable to keep a copy of the currently supported schema. Please reopen if you have any issues after the upcoming release (where it should be fixed)
