### ISSUE TITLE
introduce constant for native id prefix set in OpenMS

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#4195]
E.g.: in FileMerger, we write native ids as:
spec_it->setNativeID("spectrum=" + String(native_id));

XTandemAdapter annotates "index="
MSGFPlusAdapter annotates "scan="
in the ID data structure.

I think it would be good to be more consistent.

**Comment by jpfeuffer** [comment]
Feel free to Add it to the list in my pinned issue.

**Comment by oliveralka** [comment]
Is that a search engine issue, or related to the structure of the vendor nativeID?

Maybe the nativeID should just be the string referring to the vendors nativeID (instead of setting "spectrum=;index=;..."), or? 

Please see:
https://github.com/HUPO-PSI/mzTab/blob/master/specification_document-releases/2_0-Metabolomics-Release/mzTab_format_specification_2_0-M_release.adoc#51-use-of-identifiers-for-input-spectra-to-a-search

**Comment by timosachsenberg** [comment]
yes for the search engines I agree but seems the thirdparty tools don't provide all annotations and we need to reassign the native id.
Also that doesn't work if you merge files using FileMerger as native ids might get duplicated
