### ISSUE TITLE
command line for itemlists

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4196]
Just to be sure how are the items of an itemlist specified on the command line. Are they comma or space separated? 

For instance:

```
<ITEMLIST name="ms_levels" type="int" description="Merge spectra of this level. All spectra with other MS levels remain untouched." required="false" advanced="false" restrictions="1:">
  <LISTITEM value="1"/>
</ITEMLIST>
```

Would it be `-ms_level 1 2 3` or `-ms_level 1,2,3`?

**Comment by cbielow** [comment]
correct is `-ms_level 1 2 3`, i.e. separate command line arguments.
All our lists are handled like that. One of the reasons are input/output filenames which potentially contain spaces, so you can easily quote them. `MyTOPPTool -in "file 1.txt" "file 2.txt" ...`

**Comment by bernt-matthias** [comment]
Wonderful. Thanks.

**Comment by jpfeuffer** [comment]
Since I know you are working on a CTDConverter, it might be worth adding that for CTD in general you can use the isList attribute to trigger a slightly different behaviour.
https://github.com/WorkflowConversion/CTDSchema/blob/master/CTD.xsd#L130

If this is active, the tool assumes a repetition of the parameter per list argument. E.g. -in a.txt -in b.txt
I think seqan uses this.

**Comment by bernt-matthias** [comment]
Thanks @jpfeuffer. Is there somewhere an example of a ctd using this?

**Comment by jpfeuffer** [comment]
https://gist.github.com/jpfeuffer/00b97dc08af9a5051718ae920b8428d9

**Comment by jpfeuffer** [comment]
Hmm sorry. Has a weird structure since it was copied from the browser.

**Comment by bernt-matthias** [comment]
Thank. Got it. At the moment openms (ie 2.4) does not use `clielement`. I have seen this in seqan -- lets see if I find the time to adapt it, seqan is definitely on the todo list, but my prmary interest are the openms wrappers.
