### ISSUE TITLE
IDFileconverter - mzID no start/end found

### ISSUE THREAD

**Issue by aalvarezf** [OpenMS/OpenMS#4226]

**Comment by aalvarezf** [comment]
Hi,
Sorry if this question is very naive, quite new in the field.

I'm using IDFileConverter to convert Percolator psms output to mzid after MSGFplus to search.
The tool does not find end or start position of peptide hit in protein sequence for any instance
Any idea about what is happening? Maybe is obvious but I didn't find this output reported.

**running:** 
IDFileConverter -in PERCOLATORFILE.psms -out OUT.mzid  -score_type qvalue -mz_file FILE.mzML 

**output:**
Progress of 'Loading...':
  Progress of 'loading spectra list':
    97.65 %               
  -- done [took 26.90 s (CPU), 26.89 s (Wall)] -- 
  Progress of 'loading chromatogram list':
  -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
Created 48785 protein hits.
Created 52196 peptide hits (PSMs).
-- done [took 29.30 s (CPU), 29.35 s (Wall)] -- 
Progress of 'Storing...':
Found no start position of peptide hit in protein sequence.
Found no end position of peptide hit in protein sequence.
-- done [took 4.54 s (CPU), 5.47 s (Wall)] -- 
IDFileConverter took 34.91 s (wall), 33.93 s (CPU), 0.66 s (system), 33.27 s (user).
<Found no end position of peptide hit in protein sequence.> occurred 112109 times
<Found no start position of peptide hit in protein sequence.> occurred 112109 times

**Comment by jpfeuffer** [comment]
Hi,

I don't think this is supported by our Percolator file reader, yet.
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/PercolatorOutfile.cpp#L309
It only reads the protein accessions.
Is this information available in the ".psms" file at all?

In general this should not be a fatal error (is it?) but could lead to problems in future steps of a pipeline.

You could try to convert to the OpenMS-internal idXML format first, then run PeptideIndexer on this file together with the fasta database (to annotate the positions) and lastly try to export it to mzid again. But check the output carefully to make sure no information was lost on the way.

If you have the option and want to postprocess with OpenMS, I would however suggest to use our adapters as much as possible (e.g. MSGFPlusAdapter and PercolatorAdapter) since they take care of most of these conversion issues.

**Comment by aalvarezf** [comment]
Hi, 

Thanks for your answer!

I tried the first solution, and as you suggest, some information was lost in the final mzid.

Then I tried the same flow with all the OpenMS adapters. I've been reading some issues to find the correct parameters, but since using PercolatorAdaptor seems to me not straightforward... could you please tell me if this workflow is correct?

**MSGFPlusAdapter** (addFeatures:true)  -> **PeptideIndexer** -> **PSMFeatureExtractor** -> **PercolatorAdapter** (-peptide-level-fdrs:fasle  -protein-level-fdrs:false)    
->  **FidoAdapter**  (with all psms, no filtering previous file)-> **IdFilter** (default) -> **FalseDiscoveryRate**   (-PSM:true and -protein:true)

The data are several TMT10plex batches.
