### ISSUE TITLE
FalseDiscovery after Percolator does not work anymore

### ISSUE THREAD

**Issue by thommohr** [OpenMS/OpenMS#4227]
Dear Colleagues,

because of the MSStats adapter throwing the file UNKOWN error, we updated to the nightly openms build as suggested here: #3683.

However, now a new problem arises. Our workflow is as follows:

MSGFPlus -> PeptideIndexer -> PSMExtractor -> Percolator -> FDR ->

Now the FDR node throws an error that it has not enough information to calculate a protein level FDR and things the proteins have not been identified. With 2.4.0 it worked.

What are we doing wrong ?

best,
Thomas

**Comment by jpfeuffer** [comment]
Hi Thomas,

hmm maybe the (new) error is not so wrong. The FDR node in the end seems to be a bit counter-productive, since Percolator already reports q-values per default. A simple IDFilter on the (q-value) score would be sufficient I assume.
And remember, if you want meaningful protein FDRs you need to run Percolator with protein-level-fdrs enabled and give it the fasta file and correct enzyme (trypsin/p probably for MSGF+). Or run a separate inference tool (FidoAdapter, EPIFANY). Otherwise the proteins all have an undefined score.
Additionally, there were some serious fixes for protein handling in PercolatorAdapter since 2.4 (although this should result in more information, not less ;) )

I hope this helps you to continue.

Cheers
Julianus

**Comment by thommohr** [comment]
Hi Julianus, thanks for the quick reply ! 

It makes sense. However, we have seen FDR nodes following Percolator in quite a few (published) workflows..... In fact, this is why we inroduced it in the first place. is there any explanation, maybe to my e-mail in order not to overload the list ?

best, and thanks for the good work that OpenMS is !
Thomas

**Comment by jpfeuffer** [comment]
Hi, 

no problem.
I can understand that the interplay of different tools might be a bit confusing. I couldn't find your e-mail but it is no problem to answer it for the public.

The only reason I currently see, why an FDR calculation _right after_ PercolatorAdapter would make sense is when you set the score_type in the PercolatorAdapter to "pep" or "svm" and you want to use the slightly different FDR approach of OpenMS instead of Percolator's.
But: If you have tools in-between, there are many reasons why a re-calculation of the FDR might make sense (filtering, inference, ...).

**Comment by thommohr** [comment]
Hi Julianus,

makes sense. I updated to the trunk version in KNIME, replaced the FDR with an IDFilter and now it works.
Thanks very much !!
