### ISSUE TITLE
What is the difference between proteins and protein groups ?

### ISSUE THREAD

**Issue by mash23** [OpenMS/OpenMS#4228]

**Comment by jpfeuffer** [comment]
Hi!

Protein groups are just groups of (single) proteins that share peptides:
- proteins in "indistinguishable protein groups" share ALL their observed peptides. This can be used to make peptides unique per group (since you could not distinguish between the members anyway).
- proteins in "protein groups" share peptides in a way such that they are all "connected" (rarely used in practice and is more a theoretical concept)
