### ISSUE TITLE
Proteinquantification fails with protein group quantified that is not present in inference data

### ISSUE THREAD

**Issue by thommohr** [OpenMS/OpenMS#4232]
Dear all,

after upgrading to the trunk, we ProteinQuantifier fails with the error message above ...

Our workflow is essentially:

MSGFPlus -> Prcolator -> IDFilter -> FeatureFinderIdentification -> MapAlignerIdentification (or MapAlignerPoseClustering) -> FeatureLinkerUnlabaledKD -> ConsensusMapNormalizer -> ProteinQuantifier (as described bei Weisser et. al.)

Any ideas ? THanks a lot !
best,
Thomas

**Comment by jpfeuffer** [comment]
Hi Thomas!

are you running Percolator with "protein-level-fdrs" activated/"true"?
We just recently added support for the reading of protein groups from Percolator, so I think the original paper was with FidoAdapter for inference (if I am not mistaken).
It might well be that the message occurs because there are just no groups present.

You can also quantify without inferred groups (by not passing the optional ID file to the ProteinQuantifier) but you might lose some peptides that are unique to a specific group.

**Comment by hendrikweisser** [comment]
Any updates here? If the problem has been solved, can we close the ticket?
