### ISSUE TITLE
ProteomicsLFQ tool - Experimental design input

### ISSUE THREAD

**Issue by MiguelCos** [OpenMS/OpenMS#4308]
Hello!

I am planning to start testing the ProteomicsLFQ tool soon and I am curious about the required structure of the design file. 

I found this one [here](https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/examples/BSA/experimental_design.tsv) in the examples but I am not quite sure if this is right because of the redundant (?) information in the 4 final rows. 

Many thanks in advance, I am really looking forward to using this new tool.

**Comment by jpfeuffer** [comment]
Hi Miguel!

Great. We are very happy that people are interested in the tool already. Let me try to help you:
Yes, our experimental design file currently has two sections:
- The File section where there should be one entry per mzML file in your experiment
- and the Sample section, in case your Sample was distributed over multiple files (this can happen in TMT/iTRAQ experiments which we wanted to support as well). This sections also holds information for potential statistical downstream processing with MSStats.

In the case of the example the Sample section is indeed redundant since it is neither a TMT/iTRAQ experiment, nor did it contain replicates such that multiple samples would belong to the same condition for example.

For now I think the Sample section is nonetheless mandatory. 
@timosachsenberg however created a python script for now to quickly create such redundant information in case you have a trivial experimental design.
https://gist.github.com/jpfeuffer/6f591992357bee36d7559c0a57ea27da

Give it a try and modify it afterwards if it does not fit your needs.

**Comment by jpfeuffer** [comment]
Please also see #4558 . We will improve the docu on the experimental design file
