### ISSUE TITLE
TICCalculator: wrong results when running multi-threaded

### ISSUE THREAD

**Issue by elrubio** [OpenMS/OpenMS#4389]
## Context

- OpenMS Version: 2.4.0 Oct 29 2018, 15:59:05, Revision: 9690d06
- Windows 10
- Binary Installer

## Issue

`TICCalculator` returns wrong numbers for *number of peaks* and *total ion current* (TIC) when being called with `-read_method index_parallel -threads N` with N>1. 

Compare:

Numbers are correct when using e.g. `regular` method or `-threads 1`:

```
> TICCalculator -in QX20180816-01.mzML -read_method regular
Read method: regular
[..]
There are 39240 spectra and 23693271 peaks in the input file.
The total ion current is 1.42115e+12
[..]

> TICCalculator -in QX20180816-01.mzML -read_method indexed_parallel -threads 1
[..]
Read method: indexed (parallel)
There are 39240 spectra and 23693271 peaks in the input file.
The total ion current is 1.42115e+12
[..]
```

Numbers are wrong when using `indexed_parallel` method and multiple threads:

```
> TICCalculator -in QX20180816-01.mzML -read_method indexed_parallel -threads 2
[..]
Read method: indexed (parallel)
There are 39240 spectra and 14760886 peaks in the input file.
The total ion current is 1.1904e+12
[..]

> TICCalculator -in QX20180816-01.mzML -read_method indexed_parallel -threads 3
[..]
Read method: indexed (parallel)
There are 39240 spectra and 13019297 peaks in the input file.
The total ion current is 1.12768e+12
[..]

> TICCalculator -in QX20180816-01.mzML -read_method indexed_parallel -threads 4
[..]
Read method: indexed (parallel)
There are 39240 spectra and 11272790 peaks in the input file.
The total ion current is 1.07903e+12
[..]
```

### Observations
- Resulting numbers decrease with increasing numbers of threads
- Numbers seem to be stable for the same number of threads (tested with 10 iterations)

**Comment by cbielow** [comment]
thanks for reporting this!
can confirm on VS2015 using OpenMS 2.5 develop

**Comment by cbielow** [comment]
to follow up on this:
I've been unable to generate a minimal example outside of OpenMS, but looking at the assembly (which I barely understand), this code is generated by VS2015 for the critical section
```
; 48   : #pragma omp critical

  001ac	48 8d 0d 00 00
	00 00		 lea	 rcx, OFFSET FLAT:$vcomp$critsect$
  001b3	e8 00 00 00 00	 call	 _vcomp_enter_critsect

; 49   :     {
; 50   :       //std::cout << i << " " << nr_peaks_l << "\n";
; 51   :       TIC = TIC + TIC_l;

  001b8	f2 0f 58 fe	 addsd	 xmm7, xmm6

; 52   :       nr_peaks = nr_peaks + nr_peaks_l;

  001bc	03 f3		 add	 esi, ebx

; 36   :   for (SignedSize i = 0; i < nr_spec; i++)

  001be	48 8b 0d 00 00
	00 00		 mov	 rcx, QWORD PTR $vcomp$critsect$
  001c5	e8 00 00 00 00	 call	 _vcomp_leave_critsect
```

So, within the criticial section, only register operations are performed. To my understanding, this is not thread-safe, since there is not load/store to memory, i.e. benefit from a memory fence.

In contrast, a working version does this (shortened)
```
  001ef	f2 0f 58 75 00	 addsd	 xmm6, QWORD PTR [rbp]
  001f4	f2 0f 11 75 00	 movsd	 QWORD PTR [rbp], xmm6

; 52   :       nr_peaks = nr_peaks + nr_peaks_l;

  001f9	01 1e		 add	 DWORD PTR [rsi], ebx
```

I will try to reproduce using the latest VS2019 and file a bug report with MS-dev.

**Comment by cbielow** [comment]
Results for VS2019 are in: no bug :joy:
assembly looks like this and should be fine:
```
; 46   : 
; 47   : #pragma omp critical
; 48   :     {
; 49   :       TIC = TIC + TIC_l;

  00211	f2 41 0f 58 75
	00		 addsd	 xmm6, QWORD PTR [r13]
  00217	f2 41 0f 11 75
	00		 movsd	 QWORD PTR [r13], xmm6

; 50   :       nr_peaks = nr_peaks + nr_peaks_l;

  0021d	41 01 3c 24	 add	 DWORD PTR [r12], edi

; 45   :     }

  00221	48 8b 0d 00 00
	00 00		 mov	 rcx, QWORD PTR $vcomp$critsect$
  00228	e8 00 00 00 00	 call	 _vcomp_leave_critsect
```

**Comment by jpfeuffer** [comment]
Ok nice. Should we switch the binaries to 2019 then? And should we document this pretty big bug in the instructions then?

**Comment by cbielow** [comment]
yes, definitely.

I have filed a report with MS-dev https://developercommunity.visualstudio.com/content/problem/856143/c-openmp-omp-in-vs2015-and-2017-broken.html
Lets see ...

**Comment by cbielow** [comment]
Ok, so the VS-developers somewhat confirm that the bug is fixed in VS2019, but will not be fixed and backported in earlier versions.
Thus, we recommend VS2019 from now on, or running executables compiled with older VS's only using a single-thread to avoid wrong behaviour.
VS2019 also has the added benefit of compiling much faster and producing faster code (at least for File I/O - see  #4445).
