### ISSUE TITLE
LuciphorAdapter extension 

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4444]
The file specified by `-in ` seems to require the extension mzML. Just mzml seems not to work. Would be nice if the Adapter would take care of it. 

Furthermore I guess that the recently added test maybe wrong. The jar file seems to search in SPECTRUM_PATH (see generated template) for mzML files. The path is the directory containing the mzML file given by -id. In the case of the test this is the directory containing the test data, which contains many more mzML files.

**Comment by oliveralka** [comment]
> The file specified by -in seems to require the extension mzML. Just mzml seems not to work. Would be nice if the Adapter would take care of it.

I' am not sure what the best way would be to do this since LuciPhor will not work with files named ".mzml", which means you would have to actively rename the files on the filesystem. Do you have a suggestion here? 

> Furthermore I guess that the recently added test maybe wrong. The jar file seems to search in SPECTRUM_PATH (see generated template) for mzML files. The path is the directory containing the mzML file given by -id. In the case of the test, this is the directory containing the test data, which contains many more mzML files.

The SPECTRUM_PATH always points to the parent directory with one or multiple files. Using only one of these should work fine, as far as I know - LuciPhor2 should use the .mzML referenced in the .pepXML file. 

Unfortunately, while testing it seems to be incompatible with higher java versions - tested: Java8 (works), Java13 (not working). This seems to be related to missing module/dependency handling needed for higher versions. I will let the developer know since this could lead to incompatibility in the future.

**Comment by bernt-matthias** [comment]
Regarding mzML .. since mzML is the extension used throughout OpenMS  (except for NovorAdapter) it should be left as it is. 

The SPECTRUM_PATH problem seemed to be a temporary problem on my side. Seems to run now. 

So, I will close this issue.
