### ISSUE TITLE
Linux build issue with finding boost references

### ISSUE THREAD

**Issue by abisarvepalli** [OpenMS/OpenMS#4500]
I have mapped the dependent libraries to build openms via:
[CMakeCache.txt](https://github.com/OpenMS/OpenMS/files/4100693/CMakeCache.txt)

When I attempt to build the FeatureFinderMetabo module (pulled from the latest commit from master), I am able to build the openms library but have an issue with linking the executable.

OpenMS build setup with 
```cmake -DOPENMS_CONTRIB_LIBS=~/openms/contrib-build -DBOOST_USE_STATIC=OFF -DWITH_GUI=OFF -DCMAKE_PREFIX_PATH="/data/beta-proteomics2/tools/openms-build/conda;/Users/asarvepa/openms/contrib-build" ~/openms/openms-2.4```

<img width="948" alt="Screen Shot 2020-01-22 at 4 59 19 PM" src="https://user-images.githubusercontent.com/7587923/72953021-9847bf80-3d48-11ea-8d2a-c3d14875af06.png">

**Comment by jpfeuffer** [comment]
Hi. Does this mean you manually changed the CMakeCache?
Did a simple re-run of CMake not work?
Can you remove your CMakeCache and re-run CMake?
Maybe also use the full path to your home instead of "~" (not sure what the policy was here).

**Comment by abisarvepalli** [comment]
The flags were the only keys I changed when building the makefiles

Are you suggesting 
```cmake -DOPENMS_CONTRIB_LIBS=<abs contrib-build path> <abs openms-source path>```

**Comment by jpfeuffer** [comment]
Which OpenMS version do you use? Nightly or 2.4?
Maybe it is #4484

**Comment by jpfeuffer** [comment]
You can also have a look at our conda recipe. We build with conda packages only there.
We added some new defaults for finding boost in the develop version as well.

**Comment by abisarvepalli** [comment]
I'm pulling from the nightly branch

Where is the conda env config wikid?

**Comment by abisarvepalli** [comment]
I followed the recipe and only used the contrib library to download the missing WildMagic5 libraries.

When it came to linking to the libOpenMS.so shared library, I now get this error:
```
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libpthread.so when searching for -lpthread
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
/usr/bin/ld: /data/beta-proteomics2/tools/openms-build/conda/lib/libboost_math_c99.a(erf.o)(.text._ZN5boost4math6detail7erf_impIeNS0_8policies6policyINS3_12domain_errorILNS3_17error_policy_typeE1EEENS3_10pole_errorILS6_1EEENS3_14overflow_errorILS6_1EEENS3_16evaluation_errorILS6_1EEENS3_14rounding_errorILS6_1EEENS3_13promote_floatILb0EEENS3_14promote_doubleILb0EEENS3_14default_policyESK_SK_SK_SK_SK_EEEET_SM_bRKT0_RKN4mpl_4int_ILi53EEE[_ZN5boost4math6detail7erf_impIeNS0_8policies6policyINS3_12domain_errorILNS3_17error_policy_typeE1EEENS3_10pole_errorILS6_1EEENS3_14overflow_errorILS6_1EEENS3_16evaluation_errorILS6_1EEENS3_14rounding_errorILS6_1EEENS3_13promote_floatILb0EEENS3_14promote_doubleILb0EEENS3_14default_policyESK_SK_SK_SK_SK_EEEET_SM_bRKT0_RKN4mpl_4int_ILi53EEE]+0x196): unresolvable H?\$?H?l$?H??L?d$?H??H?GH??I??H??H?;?PxH?EI?tH??PxH?EH?{I?t$H?$H?lL?d$H?@xH????f?H?\$?H?l$?H??L?d$?H??H?GI??H??H???PhI?$H?CH??PhH?$I?DH?lL?d$H??? relocation against symbol `frexpl@@GLIBC_2.2.5'
/usr/bin/ld: BFD version 2.20.51.0.2-5.42.el6 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size
```

The boost version that I am using is 1.70.0

**Comment by jpfeuffer** [comment]
A warning in general: We have built OpenMS for conda in a clean self-contained conda-build environment (https://bioconda.github.io/contributor/build-system.html). Conda libraries are built with relatively new compilers (see their compiler packages). You might need to use compatible ones when compiling the rest of the contrib and openms. And you might need to set correct sysroot paths for the libdl and libm/libc libraries which is not trivial when not using the pre-configured build environments.

Can you clean (i.e. erase) your build folder and try:
`cmake -DOPENMS_CONTRIB_LIBS=/Users/asarvepa/openms/contrib-build -DBOOST_USE_STATIC=OFF -DWITH_GUI=OFF -DCMAKE_PREFIX_PATH="/data/beta-proteomics2/tools/openms-build/conda" /Users/asarvepa/openms/openms-2.4`

If it does not work, I would suggest to just take the recommended route of building everything from contrib (and use Qt from the system or the official installer).
Or if you urgently have to use some libraries from conda, have a look in the above links on how to setup a compatible build environment.

**Comment by abisarvepalli** [comment]
Tried to setup the conda environment using the bioconda recipe, but run into an issue when building .../src/openms/source/MATH/STATISTICS/StatisticFunctions.cpp :
```
#if OPENMS_BOOST_VERSION_MINOR >= 64
```
where the OPENMS_BOOST_VERSION_MINOR pragma does not seem to be satisfied with conda installing boost version 1.70.

**Comment by lfnothias** [comment]
Hi OpenMS community,
I am having the same issue on a similar environment. Anyone would know what could be done to fix this issue ?

**Comment by jpfeuffer** [comment]
Hi!
@abisarvepalli your last comment might hint on CMake finding headers from an old boost version.

In general, let me explain how the CMake find process works:
- We have the OPENMS_CONTRIB_LIBS variable which just adds its entry to the CMAKE_PREFIX_PATH so this path is searched before every other.
- There is the CMAKE_PREFIX_PATH in case you have libraries that you did not build with contrib and that are not in system paths like /usr/lib(64)/
- There are special variables for Boost because it can be built in many ways: BOOST_USE_STATIC tells the finding mechanism to prefer static ".a" libraries instead of dynamic ".so/.dylib". Usually in conda or package managers you will have either just the dynamic one or both. In this case you probably want to set the variable to Off. In the contrib, we default to building boost static. So you want it On.
Since boost 1.69 they additionally changed their naming. So if you want to find boost now, you need an up-to-date CMake and might need to set additional variables like Boost_ARCHITECTURE (this also depends on if you build from contrib or a package manager, I would need to see the naming scheme of the libraries). We added some defaults to our build system to help in this but since multiple errors were reported I have to double check them.
- There may arise problems when you have the same library in the contrib and in system paths, because some libraries' headers unfortunately are not in a separate subfolder (e.g. /usr/include/boost) and therefore pull in all headers from every other system library there is. This might lead to different versions of header includes (.h) and libraries (.so) to be found and is the reason why we recommend only having one version present.

To proceed further, maybe you could both send me (after creating a fresh build folder please):
- your OS and architecture
- the commit/version of OpenMS to be built
- the contents of the contrib-build/lib folder (or what libraries you built from the contrib)
- which libraries you want to use from conda or your package manager.
- your CMake call (preferably with -DBoost_DEBUG=On for some additional output)
- the output of your CMake call
- the generated CMakeCache.txt in the build folder

I hope we will find a solution.

**Comment by jpfeuffer** [comment]
As a small addition:
We are currently updating our conda packages and it works for develop with all packages coming from conda (except the missing wildmagic).
https://github.com/bioconda/bioconda-recipes/pull/19989
Maybe that helps you as well, but again, the builds there are run on a clean conda-build environment with no other potential system libraries to be found.

**Comment by abisarvepalli** [comment]
Determined that the issue was with cmake sourcing the incorrect c/c++ compiler.

I was using a conda distributed of cc and realized that cmake was sourcing the `cc` binary, which in conda is named `x86_64-conda_cos6-linux-gnu-cc`. 

Solution: symlink the `x86_64-conda_cos6-linux-gnu-cc` conda binary as `cc` and having the conda bin directory PATHed should allow cmake to source the proper cc compiler.

```
$ cd <openms-release>/binaries/conda/bin
$ ln -s x86_64-conda_cos6-linux-gnu-cc cc
# ensure that conda binaries are pathed
$ export PATH=${CONDA_ROOT}/bin:${PATH}
```
