### ISSUE TITLE
OpenPepXL: unknown or deprecated parameters 

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4546]
I see messages like `Unknown (or deprecated) Parameter 'in' given in outdated parameter file! Ignoring parameter.` when running 

```
OpenPepXL -test -decoy_string "decoy" -in OpenPepXL_input.mzML -consensus OpenPepXL_input.consensusXML -database OpenPepXL_input.fasta -out_xquestxml OpenPepXL_output.xquest.xml.tmp -out_xquest_specxml OpenPepXL_output.spec.xml.tmp -out_mzIdentML OpenPepXL_output.mzid.tmp -out_idXML OpenPepXL_output.idXML.tmp -debug 3
```

which is odd since I do not use a parameter file. The messages are also there if I use a parameter file generated with `OpenPepXL -write_ctd ./`. Testing currently in 2.5.0.

I'm asking in particular because the output also indicates that the `test` parameter is ignored even if I set it in the parameter file .. which would explain the differences in the output data that I observe in my Galaxy tool tests.

**Comment by enetz** [comment]
I think this happens in the code block at line 231 in `OpenPepXL.cpp`:
```
    OpenPepXLAlgorithm search_algorithm;
    Param this_param = getParam_().copy("", true);
    Param algo_param = search_algorithm.getParameters();
    algo_param.update(this_param, false, OpenMS_Log_debug); // suppress param. update message
    search_algorithm.setParameters(algo_param);
```
`algo_param.update(...)` forwards the parameters to the algorithm class in `OpenPepXLAlgorithm.cpp`. The algorithm class then complains that it doesn't know parameters that are specific to `OpenPepXL.cpp` like `-in` and `-database` or specific to `TOPPBase` like `-test` and `-threads`. This means that these parameters should be correctly handled by `TOPPBase` and `OpenPepXL` and only after that `OpenPepXLAlgorithm` complains about them.

So far I have not figured out why exactly these warnings are returned, and why that only happens in `-test` mode. E.g. this exact way of forwarding parameters is also used in the `PeptideIndexer` and its `PeptideIndexing` algorithm class. But that tool doesn't give these warnings for its `-in` and `-fasta` parameters or the `TOPPBase` parameters.  
This can probably be fixed by using the method that `SimpleSearchEngine` uses to pass parameters to `SimpleSearchEngineAlgorithm`. It defines a prefix for all `SimpleSearchEngineAlgorithm` parameters and then only forwards those paramaters. Although this would change most of the parameter names of OpenPepXL e.g. from `precursor:mass_tolerance` to `search:precursor:mass_tolerance` or something similar.

**Comment by bernt-matthias** [comment]
Just stumbled over this one again and I can add that `PeptideIndexer` also issued the warnings: 

```
Unknown (or deprecated) Parameter 'in' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'fasta' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'out' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'log' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'debug' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'threads' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'no_progress' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'force' given in outdated parameter file! Ignoring parameter. 
Unknown (or deprecated) Parameter 'test' given in outdated parameter file! Ignoring parameter. 
```

**Comment by jpfeuffer** [comment]
Hmm yes, PeptideIndexer has a line with `params.update(..)` as well.
@enetz  What is this line supposed to do? In the docu it says "tries to rescue params from ..". Why would that be needed here?

In any case, shouldn't that only be printed in debug mode? It streams the warnings into the debug logger.

**Comment by enetz** [comment]
@jpfeuffer @bernt-matthias yes, this only happens in debug mode. The `params.update(..)` line turns actual warnings that would be visible without debug mode into softer warnings. But those are still visible and misleading.
I submitted a PR that simply removes all those parameters from the Param object that is passed from the tool to the algorithm classes. This removes both types of warnings, since no unknown parameters are passed on to the algorithm classes anymore.

I fixed this for OpenPepXL, OpenPepXLLF and PeptideIndexer. Let me know if you find any other cases where this happens.
