### ISSUE TITLE
breaking older MSGF+ workflows

### ISSUE THREAD

**Issue by cbielow** [OpenMS/OpenMS#4766]
#4713 breaks workflows, because the new flags are not known (e.g. for MSGF+ 2018)

**Comment by timosachsenberg** [comment]
do we really want to keep backward compatibility to third-party tools?

**Comment by cbielow** [comment]
at least the minimum required version should be documented, or (better) actively tested in the adapter and quit with a proper error message.
Right now, the tool fails and reports:
` "Temporary output file '...' was not created by MSGF+. Please set a debug level > 10 and re-run this tool to diagnose the problem.`... which is highly confusing because 
A) by whom was the mzID generated, if not by MSGF+? (the wording is confusing!) It should say: `MSGF+ did not finish successfully ...` ...
B) The user has to run the tool again with debug enabled to get the output from MSGF+ which then tells him that certain flags are not supported...

**Comment by jpfeuffer** [comment]
I think the "re-run" message might be obsolete by now. At some point I changed the tools to use the same "runExternalProcess" method from TOPPBase.
They should report the stdout/err from the tool if something fails.
https://github.com/OpenMS/OpenMS/blob/4125788da613519618247e598a6bf1a0c39b2120/src/openms/source/APPLICATIONS/TOPPBase.cpp#L1543
However, some tools might have weird exit codes.

Regarding backwards compatibility: we should probably not support it because of maintenance effort but document it better (one place where it is kind of documented is the bioconda openms-thirdparty recipe)

**Comment by jpfeuffer** [comment]
@cbielow What is the status here. I think you and/or your students changed something in that regard.

**Comment by cbielow** [comment]
I think

> I think the "re-run" message might be obsolete by now. At some point I changed the tools to use the same "runExternalProcess" method from TOPPBase.
> They should report the stdout/err from the tool if something fails.
> 
> https://github.com/OpenMS/OpenMS/blob/4125788da613519618247e598a6bf1a0c39b2120/src/openms/source/APPLICATIONS/TOPPBase.cpp#L1543
> 
> However, some tools might have weird exit codes.
> 
This is exactly the Problem. Msgf returns 0 if you pass wrong parameters.
However this I fixed recently https://github.com/OpenMS/OpenMS/blob/922a11192bf5960c749437e6cff19aa7269c3634/src/topp/MSGFPlusAdapter.cpp#L578

The minimum version should also be documented now. Automated check would be better, but it's ok IMHO.
