### ISSUE TITLE
contrib libs not taking precedence during OpenMS build

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#4946]
I am building OpenMS under macOS. Contrib was successfully build including SQLite 3.15.0.
```
macOS 10.15.6
XCode 11.7
Apple clang version 11.0.3 (clang-1103.0.32.62)
```
During the OpenMS build a wrong SQLite version was found.
```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
 SQLite not found, try -DSQLite_DIR=<path>: Found unsuitable version
 "3.9.2", but required is at least "3.15.0" (found
 /Library/Frameworks/Mono.framework/Headers)
Call Stack (most recent call first):
 /Applications/CMake.app/Contents/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
 cmake/modules/FindSQLite.cmake:201 (find_package_handle_standard_args)
 src/openms/cmake_findExternalLibs.cmake:134 (find_package)
 src/openms/CMakeLists.txt:70 (include)
```
After removing SQLite 3.9.2 in `/Library/Frameworks/Mono.framework/Headers` the issue was resolved.

(1) But shouldn't SQLite first looked for in `contrib-build` and not system wide?

(2) Even providing the explicit path to `contrib-build` with `-DSQLite_DIR=<path>` had no effect.

**Comment by jpfeuffer** [comment]
HI @lars20070 !
Thanks for reporting.
So, contrib takes preference in the sense that we add the contrib folder in the first position of "CMAKE_PREFIX_PATH".
The ordering of the lookup mechanisms of CMake find-modules is specified [here](https://cmake.org/cmake/help/v3.18/command/find_path.html).
There is also the SQLite_ROOT variable. Maybe that helps. Also, make sure to use absolute paths without "~" or other abbreviations.
If you stumble over it again, could you run cmake with `-D CMAKE_FIND_DEBUG_MODE=ON`? Then it will give you more information about the searched paths.

**Comment by lars20070** [comment]
> So, contrib takes preference in the sense that we add the `OPENMS_CONTRIB_LIBS` folder in the first position of `CMAKE_PREFIX_PATH`.

Surprisingly, it didn't. The non-contrib 3.9.2 was found first. I will switch on debug mode, if I come across it again. Thanks.

**Comment by lars20070** [comment]
I did build OpenMS develop under Ubuntu. A second Boost outside the contribs did lead to Boost linking problems during OpenMS build. Removing the second Boost resolved the issue.

This is a second example (SQLite, Boost) that libs in `contrib-build` do not take precedence over libs elsewhere on the system. They should as @jpfeuffer pointed out, but currently don't.

**Comment by jpfeuffer** [comment]
Yes but they are slightly different problems. The first problem is taking precedence during finding, which should be solveable.
The second problem is taking precedence in the include paths, which is unfortunately not easily solveable without changes in the upstream contrib libraries. The problem is that sometimes system libraries lie directly in /usr/include or their include path is determined as this by a CMake find module (and then the headers are included as boost/headerX.h). As soon as this include path is added for one library (since it was e.g. not build with contrib, maybe even Qt which cannot be built) it will result in the include of all the other libraries in there. Therefore the correct library (.a/.so/.dll) might be found by CMake and correctly used for compilation, but during linking it will use the wrong headers.

**Comment by jpfeuffer** [comment]
Actually, I just wanted to have a look at this again but I successfully compiled OpenMS on an Ubuntu with both system and contrib Boost.
Can you re-install the "second" boost and send me your build/CMakeCache.txt, build/src/OpenMS/CMakeFiles/OpenMS.dir/flags.make and build/src/OpenMS/CMakeFiles/OpenMS.dir/link.txt ?
