### ISSUE TITLE
Windows 10 refused ro run OpenSwathWorkflow.exe 

### ISSUE THREAD

**Issue by Liang-aaaaa** [OpenMS/OpenMS#4967]
The OpenSwathWorkflow.exe worked well when the output format is .tsv(the library is .tsv format, input file is a single mzML files transformed from diaPASEF by mobi-dik). However, when we transformed the library.tsv to library.PQP for .osw output，an error emerged: Unable to read file (- due to that error of type Parse Error in: C:\jenkins\ws\openms_release_packaging\9447518b\source\src\openms\source\FORMAT\HANDLERS\MzMLHandler.cpp@176-void __cdecl OpenMS::Internal::MzMLHandler::populateSpectraWithData_(void))
Then I tried to re-open the cmd window and run the same command line as I generated the .tsv output(have successfully finished), the Windows system refused access to openSwathWorkflow.exe. No matter restarting my PC or re-downloading Open-MS, the Windows system refused to run the program.
How can I fix this problem and get .osw output for pyprophet ananlysis?

**Comment by cbielow** [comment]
this error in MzMLHandler occurs while loading the data.
Since this step is independent of the output format and it worked before, I'd say there is some serious hardware problem, like hard disk failure or some process which corrupted your mzML input file.
Also the fact that Windows refuses to run the program (what exactly is the error message?), hints towards a failing disk.

In short, this is not an OpenMS problem.
Talk to your admin and have him check the system.
