### ISSUE TITLE
PyOpenMS Openswath for metabolomics

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#4972]
Hey :) 
Where can I find the script or commands necessary to call the Diametalyzer workflow (Openswath for metabolomics) in PyOpenms?

Thanks!

**Comment by oliveralka** [comment]
Hi @eeko-kon,

unfortunately, the "AssayGenertorMetabo" which is part of the DIAMetAlyzer workflow is not available as a wrapped pyopenms algorithm, so it can not be called from pyopenms. 

You could either try to script it in pyopenms - is probably over the top, or use this step in a bash script. In addition, there is further python code and tools, which are needed to run the workflow with the decoy generation, which is shipped inside the KNIME workflow (https://github.com/oliveralka/DIAMetAlyzer_additional_code/tree/master/workflow/KNIME/scripts_in_workflow_dir). 

What is your aim in running it with pyopenms? 

An alternative would be to run the workflow (tools) partially in a bash script and read in the .pqp file in pyopenms for example.

**Comment by eeko-kon** [comment]
Hi Oliver,

I only need the DDA part and the Candidate ID. No need for the rest of the tools. What would you suggest doing in this case?

**Comment by oliveralka** [comment]
So you basically would like to run FeatureFinderMetabo, MetaboliteAdductDecharger and AccurateMassSerach (CandidateID)? 

You can have a look at the tools and the algorithms they use.  For example:
`FeatureFind**er**Metabo` [1]
uses the `FeatureFind**ing**Metabo` algorithm [2]
which is wrapped for pyopenms using a .pxd file [3]

Here is en pyopenms example on how to use feature detection in general. This could be adapted to the FeatureFinderMetabo. The other algorithms can be called in a similar fashion. 
https://pyopenms.readthedocs.io/en/latest/feature_detection.html

If you are only interested in the outputs of the specific tools, I would suggest sticking to bash scripts, since 
the pyopenms library is in my option best for prototyping and development of extension for specific algorithms. 

I hope that helped a bit - let me know if you have further questions! 

[1] https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FeatureFinderMetabo.cpp
[2] https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FILTERING/DATAREDUCTION/FeatureFindingMetabo.cpp
[3] https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pxds/FeatureFindingMetabo.pxd

**Comment by eeko-kon** [comment]
That's great, thank you so much!

**Comment by oliveralka** [comment]
Please reopen, if you have further questions!
