### ISSUE TITLE
OpenSWATH with IPF enabled omits features of detecting/quantifying transitions

### ISSUE THREAD

**Issue by yyi17** [OpenMS/OpenMS#5118]
After running OpenSwathWorkflow with parameter `-enable_ipf true`, in the output OSW file the `FEATURE_TRANSITION` table contains only the data of identifying transitions, while those of detecting or quantifying transitions are missing.

Are there any options to fetch transition-level feature data (e.g. area intensity) of non-identifying transitions when IPF is enabled?

Version: 2.6.0 Sep 30 2020, 13:11:25, Revision: c26f752

**Comment by grosenberger** [comment]
Unfortunately, only the identifying transitions are reported in this mode at the moment. However, since detecting or quantifying transitions are typically a subset of the identifying transitions, those transitions could be mapped by their annotation tag through a modified SQL query to obtain the corresponding features.
