### ISSUE TITLE
MetaboliteAdductDecharger warnings

### ISSUE THREAD

**Issue by rickhelmus** [OpenMS/OpenMS#5133]
Hello,

I am started working with MetaboliteAdductDecharger for adduct detection. I get two warnings of which I'm a bit unsure about:

```
ConsensusFeature::computeDechargeConsensus() WARNING: Feature's charge is 0! This will lead to M=0!
Warning: Adduct was given only a single element but with an abundance>1. This might lead to errors! (Na2)
```

Example command:
```
$ MetaboliteAdductDecharger.exe -in test.featureXML -out_cm testadd.consensusXML -algorithm:MetaboliteFeatureDeconvolution:charge_max 2 -algorithm:MetaboliteFeatureDeconvolution:potential_adducts H:+:0.8 Na2:++:0.2 -algorithm:MetaboliteFeatureDeconvolution:q_try "heuristic"
```

The first warning makes sense, as the featureXML input files indeed have a charge set to zero, because I don't know have charge information available. However, I hoped setting `q_try` to something else than `"feature"` would avoid this.

The second warning is perhaps related to me not fully realizing how to specify eg `[M-Na2]2-` adducts ;-)

Thanks,
Rick

**Comment by FabianAicheler** [comment]
I think the intention behind the second warning is that users instead should have only a single Na as possible adduct (instead of Na2) while allowing for charges (max_charge parameter 2 or larger) to allow for adduct combinations to lead to Na2.

Otherwise, possible adducts would be Na2, Na4, Na6, ... etc. While technically possible with the underlying implementation, I assume that algorithm development was not focussed on making such a (preventable) case bulletproof -> code logic, heuristics, pruning etc might behave unexpectedly, which would be very hard to track afterwards (particularly when trying to reason why specific adduct combinations were taken or rejected)

**Comment by rickhelmus** [comment]
Hi Fabian,

That makes sense, I didn't take in to account the addition of multiple adducts dictated by the max charge.

Thanks!

Rick
