### ISSUE TITLE
RNAses with multi nucleotide specificity are not supported

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#5215]
See https://github.com/OpenMS/OpenMS/pull/5200 for background. Current parsing of the regexes for enzymes that match multiple consecutive nucleotides (eg, mazF) fails. See line https://github.com/OpenMS/OpenMS/blob/55598cf39c73a2092365fbdb51e63defa9b29c6f/src/openms/source/CHEMISTRY/RNaseDigestion.cpp#L106

**Comment by hendrikweisser** [comment]
Hm, good point. It appears that is currently not supported. (We haven't had an enzyme that needed this until now.)

If I remember correctly, there is the "older" mechanism (inherited from protein digestion) that uses the "RegEx" entry (from the enzymes XML file) to find cutting sites, by matching that regex against the string representation of the sequence. For RNA, I replaced that by the "CutsBefore"/"CutsAfter" regexes to have better control when matching against the neighbouring ribonucleotides (of the potential cutting site), because the modification state of a nucleotide can affect whether the enzyme will cut.
Unfortunately I think it would get quite complex to extend the "CutsBefore"/"CutsAfter" mechanism to stretches of nucleotides.

I think the pragmatic solution for mazF would be to add a fallback that uses the older functionality - matching "RegEx" against the string representation. The fallback could be triggered if the "CutsBefore"/"CutsAfter" regexes are undefined.
There is related code in `EnzymaticDigestion::digestUnmodified` (https://github.com/OpenMS/OpenMS/blob/8be26bac2ffcbf0454cfe9c875e9b8feb6226a2e/src/openms/source/CHEMISTRY/EnzymaticDigestion.cpp#L352). However, it will get tricky if you have to take possible modifications on the "ACA" pattern into account...

The other option I can think of would be to implement this directly in C++, rather than define the behaviour via regular expressions in an XML file. But that doesn't fit well with the current API for digestion in OpenMS, so you'd either need to hack in a special case or redesign the whole API - not great options.

**Comment by poshul** [comment]
What about if we made any "multi-base" cuts_*_regex use square brackets to separate the successive nucleic acids. For example MazF cutsBefore would be [A][G][A]?

**Comment by hendrikweisser** [comment]
Square brackets are reserved characters in regular expressions (for matching multiple alternatives).

**Comment by poshul** [comment]
Okay, I guess we would need to escape them (so \[A\]\[G\]\[A\]) but at least then we are consistent with the format in which we take input data. Alternatively, can we come up with some other divider that we can use to make explicit where the breaks between nucleic acid token are?

**Comment by hendrikweisser** [comment]
Just comma-separate them? That's the standard way of serialising lists in OpenMS. Should work okay here because commas aren't special characters in regexes and aren't used in short codes for ribonucleotides (I think - not 100% sure on either).

**Comment by poshul** [comment]
You are correct on both counts (https://www.boost.org/doc/libs/1_31_0/libs/regex/doc/syntax.html) (https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Modomics.tsv). I'm going to give that a shot and see how it looks.

**Comment by poshul** [comment]
I've implemented a fix for this using commas to separate successive nucleotides. It works for the mazF case. @hendrikweisser any thoughts as to where I should document this behavior? I'm thinking putting in a short description in the Enzymes_RNA.xml file.

**Comment by poshul** [comment]
Resolved in https://github.com/OpenMS/OpenMS/pull/5200
