### ISSUE TITLE
MassTrace Convex Hulls

### ISSUE THREAD

**Issue by bertrandboudaud** [OpenMS/OpenMS#5378]
We came across one issue with the convex hulls of the MassTraces.

at the moment the convex hull is constructed this way:

```
        hull_points[i][0] = (*l_it).getRT();
        hull_points[i][1] = (*l_it).getMZ();
```

(in `ConvexHull2D MassTrace::getConvexhull()` )

However, as a result, it gives us a convex hull where all the 'y' values are the same (because it's a MassTrace, we have the same MZ for all points)

![image](https://user-images.githubusercontent.com/1705849/122517480-5d66bb80-d010-11eb-9dce-7599a0922e4f.png)

Is it correct to set MZ as a secondary coordinate? we would have expected to have intensity here (in our case, but maybe we miss another use).

thanks for your feedback!

**Comment by cbielow** [comment]
This is working as intended IMHO.

The CH for mass traces are used for visualization (e.g. in TOPPView: 
![image](https://user-images.githubusercontent.com/6008722/122520209-9eac9a80-d013-11eb-84e3-1bd15447c8f9.png)
) and also to decide if a peak belongs to a feature, e.g. for IDMapper (because you would not want to make that query against the full convex hull across the whole m/z range of the isotopes when you have overlapping isotope profiles).

**Comment by jpfeuffer** [comment]
I agree with @cbielow that MZ is correct but want to add that I think some FeatureFinders (mainly in proteomics) interpret them differently and can/do only report a rectangular or trapezoidal bounding box instead of all mass traces.

**Comment by bertrandboudaud** [comment]
Thank you for your feedback. this is instructive 👍 
So if this is how it is supposed to be and useful, we will find a way to do what we want another way.
we can close this ticket.
