### ISSUE TITLE
Adapter for Comet Database Search Engine [545]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#545]
Submitted by wernber on 2013-06-20 16:00:38

Implementation of an Adaper/Wrapper for the database search engine Comet

The Comet search engine is a very powerful search engine (formerly known as Sequest - original algorithm)

When comparing to other search engines, this one is one of the two most powerful search engines and and takes mzML as input and outputs pepXML (my personal experience)

http://comet-ms.sourceforge.net/

http://www.ncbi.nlm.nih.gov/pubmed/23148064

Would be a very sad thing not to have it in the TOPP pipeline/ OpenMS library

**Comment by timosachsenberg** [comment]
@mwalzer Leon would take a look at this. Do you have a prototype he can build on?

**Comment by jpfeuffer** [comment]
Three points that might help:
- I modified the makefile to make an executable on macOS already (I think Leon already has it)
- I can say that the output can already be read in with the pepXML reader from @mwalzer 
- It might be more straightforward if we let the user pass the comet.myparams file but it would be better if at some point we could allow to overwrite the most important parameters (like in the other adapters) so that we can pass workflow variables into it (e.g. tolerance). One would need to write this to a standard params file for example. If the comet developers made it user friendly you might be able to just add parameters passed to the TOPP tool at the end of the standard params file.

**Comment by mwalzer** [comment]
He can take a look at Xtandem adapter, as it also writes a config file before executing the 3rd party exec.
And this is essentially the only thing missing to the adapter. Result file consumption I implemented a while ago.

btw, what is Leons handle?

**Comment by oliveralka** [comment]
@mwalzer Leons handle should be Leon-Bichmann.

**Comment by timosachsenberg** [comment]
I added him as a collaborator.

**Comment by hendrikweisser** [comment]
> He can take a look at Xtandem adapter, as it also writes a config file before executing the 3rd party exec.

Note that X! Tandem itself has a mechanism where a config file can reference a default config file. Settings in the (primary) config file override settings in the default config file (see http://www.thegpm.org/TANDEM/api/lpdp.html).

This mechanism was replicated in OpenMS (classes XTandemInfile and XTandemInfileXMLHandler), but since it was redundant I've removed that in my recent changes (#2428). Those changes are not yet merged, but when they are, you'd need to look at an older version of the code to see how it was handled.

**Comment by Leon-Bichmann** [comment]
OK, die erste funktionierende COMETAdapter version ist jetzt auf diesem branch:

https://github.com/Leon-Bichmann/OpenMS/blob/feature/COMETAdapter/src/utils/COMETAdapter.cpp

**Comment by timosachsenberg** [comment]
Thank. Can you remove / adapt the parts that still refer to X!Tandem? There seems to be some copy & paste leftovers.

**Comment by jpfeuffer** [comment]
Great! Looks good. If you create a pull request we can give you more detailed comments on specific parts of the code. I only have some minor ones.
You can still add commits later, that will appear automatically in the PR if you push them, so do not worry.

**Comment by jpfeuffer** [comment]
I'll post them here quickly, so I do not forget.
- replace __FUNCTION__ macro with OPENMS_PRETTY_FUNCTION
- remove ifdef for comet.exe
- add pid to output files of the tool
- can we come around writing the version into the param file header?
  * What about calling "comet -p" and replacing important occurrences?

**Comment by Leon-Bichmann** [comment]
Lars and I think that the longterm solution should involve creating a COMETInfile Class that handles all parameters separatly

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/OpenMS/pull/2478
