### ISSUE TITLE
The question of the combine the compound data

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#5525]
Hi,
Now, I have finded a node to combine the MS1 with the MS2 information. But now I don't know how to check the accuracy of the method.And the MetaboliteSpectralMatcher is excuting a sample,But the AccurateMassSearch node excutes all samples.I think it may be not perfect to identify the compound.
Thank you very much!
![image](https://user-images.githubusercontent.com/83147334/132469280-585b54c3-fcec-4e8d-aaac-bdf8cd693635.png)

**Comment by oliveralka** [comment]
Hi @hello-lei, 
unfortunately I do not have a straight forward answer for you here since I had not to deal with that problem yet. 

You are right, since the AccurateMassSearch, by using the consensusXML aggregates the feature information before performing the identification there is a difference in number of identifications in contrast to the MetaboliteSpectralMatcher. 

The question is how to aggregate that kind of information and to decide which on the identification is the "best" one. 

The first step would be to aggregate the information of every sample based on the same analyte/feature. I think here, the information in the ConsensusFeature (input in AccurateMassSearch) could be used to used to asses the correct features an identification belongs to based on mz and rt in the specific file. 

The second problem is the "scoring": If the information is aggregated it might be that you have multiple possible identifications for the same analyte/feature. Here, we could use a rudimentary "scoring" in the beginning by using the identification which was found more often over all the samples. We would have to look how the spectra are actually scored in the MetaboliteSpectralMatcher and see if there is a better scoring method available to aggregate the identification information. 

I currently, do not have much time to take a look at it, but if you are able to send me your workflow and some example data, I will try to take a look at it.

**Comment by hello-lei** [comment]
First,Thank your explain very much.
Yeah ,I agree your view. The further identification have the SIRIUSAdapter and the MetaboliteSpectralMatcher node. Now I have achieved them together.The key I think is how to combine the data to improve the accuracy How do I send you my workflow and data? The data is  so big that I can't upload my data.

**Comment by hello-lei** [comment]
Or I can send the data and the workflow in other ways.Do you have some nice methods?
Thank you!

**Comment by oliveralka** [comment]
You can write in the OpenMS Gitter Channel and we can also chat privately there - e.g. share a cloud link to deposit the files. I think that allows for faster conversations than via eMail.

**Comment by hello-lei** [comment]
What is the OpenMS Gitter channel? Can you share the link?

**Comment by oliveralka** [comment]
When you look at our **OpenMS Github Main Page** - you can see a small "gitter join chat" button. Just click it. 

This is how the button should look like:
![Screenshot 2021-09-13 at 08 39 38](https://user-images.githubusercontent.com/15729190/133036141-4738e306-56c8-4e4b-b010-abc34f708167.png)

**Comment by hello-lei** [comment]
Hi，I have got the OpenMS Gitter,but I can't find the cloud link to upload my workflow and the data.
Thank you very much!

**Comment by oliveralka** [comment]
You should see my name and icon on the right - you can click there and start a private chat - then I can send you a link.

**Comment by hello-lei** [comment]
Ok

**Comment by oliveralka** [comment]
Please open a new issue or write in the OpenMS Gitter channel if you have further questions.
