### ISSUE TITLE
Ion mobility units

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#5598]
@enetz Shouldn't this also catch `FAIMS_COMPENSATION_VOLTAGE` here?

https://github.com/OpenMS/OpenMS/blob/cef7d2efb34c594ffe55a55029b8d3374675b16d/src/openms/source/IONMOBILITY/IMDataConverter.cpp#L298

**Comment by enetz** [comment]
that function was written by @cbielow, so I am not sure about all use cases, but it is intentional, since the description in the header also states:
`For anything else (e.g. FAIMS-Compensation voltage) we throw.`

@cbielow is there a reason it is excluded in `setIMUnit`, even though `FAIMS_COMPENSATION_VOLTAGE` is also covered in the `DriftTimeUnit` ENUM?

my guess is that it is currently only used in `collapseFramesToSingle`, which doesn't look very useful for FAIMS data
