### ISSUE TITLE
ConsensusID failure because MS run path not interpreted from MSFragger idXML

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#5618]
I'm currently developing a TMT pipeline in which we would like to use XTandem, Coment and MSFragger as search engines. Below is the error message of `ConsensusID`:

```
Error: Unexpected internal error (the value '0' was used but is not valid; Currently only ID runs on exactly one mzML file are supported. Run MSFragger_2021-10-27T05:44:59_14920651020794111615 contains too many.)
```

I think here is the cause of this issue:

https://github.com/OpenMS/OpenMS/blob/e75e5e43ef903f10a263501769fe072f184b89cb/src/topp/ConsensusID.cpp#L708-L722

MSFragger's idXML does not have a `UserParam` tag with `name="spectra_data"`, so causing `getPrimaryMSRunPath` returns zero. I was able to work around it by adding a UserParam tag using sed. But it's probably worth to fix.

Also, the error message might be good to improve. Apparently 0 isn't too many. 😄

**Comment by prvst** [comment]
I found the same issue when running the standalone MSFragger followed by IDFileConverter (pepXML -> idXML).

**Comment by jpfeuffer** [comment]
Hmm true, the original error message was not corrected yet to distinguish between 0 (too few) and >1 (too many).
And without the adapter, the IDFileConverter does not automatically add a "spectra_data" parameter to the XML. If there is some kind of reference to the original mzml/raw in the pepxml we could parse this, otherwise we would need to allow an additional parameter to the file converter to allow adding it while converting, to satisfy ConsensusIDs strict comparisons.
There might be a force parameter in ConsensusID to skip strict file origin checking but I am not sure if we implemented that yet.

A hacky workaround for now would be to add that UserParam "spectra_data" XML element manually with e.g. sed or an XML processor to the resulting idxml file.
