### ISSUE TITLE
GNPSExport memory issues

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5707]
Sooo I'm finally running my 1,300 raw files using the OpenMS CLI (+snakemake) and I m renting a VM Standard D8s v3 (8 vcpus, 32 GiB memory) which should be enough, but actually, right at the GNPSExport step the workflow is crashing due to memory issues - So I am now monitoring what's going on and I can see that I am still at 1.67% of the process but GNPSExport is using already 62.6% of the memory. GNPSExport converts the filtered (only features with MS2 data) consensusXML to an .mgf file. 

Could there be any optimization as to how the code works here? It seems that it's continuously appending and adding on the memory which makes sense, but I m just wondering if there is another way to do this..? Demands the inexperienced programmer 👯

**Comment by jpfeuffer** [comment]
Hi,

the caching mechanism seems to have been removed or not completed:
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/GNPSExport.cpp#L430

Currently, it loads ALL mzMLs into memory when needed. You need to limit the number of cached mzmls.
And when that amount is reached, one mzML needs to be freed before a new one is loaded (maybe there is even a smart way to predict which mzMLs will be used in the immediate future, otherwise just remove a random one).

**Comment by timosachsenberg** [comment]
Maybe we could look into using ondiscexperiment

**Comment by timosachsenberg** [comment]
I can take a look

**Comment by eeko-kon** [comment]
Thank you Timo!

**Comment by timosachsenberg** [comment]
did not test it on a large number of file: https://github.com/OpenMS/OpenMS/pull/5709

**Comment by eeko-kon** [comment]
Did not work - still using a lot of memory

**Comment by eeko-kon** [comment]
That worked- there was a problem with my OpenMS build
