### ISSUE TITLE
MSFraggerAdapter: Invalid string parameter value '0,1,2' for parameter 'isotope_error' given! Valid values are: '0,1,2'

### ISSUE THREAD

**Issue by zhuchcn** [OpenMS/OpenMS#5746]
Hi, I got this error when setting `isotope_error` with MSFraggerAdapter.

```
Invalid string parameter value '0,1,2' for parameter 'isotope_error' given! Valid values are: '0,1,2'
```

I checked the ini file it does look like the value is '0,1,2'. Did I miss anything?

**Comment by tillenglert** [comment]
Hi zhuchcn,

this parameter should be set as "0/1/2" instead if you want to have multiple isotope error windows or just "1" or "2". Maybe you can check if "0/1/2" works, otherwise we need to fix this, as it is not given in valid options.

https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/UTILS_MSFraggerAdapter.html

-tolerance:isotope_error <isotope_error>                                 Isotope correction for MS/MS event
                                                                           s triggered on isotopic peaks.
                                                                           Should be set to 0 (disabled) for
                                                                           open search or 0/1/2 for correctio
                                                                           n of narrow window searches. Shift
                                                                           s the precursor mass window to
                                                                           multiples of this value multiplied
                                                                           by the mass of C13-C12. (default:
                                                                           '0' valid: '0', '1', '2')

What version of OpenMS are you working on?

**Comment by tillenglert** [comment]
I already created a pull request to support using 0/1/2 as an option for the isotope error.

https://github.com/OpenMS/OpenMS/pull/5749

**Comment by zhuchcn** [comment]
Just tried '0/1/2' and it still doesn't work

```
Invalid string parameter value '0/1/2' for parameter 'isotope_error' given! Valid values are: '0,1,2'. Updating failed!
```

**Comment by tillenglert** [comment]
Have you pulled and build the newest version? The pull request was merged earlier today and it should work now.

**Comment by zhuchcn** [comment]
Testing right now!

**Comment by zhuchcn** [comment]
Just confirm that it has been fixed!
