### ISSUE TITLE
Isotope masses slightly off 

### ISSUE THREAD

**Issue by dlon450** [OpenMS/OpenMS#5841]
Hi,

I'm currently working on a project to identify protein adducts. I have been trying to find the most abundant isotope for Ubiquitin protein, as well as metals such as platinum and ruthenium. However, they seem to be slightly different from commercial sources (Bruker) and those found online. 

Using the coarse generator:
```
formula_str = 'C378H629N105O118S1' #this is Ubiquitin
seq_formula = EmpiricalFormula(formula_str)
isotopes = seq_formula.getIsotopeDistribution( CoarseIsotopePatternGenerator(20) )
masses, rel_abundance = zip(*[(iso.getMZ(), iso.getIntensity()) for iso in isotopes.getContainer()])
print(masses[np.argmax(rel_abundance)])
>>> 8564.6335299841
```
Using the fine generator:
```
isotopes = seq_formula.getIsotopeDistribution( FineIsotopePatternGenerator(0.1) )
masses, rel_abundance = zip(*[(iso.getMZ(), iso.getIntensity()) for iso in isotopes.getContainer()])
print(masses[np.argmax(rel_abundance)])
>>> 8563.6301757951
```
Using commercial software, the most abundant isotope for Ubiquitin is 8564.630429.

For Pt:
- Using the coarse generator: 194.9711025134
- Using the fine generator: 194.9647911
- Using commercial: 194.964792

For Ru:
- Using the coarse generator: 101.9277270268
- Using the fine generator: 101.9043493
- Using commercial: 101.904344

I realise that this a very small difference, but when doing high resolution data processing it becomes significantly relevant for error calculations. Thanks :)

**Comment by timosachsenberg** [comment]
Potentially related to https://github.com/OpenMS/OpenMS/issues/4615

**Comment by timosachsenberg** [comment]
and the calculation in:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/CoarseIsotopePatternGenerator.cpp#L495-L514

**Comment by timosachsenberg** [comment]
Thanks for reporting the issue.
First let me make sure that I understand correctly.
1. The coarse generator returns a value close to the expected one 8564.6335299841 vs 8564.630429
2. The fine generator seems to be off with 8563.6301757951

Could it be that this is still correct? The fine generator returns all isotopic peaks while the coarse one returns binned ones (e.g., think of it as summed abundances for a particular number of added neutrons). E.g., maybe the most intensity fine structure peak is at 8563.6301757951 while the sum of all fine structure peaks for a given neutron number is highest at 8564.63?

**Comment by hroest** [comment]
I think there may be small differences in the recorded masses of the elements which can lead to slight differences in the final results. I have run the tool with somewhat more fine-grained resolution (1e-3 cutoff) which leads to these results
```
isotopes = seq_formula.getIsotopeDistribution( FineIsotopePatternGenerator(1e-3) )
iso_filter = [(iso.getMZ(), iso.getIntensity()) for iso in isotopes.getContainer() if int(iso.getMZ())==8564]
sum([ m*i for m,i in iso_filter]) / sum([i for m,i in iso_filter])
>>> 8564.63044867891
sum([i for m,i in iso_filter])
>>> 0.16689567547246043

iso_filter = [(iso.getMZ(), iso.getIntensity()) for iso in isotopes.getContainer() if int(iso.getMZ())==8563]
sum([ m*i for m,i in iso_filter]) / sum([i for m,i in iso_filter])
>>> 8563.62782218416
sum([i for m,i in iso_filter])
>>> 0.1659167899338172
```

as you can see, all nominal masses at 8564 have a (slightly) higher total probability with 16.69% vs 16.59% for the 8563 nominal mass. For the averaged mass over all produced hyper-fine peaks, we get an intensity-weighted average of 8564.63044867891 m/z which is quite close to the value of the commercial tool that you are using. 

I think the difference that you are seeing here is whether you are using the *overall highest peak* of a hyperfine mass distribution (which is 8563.6301757951) or if you are looking at the *highest nominal mass peak* by intensity weighted average of a hyperfine mass distribution (which is 8564.63044867891). Note that these can be different, and here they happen to be since higher isotopes tend to have more peaks each with lower intensity. Here the overall highest peak is indeed 8563.6301757951 m/z with intensity 0.0883576348423958 but the intensity average of nominal peak is very close between 8564 and 8563 with 8564 being about 0.6% higher than 8563 (I am not sure if you could distinguish this intensity difference with your instrument). Note that the second highest peak is actually 8562.6268207951 (with 8.7% weight) and only the third-most intense peak is of nominal mass 8564, namely 8564.6335307951 with 7.1% weight.

regarding the error if your tool vs the intensity-averaged values, the error is on the order of 10e-9 or 0.002 ppm between the commercial result and the fine isotope generator:
```
(8564.630429-8564.63044867891)/8564.63044867891
>>> -2.297695129308194e-09
```
which I think is pretty close and probably due to small differences in the masses of the individual elements used for the calculations and/or the approximations used to create these values. The difference is very likely not possible to measure with any current MS instrument as it would require an resolution larger than 0.002 ppm.

If you look at metals like Pt, it seems our values correspond to the values for 195Pt, namely 194.9647911(9) [1] which is derived from the 2003 paper of Audi et al [5]. Note that more recent work from 2016 such as Huang et al [2] states the mass as 194.964794353±0.000000539 as seen from their supplemental tables [3]. So it seems like the 6th number after the decimal point is still going through revisions from 1 (us / WP) to 2 (your tool) to 4 (Huang et al). It seems that if we look at the 2003 dataset of the AME [4] in Audi et al [5] we find a value of 194.9647911±0.0000009 which is the value used in OpenMS and on Wikipedia. I dont know where the value in your tool comes from. But it does raise the point that we could attempt to update our tables in OpenMS to the most recent tables from 2016 in order to be more accurate (I am not sure how much of a difference this change in the 6th decimal value would really make though).

1. https://en.wikipedia.org/wiki/Isotopes_of_platinum
2. The AME2016 atomic mass evaluation (I). Evaluation of input data; and adjustment procedures. cms.iopscience.org/e4ef3f65-0d62-11e7-9a47-19ee90157113/030002.pdf
3. http://amdc.in2p3.fr/masstables/Ame2016/mass16.txt
4. http://csnwww.in2p3.fr/amdc/masstables/Ame2003/mass.mas03round
5. https://www.sciencedirect.com/science/article/pii/S0375947403018098

**Comment by dlon450** [comment]
Thanks for those suggestions and feedback. I think [hroest](https://github.com/hroest) has explained it quite well and so I'll have a go at seeing if the highest nominal mass peak values are close to the commercial software!

**Comment by hroest** [comment]
PS: please also realize that the m/z values of the coarse isotope generator will generally not accurately reflect the mass center since it uses a rather simple formula to calculate higher isotope peaks as @timosachsenberg -- it is rather coarse... @timosachsenberg maybe it would make sense to provide a binned version of the fine isotope distribution that provides accuracy and simplicity?

**Comment by timosachsenberg** [comment]
I think it makes sense to provide a simple binning method but we would need to document this well as there might also be some unexpected results.
E.g., if we just bin fine by mass both coarse and fine are not comparable for very large molecules. It can happen that the same number of neutrons fall into two distinct mass bins (e.g., if we have two elements with significantly different mass defects between their isotopes). And I think that the way _coarse_ works it bins at "number of additional neutrons"
while _fine_ is at the true masses.

**Comment by hroest** [comment]
optimally we would provide a method that ensures binning at number of neutrons but probably a simpler clustering method would be more than sufficient.

**Comment by KyowonJeong** [comment]
I also checked with Isotopicdist function in Bioinformatics toolbox in matlab (with isotopicdist([378,629,105,118,1])).
The most abundant mass is 8564.62888, which is not exactly the same as your output.  But the ppm error is only 0.18ppm. 
Matlab output also comes with two versions: one is coarse mass distribution (only 22 bins from mono to 21nd isotope), and the other is fine distribution (the masses have total ~33000 distinct values - using Rockwood, A. L., Van Orden, S. L., and Smith, R. D. (1996). Ultrahigh Resolution Isotope Distribution Calculations. Rapid Commun. Mass Spectrum 10, 54–59.  ). In the coarse case, the most abundant mass is 8564.63, which is far away from any output. But in the find case the difference is less than 0.2ppm as mentioned. 

OpenMS and Matlab use different calculation methods and very slightly different masses (different in 1e-4 Da range for N, O, etc). Probably as @hroest mentioned, this small difference results in a few ppm different in big molecules. I will locally modify the mass values in ElementDB.cpp and test how the results change.

**Comment by dlon450** [comment]
Appreciate all the help and support. I'm definitely not an expert in chemistry and not sure if I understand the binning method fully, but I've had a try and gotten pretty similar values - I agree that for Pt and Ru the values are similar enough. If everything below looks fine and makes sense I think I will close the query. Thanks everyone!

```
def peak_isotope(formula: str) -> float:
    seq_formula = EmpiricalFormula(formula)
    isotopes = seq_formula.getIsotopeDistribution( FineIsotopePatternGenerator(1e-3) )
    iso_dict = {}
    for iso in isotopes.getContainer():
        mz = iso.getMZ()
        group = int(mz)
        iso_dict[group] = iso_dict.get(group, []) + [(mz, iso.getIntensity())]

    best_abundance = 0.
    best_mass = 0.
    for _, value in iso_dict.items():
        abundance = sum([i for m,i in value])
        if abundance > best_abundance:
            best_mass = sum([ m*i for m,i in value]) / abundance
            best_abundance = abundance

    return best_mass

peak_isotope('C378H629N105O118S1') 
>>> 8564.63044867891
peak_isotope('Pt')
>>> 194.9647911
peak_isotope('Ru')
>>> 101.9043493
```

**Comment by hroest** [comment]
>  If everything below looks fine and makes sense I think I will close the query.

yes, this looks correct to me
