### ISSUE TITLE
TOPPView large memory consumption when clicking on log scaling in 1D view

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#5868]
Memory consumption went up to 90gb on a small dataset. Tested on linux via x forwarding.

**Comment by cbielow** [comment]
i can confirm:
from 0.2 GB to 13GB in the click of a button :)

![image](https://user-images.githubusercontent.com/6008722/156339162-63324794-f548-4963-857d-8c4720e6c711.png)


the problem is here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/AxisTickCalculator.cpp#L158

fix coming up.
