### ISSUE TITLE
FeatureLinkerUnlabeledKD produces empty consensus

### ISSUE THREAD

**Issue by eeko-kon** [OpenMS/OpenMS#5978]
I have two datasets that were run using the same method. The Map aligner works fine, all the preprocessing steps are great, but at the re-quantification step (FFmetaboIdent), even though each featureXML file generated is not empty, FeatureLinkerUnlabeledKD produces an empty consensus file. Why? When can this happen?

**Comment by enetz** [comment]
@eeko-kon  the only thing I can think of without more info, is that there are no or too few common features between the files. If no features can be linked, the consensus files would be empty.

Can you provide some example files where this happens, or describe the data in more detail? If you have two datasets, are you linking features from two files at a time, one from the first and one from the second data set? Or are you linking them all at once?
I am not exactly sure how the FeatureLinkerUnlabeledKD works, but does it require the same feature to be found in all input files for it to be reported in the results? In that case, the chance of finding a feature in every file would of course decrease for larger numbers of input files.

**Comment by eeko-kon** [comment]
Hi Eugen!

That shouldn't be a problem in linking, I am guessing. I have examples where a feature is only present in a single sample out of approximately 20 and there was no issue at all. I am getting this error:
```
Linking 50 featureXMLs.
Progress of 'reading input':
-- done [took 01:02 m (CPU), 01:03 m (Wall)] -- 
Progress of 'computing RT transformations':
  53.92 %               Error: Unable to fit linear transformation to data points.
Number of consensus features:
  total:           0
FeatureLinkerUnlabeledKD took 01:05 m (wall), 01:04 m (CPU), 1.02 s (system), 01:03 m (user); Peak Memory Usage: 252 MB.
```

Both from the develop and 2.7 version, whereas Axel tried it from his Windows pc (2.7 OpenMS) and it worked perfectly fine. 

Here are the files:

https://drive.google.com/drive/folders/1EzVqBg2zsXj30jYFxO25AQIgfPLHIXmb?usp=sharing

**Comment by enetz** [comment]
I was able to reproduce this on Linux with the current develop code.
It looks like it happens when some specific files are part of the linking, e.g. this one: `FFMID_20210612_UMETAB211_POS_MA_HLB100_Pl14_72_blank.featureXML`
I could not figure out, why this file in particular. It works fine, if I remove it.
Linking just this file to a few random others worked out fine as well, but adding about 15 different files caused the error to appear again.

The exception is thrown here:
https://github.com/OpenMS/OpenMS/blob/78304b740751603ac5c41b618ec95d0c8e48c51c/src/openms/source/ANALYSIS/MAPMATCHING/TransformationModelLinear.cpp#L87-L90

From what I can tell the function calls go something like this:
`MapAlignmentAlgorithmKD::fitLOWESS()` is called and uses `TransformationModelLowess` which uses `TransformationModelInterpolated` which uses `TransformationModelLinear`
The last change here was by @timosachsenberg in b2cfc1eb966cfc6ab49fe70253678e72732f4951 , but if it's the same with 2.7 that is probably irrelevant.
The code causing the exception uses functions from the WildMagic5 lib. Maybe a mismatch in WM5 lib behavior can cause this discrepancy between Linux and Windows versions?

**Comment by timosachsenberg** [comment]
Hmm blank sounds like it might contain no or few features. We had similar issues in the past and a simple check for <2 or <3 features (don't recall) did fix the issue. @eeko-kon do you recall the issue you opened?

**Comment by enetz** [comment]
The file is 21 MB large and contains many features. I also checked the data given to `Wm5::HeightLineFit2` with gdb.
`points` contains two entries: `mTuple = {40.69040599264212, 39.665594672489611}` and `mTuple = {40.69041070079674, 39.665599359646443}` . The two points are extremely close, but not the same. Not sure if this is unusual or expected.

**Comment by eeko-kon** [comment]
@timosachsenberg that was an issue with FeatureFinderMetaboIdent when it couldn't match any features to the MetaboliteIdentification file:

[#5677 ](https://github.com/OpenMS/OpenMS/pull/5677)

**Comment by eeko-kon** [comment]
@enetz I followed your strategy initially and got the same results. If I split the data into two groups, the linking works. Those groups are two different runs, both from similar bacterial strains, but with different extraction procedures and different time points that they were analyzed (same LC-MS-MS/MS method, and the runs were a few weeks apart) so maybe there is something going on there. Too much RT shift would appear as an issue at map alignment though which is already done.

**Comment by enetz** [comment]
this might be related to  #4175 and #4330

**Comment by enetz** [comment]
The issue is this WildMagic function:

`// Least-squares fit of a line to (x,f(x)) data by using distance
// measurements in the y-direction.  The resulting line is represented by
// y = A*x + B.  The return value is 'false' if the 2x2 coefficient matrix
// in the linear system that defines A and B is (nearly) singular.  In this
// case, A and B are returned as MAX_REAL.
template <typename Real> WM5_MATHEMATICS_ITEM
bool HeightLineFit2 (int numPoints, const Vector2<Real>* points,
    Real& coeffA, Real& coeffB);`

And here the problem seems to be the `(nearly)` in the description. The points are too close to each other and we need to take care of such special cases manually.

**Comment by timosachsenberg** [comment]
Good find! So I think we need to:
1. detect that situation using the bool
2. have a fall-back in the affected algorithms (e.g., using the mean of both y as a constant could work)
