### ISSUE TITLE
Using OpenMS parsers in a C++ application

### ISSUE THREAD

**Issue by guoci** [OpenMS/OpenMS#6144]
Is it possible to use the mzML and mzXML parsers in OpenMS in a C++ application? Or are they currently designed for internal use by OpenMS code only?

**Comment by cbielow** [comment]
There are basically three options that come to mind:
1) use the [OpenMS library as a dependency](https://abibuilder.informatik.uni-tuebingen.de/archive/openms). Then you can simply include the [mzMLFile header](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1MzMLFile.html)  in your cpp file and use it.
2) Since the parsers depend on a lot of datastructures (e.g. MSSpectrum) for handling the data, you cannot simply pull out one header/cpp from the library and use it independently. But you could replace some datastructures with your own ones, and discard things which you do not need from the parser. It depends a bit on how complete your parser needs to be. In any case, you'll need to pull in the Xerces-C library, since this is what the OpenMS Parser is build upon.

Option 1 is definitely the easiest. Option2 is way harder, but reduces dependencies.

**Comment by timosachsenberg** [comment]
@cbielow the link might be wrong. Did you mean https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/external_code.html

**Comment by cbielow** [comment]
ah, yes. Corrected.

**Comment by guoci** [comment]
@cbielow you said "three options" but only listed two, off-by-one error?

**Comment by guoci** [comment]
@cbielow @timosachsenberg thanks for your answers!

**Comment by guoci** [comment]
It turns out that the binaries from pyOpenMS are very useful, it contains all dependencies without the need for any installation. 
The `.deb`  is still missing the `Qt` libraries, requires administrative rights to install, and doesn't work on non Debian based distros.

**Comment by timosachsenberg** [comment]
Thanks for the feedback!
