### ISSUE TITLE
[TOPPView] Filter doesn't work for 1D data

### ISSUE THREAD

**Issue by greengypsy** [OpenMS/OpenMS#6216]
As shown below, the filter isn't working. @axelwalter also tried, and he had the same issue.
![image](https://user-images.githubusercontent.com/31978630/177731049-90dac88a-d17e-43d2-9f54-94da864f891c.png)

**Comment by axelwalter** [comment]
They issue seems to be with mzML files that contain only one spectrum. When selecting a spectrum from the 2D view, the intensity filters work as intended.

**Comment by timosachsenberg** [comment]
Hmm think that is worth investigating. Sounds like a bug

**Comment by axelwalter** [comment]
Created a test mzML file with only one spectrum and it worked fine. Perhaps the issue is only with the `peakpicker_tutorial.mzML` example files.

**Comment by cbielow** [comment]
Close.
The "problem" here is the drawing mode: if sticks are drawn, the filters are active in 1D. 
However, if you draw connected lines (as is the default for the PeakPicker1D data), then the filters are not applied, because you'd skip over some points when drawing the line.
Not sure if this was intended or simply forgotten.
I added the filter in my PR #6139  (see https://github.com/OpenMS/OpenMS/pull/6139/commits/a5774f4dac3a552974094d4af68d856b04b34e4b).
This is the new look 
![image](https://user-images.githubusercontent.com/6008722/182621116-2bb88834-17c6-4513-9ec0-4d5aba270956.png)


This also fixes another bug, where changing a filter value will actually toggle the filter active/inactive, depending on its former state, but leave the checkbox checked.
