### ISSUE TITLE
Internal representation of idXML files very inefficient [624]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#624]
Submitted by cbielow on 2013-11-04 10:33:46

Loading a 1GB file uses about 7GB of memory (Win64), plus it takes ages to load (indicating that the parser might have potential for speedup).

So, memory usage must go down, since this affects all tools using IDXML.
While at it, we can use proper members for MZ and RT, instead of meta-values -- this might actually be (one of) the reasons why memory consumption is so high.

---

Commented by hendrikweisser on 2013-11-06 12:21:45:

> While at it, we can use proper members for MZ and RT, instead of meta-values -- this might actually be (one of) the reasons why memory consumption is so high.

That should have happened a long time ago, but does it still make sense now that we're planning to switch to mzIdentML?

**Comment by hroest** [comment]
I have done some benchmarking on the file provided from https://github.com/OpenMS/OpenMS/pull/3750#issuecomment-423726499 to document progress on this issue:

# Benchmarking 
```
$ /usr/bin/time ../release_2.1/bin/FileInfo  -in E3035_HCV_LAB1.idXML
^CCommand terminated by signal 2
176.97user 24.04system 7:57.48elapsed 42%CPU (0avgtext+0avgdata 13351316maxresident)k
$ /usr/bin/time ../release_2.3/bin/FileInfo  -in E3035_HCV_LAB1.idXML
File '/home/hr/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/home/hr/.OpenMS/OpenMS.ini' with defaults!
^CCommand terminated by signal 2
153.69user 6.60system 2:41.31elapsed 99%CPU (0avgtext+0avgdata 13515052maxresident)k
$ /usr/bin/time ../release_2.4/./bin/FileInfo -in E3035_HCV_LAB1.idXML 
Memory usage (loading idXML): 10520 MB (working set delta)
FileInfo took 02:15 m (wall), 02:15 m (CPU), 3.20 s (system), 02:11 m (user).
```
Note that I had to abort the test with OpenMS 2.1 and 2.3 due to excessive memory consumption and swapping on my system after reaching 13 GB of memory usage.

after merging https://github.com/OpenMS/OpenMS/pull/3744
```
$ /usr/bin/time ../pr_3744/bin/FileInfo -in E3035_HCV_LAB1.idXML
Memory usage (loading idXML): 5327 MB (working set delta)
```
after https://github.com/OpenMS/OpenMS/pull/3755
``` 
$ /usr/bin/time ./bin/FileInfo -in /media/doc/tmp/openms_issues/E3035_HCV_LAB1.idXML
Memory usage (loading idXML): 3002 MB (working set delta)
FileInfo took 01:55 m (wall), 01:52 m (CPU), 1.85 s (system), 01:50 m (user).
```

So far, it looks like memory is reduced by a factor of 3 and execution speed is slightly faster (around 15%). 

# String Metavalues

## Removing Metavalues
However, the file also had an excessive amount of string meta values, which I further investigated. When removing all string values
```
$ grep -v 'UserParam type="string"' E3035_HCV_LAB1.idXML  > /tmp/qqq.idXML
$ /usr/bin/time ./bin/FileInfo -in /tmp/qqq.idXML 
Memory usage (loading idXML): 1709 MB (working set delta)
FileInfo took 49.02 s (wall), 49.01 s (CPU), 0.90 s (system), 48.11 s (user).
FileInfo took 49.02 s (wall), 49.01 s (CPU), 0.90 s (system), 48.11 s (user).
48.13user 0.90system 0:49.09elapsed 99%CPU (0avgtext+0avgdata 1930636maxresident)k
```
## Converting Metavalues

and when converting individual string meta values to floats: 

```
$ ./bin/FileInfo -in/E3035_HCV_LAB1.idXML
Memory usage (loading idXML): 3003 MB (working set delta)
$ sed  's/type="string" name="MeanErrorAll"/type="float" name="MeanErrorAll"/'  E3035_HCV_LAB1.idXML  > /tmp/q1.idXML
$ sed -i 's/type="string" name="StdevErrorAll"/type="float" name="StdevErrorAll"/'  /tmp/q1.idXML  > /tmp/q2.idXML
$ sed  's/type="string" name="NTermIonCurrentRatio"/type="float" name="NTermIonCurrentRatio"/'  /tmp/q2.idXML  > /tmp/q3.idXML
$ ./bin/FileInfo -in /tmp/q1.idXML
Memory usage (loading idXML): 2955 MB (working set delta)
$ ./bin/FileInfo -in /tmp/q2.idXML
Memory usage (loading idXML): 2906 MB (working set delta)

```

it seems that memory usage improves by about 50 MB for each value that is converted from a `String` to a float value, so that is about 50 bytes which seems to make sense given that a String requires 32 bytes in memory, these are small strings (<16 bytes) for which the SSO is applied and then there is approx 20 byte overhead for memory fragmentation / alignment. Still, it is interesting to note how something that is about 10 chars long (10 bytes) suddenly turns into 50 bytes of memory, basically producing 5x overhead for storage in memory. 

## String overhead

To look at this, I ran some benchmarks and found similar numbers as http://jovislab.com/blog/?p=76 for memory overhead of `std::string`. It turns out, storing many strings has quite a bit of overhead, especially when storing small strings. Here are some benchmarks for medium size strings (47 bytes on average):

```C++
      std::vector<PeptideIdentification> v;
      String longStr;
      std::vector<String> vv;
      std::vector<char *> vvv;
      std::vector<int> off;
      String hello;

      for (Size k = 0; k < 10; k++) hello += "hello";
      std::cout << hello.size() << std::endl; // should be 50 bytes

      std::cout << sizeof(DataValue) << std::endl;
      std::cout << sizeof(MetaInfo) << std::endl;
      std::cout << sizeof(String) << std::endl;

      v.reserve(1024*1024);
      for (Size k = 0; k < 1024*1024; k++)
      {
        PeptideIdentification id;
        v.push_back(id);
        // ---------------
        // Memory usage (loading MS data): 170 MB (working set delta)
        // ---------------
        v.back().setMetaValue("someValue", 5.0);
        // ---------------
        // Memory usage (loading MS data): 234 MB (working set delta)
        //   64 bytes to store a float
        //      24 for MetaInfo
        //      8  for overhead (alignment of MetaInfo)
        //      16 for DataValue
        //      4  for UInt
        //      12 for overhead (alignment, boost::flat_map)
        // ---------------
#if 0
        v.back().setMetaValue("someNewValue", 5.0);
        // ---------------
        // Memory usage (loading MS data): 266 MB (working set delta)
        //   32 bytes to store a float
        //      16 for DataValue
        //      4  for UInt
        //      12 for overhead (alignment, boost::flat_map)
        // ---------------
#else
        v.back().setMetaValue("someNewValue", hello);
        // Memory usage (loading MS data): 378 MB (working set delta)
        //   144 bytes to store a strong of 50 chars (+1)
        //      16 for DataValue
        //      4  for UInt
        //      12 for overhead (alignment, boost::flat_map)
        //      110 for the String 
        //        - 98 bytes for the String (includes 15 bytes overhead)
        //        - 12 bytes additional overhead
        // ---------------
        // For a small string (<16 bytes) 
        // Memory usage (loading MS data): 313 MB (working set delta)
        //   80 bytes to store a strong of 50 chars (+1)
        //      16 for DataValue
        //      4  for UInt
        //      12 for overhead (alignment, boost::flat_map)
        //      68 for the String 
        //        - 32 bytes for the String (SSO means the data is inside the String)
        //        - 34 bytes additional overhead
        // ---------------
#endif

        // ---------------
        // Alternative ways to store the data:
        // ---------------

        // ---------------
        // Memory usage (loading MS data): 98 MB (working set delta)
        //   98 bytes to store the string in a simple vector
        //     32 bytes for the string
        //     51 bytes for the data
        //     15 bytes overhead
        // ---------------
        // For a small string (<16 bytes) 
        // Memory usage (loading MS data): 34 MB (working set delta)
        //     32 bytes for the string (SSO means the data is inside the String) 
        // ---------------
        // vv.push_back(hello);

        // ---------------
        // Memory usage (loading MS data): 74 MB (working set delta)
        //   74 bytes to store a char* ptr
        //     8  bytes for the ptr
        //     51 bytes for the data
        //     16 bytes overhead
        // ---------------
        // auto c = new char[hello.length() + 1];
        // strcpy(c, hello.c_str());
        // vvv.push_back(c);

        // ---------------
        // Memory usage (loading MS data): 52 MB (working set delta)
        //   60 bytes to only store the string data
        //      - 51 bytes for the data
        //      - 8 bytes for the offsets
        //      - 1 byte overhead
        // ---------------
        // off.push_back(longStr.size());
        // longStr += hello + "\0";
      }
```

this was done on Ubuntu with `c++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609`. It is interesting to note that on an object with a `MetaInfoInterface` without metavalues, adding a single string of 50 bytes can add up to 200 bytes of extra data (300% overhead) while on an existing object that already has metavalues its 144 bytes (200% overhead). Storing the string in a member variable would only incur 98 bytes of memory (100% overhead) while storing it in a `char *` leads to 74 bytes of memory usage (48% overhead). The cheapest solution is to do "manual" memory management with a long global contiguous String and only store a ptr to the offset which costs 60 bytes (16% overhead).

Also note that for small strings the difference is really striking, it takes only 32 bytes to store a small string (<16 bytes) as a member variable while it still takes 80 bytes to store it as a MetaValue.

So one takeaway message is that it can save memory to store strings as member variables instead of metavalues and that the overhead can be up to 300% (e.g. 4x more storage required) if your string is the first metavalue. Also the overhead of placing objects in memory and having many small objects is significant, even for placing `char *` arrays it reduces the overhead from almost zero (16%) to 48% because it has to be aligned to 16 byte boundaries.

**Comment by hroest** [comment]
To better compare older versions, I first made a smaller version of the file

```
$ head -n 14974031 E3035_HCV_LAB1.idXML > /tmp/smallerfile.idXML
$ tail -n 20 E3035_HCV_LAB1.idXML >> /tmp/smallerfile.idXML 
$ ls -tlrh /tmp/smallerfile.idXML 
-rw-rw-r-- 1 hr hr 1.2G Sep 27 13:02 /tmp/smallerfile.idXML
$ ls -tlrh E3035_HCV_LAB1.idXML
-rw-rw-r-- 1 hr hr 2.7G Sep 27 10:23 E3035_HCV_LAB1.idXML
$ release_2.1/./bin/FileInfo -in /tmp/smallerfile.idXML 
Mem Usage while loading: 6245 MB
FileInfo took 01:20 m (wall), 01:18 m (CPU), 0.00 s (system), 01:18 m (user).
$ release_2.2/bin/FileInfo -in /tmp/smallerfile.idXML 
Memory usage while loading: 6257 MB
FileInfo took 01:18 m (wall), 01:16 m (CPU), 0.00 s (system), 01:16 m (user).
$ release_2.3/bin/FileInfo -in /tmp/smallerfile.idXML 
Memory usage (loading idXML): 6257 MB (working set delta)
FileInfo took 01:24 m (wall), 01:24 m (CPU), 2.68 s (system), 01:21 m (user).
$ release_2.4/./bin/FileInfo -in /tmp/smallerfile.idXML 
Memory usage (loading idXML): 2677 MB (working set delta)
FileInfo took 55.24 s (wall), 55.23 s (CPU), 0.93 s (system), 54.30 s (user).
$ current/./bin/FileInfo -in /tmp/smallerfile.idXML 
Memory usage (loading idXML): 1296 MB (working set delta)
FileInfo took 48.58 s (wall), 48.58 s (CPU), 0.53 s (system), 48.05 s (user).
```

so overall that is a 5x improvement since `2.3` and a 2x improvement since `2.4` and also nice speedups.

**Comment by hendrikweisser** [comment]
Is more work going to be done on this or are the improvements made so far sufficient to close the ticket?
