### ISSUE TITLE
Question about Epifany module

### ISSUE THREAD

**Issue by katrina-uw** [OpenMS/OpenMS#6296]
The protein results from Epiphany show four different types, and each has a different score:
general_protein_group, indistinguishable_protein_group, single_protein, protein_details

I wonder which subset of them is for protein-level scores and which subset is for single-protein-level scores? 
For example, the protein_details and single-protein shows different scores for each protein, so how is the score of protein_details calculated? (a combination of single-protein and protein-group?)

Thanks a lot!

**Comment by katrina-uw** [comment]
What's the difference between general_protein_group and indistinguishable_protein_group？ And the difference between single_protein and protein_details? (since they have different scores.)


Ideally there should be only one score for each of the types (protein group level and single protein level)

And example shown here for 4 types of the protein:
![ed115f7773f58d5876b37bd65f6ac11](https://user-images.githubusercontent.com/45520179/184549406-033085ee-4869-4b67-b0b5-d31d014af76f.png)
![fb7c441320880ca0ae092817ca0f1bd](https://user-images.githubusercontent.com/45520179/184549412-1144b83f-7dc9-4d96-8296-e140bdbaa938.png)
![e5dde67f4cd7589c1db6afbf07dc249](https://user-images.githubusercontent.com/45520179/184549415-81e6e4c8-73d0-4b2e-a5b3-e1bc5f7e65da.png)
![270d0e56fa58fae5f26df8a311d8037](https://user-images.githubusercontent.com/45520179/184549444-29cf81d2-f55e-4a80-a1cf-49430d7ccdfb.png)

**Comment by jpfeuffer** [comment]
Hi!

First of all, I am not sure where the general protein groups are coming from. We kind of deprecated that concept. We wanted to be able to represent other types of protein groups but never implemented anything yet. All they ever were, were connected components in the graph. I would disregard them completely.

I think indistinguishable groups should be clear. The score is the probability of at least one protein of the group being present.

For single(ton) proteins the score is the probability of presence.

Protein details represent probabilities and other information (e.g. coverage) for specific proteins in (indistinguishable) groups. They should of course be lower than the probability of any protein in the whole group being present. They should be the same for every member since we currently don't model proteotypicities or protein lengths.

For our QC reports we usually filter for single proteins and indistinguishable protein groups only. The rest is mainly for advanced users or strict isoform analyses.

**Comment by katrina-uw** [comment]
Thank you so much!
