### ISSUE TITLE
TOPPView MS2 visualization on the 2D map is messed up in the latest nightly

### ISSUE THREAD

**Issue by lfnothias** [OpenMS/OpenMS#6572]
Just to report that there is an issue with the 2D map visualization of MS2 in the latest nightly TOPPView. Below you can see the same file with the latest version and the an older one. Adding that is on macOS 12.6.

<img width="1294" alt="Screen Shot 2022-12-25 at 12 34 32" src="https://user-images.githubusercontent.com/22830047/209574330-1a807f96-a1a3-4ddd-9140-e8fdc13a0d16.png">

<img width="1294" alt="Screen Shot 2022-12-25 at 12 33 16" src="https://user-images.githubusercontent.com/22830047/209574340-90a00a3f-57c6-4e3f-a62e-5b1d17592966.png">

**Comment by cbielow** [comment]
if the date in the nightly build as shown in the screenshot is correct (2022/11/25), then these glitches are already fixed in develop (see https://github.com/OpenMS/OpenMS/pull/6519). 
Please wait for nightlies to update.

Will close. Please re-open if my assumptions are incorrect.
Happy Christmas :)
