### ISSUE TITLE
Move KNIME Tutorial workflows to KNIME Hub and use Workspace relative paths

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6605]
- Load workflows from github.com/OpenMS/Tutorials folder Workflows
- Add short descriptions and metadata to the workflows after opening them (see the README.MD in the Workflows folder)
- This description should also include a short description of how to download Tutorial data files and where to place them. We want them in the KNIME workspace, so ALL our workflows can access them. For this we will need to adapt all workflows to knime relative paths, usually knime://knime.workspace/somefolder. Some workflows might do that already. Check for hidden input nodes in Components/Metanodes.
- Login to KNIME Hub with openms account. Ask for credentials.
- Drag n Drop to KNIME Hub

Please consult KNIME docs for most of the steps.

**Comment by enetz** [comment]
there is a major issue with a workflow:
ProteomicsLFQ_tool_and_MSstats_postprocessing

The workflow uses the `Input Directory` node twice. I am not sure how it is supposed to work, but the problem is that I cannot open any config for these nodes. When I double click on it, nothing happens, except for this error message in the console:

`ERROR Input Directory      12:2       Error while creating node dialog for 'Input Directory': KNIME URLs must contain an Authority, fount 'knime:/n\\ime.workflow\..\Example_Data\Labelfree\datasets'`

it looks like the path is set almost correctly, but
1. it uses the windows style `\`
2. some weird stuff happened in the beginning with `knime://knime.workflow/`

This might be Windows specific and related to this GKN issue: https://github.com/genericworkflownodes/GenericKnimeNodes/issues/295
