### ISSUE TITLE
Add support for file dialog in TOPPView to default to the last opened directory

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6642]
It would be really nice if the file selection dialog defaulted to the directory that we used most recently.

**Comment by jpfeuffer** [comment]
Which OSes are affected?

**Comment by poshul** [comment]
> Which OSes are affected?

Both windows and Linux at least. Its not new behavior, and its not a showstopper, but it is getting on my nerves today, so I figured I'd log it as an enhancement request

**Comment by cbielow** [comment]
I've observed this too, and IMHO a good solution is to use the path of the currently opened layer (this may not be the most recent one).
This is how its done in Notepad++ for example, and I really like it because it allows the user to switch to certain tabs (or layers in our case) to open other files right next to it.

**Comment by cbielow** [comment]
fixed in https://github.com/OpenMS/OpenMS/pull/6703
