### ISSUE TITLE
TOPPView crashed while attempting to edit text annotation on Peak1 in idXML file

### ISSUE THREAD

**Issue by JeeH-K** [OpenMS/OpenMS#6652]
![Screenshot 2023-02-02 at 10 40 41 AM](https://user-images.githubusercontent.com/7207883/216290142-1a81f9de-ea67-4ec4-8f96-4b4b9429b130.png)

Tested with example idXML files (OpenMS/examples/FRACTIONS/*.idXML). Clicking both the edit and delete buttons resulted in crashes.

Tested on MacOS, Ventrua 13.1

**Comment by cbielow** [comment]
Reproducible on Windows. 
However, double clicking works. (Which also calls edit).

**Comment by cbielow** [comment]
Also pressing the "delete" key on a selected item works fine on Windows. Can you confirm on Mac?

I did not even know this functionality/context menu existed.

The problem is, the fix is not easy since the context menu stores a pointer to the item, but the pointer is invalided since all items are refreshed during a redraw which happens in the background. The code involved is quite messy (TVController and PeptideIdentification conversion stuff) and should be reworked.
Maybe @timosachsenberg  can find some time to look into it?! 

For now, we could simply disable the context menu and just rely on keyboard shortcuts (to be confirmed to work on all platforms).

**Comment by cbielow** [comment]
Small hint on how to trace the bug: put a breakpoint in the Ctor or Dtor of AnnotationItem1D to catch the event of redrawing.

**Comment by timosachsenberg** [comment]
@cbielow trying to understand why this issue came up now?
I recall that some of the annotation drawing code was dropped between the old version and after the refactoring. Will check if the error was present in the old version.

**Comment by axelwalter** [comment]
Just tested on Ubuntu 22.10, delete works fine with key and menu click, edit crashes on menu click.
