### ISSUE TITLE
Overhaul archive

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6719]
https://abibuilder.cs.uni-tuebingen.de/archive/openms/

Navigate to our NFS on our infrastructure. Ask @timosachsenberg how to do that.

Remove:
- All older tutorial data from old courses
- All temporary data (@timosachsenberg is this galaxy-testdata needed? Can this go elsewhere?)
- pyopenms folder

Restructure such that ALL data that is needed for our workflows is in one folder. See Tutorials folder.
Rethink versioning of Tutorial data.

Ask the IT if we can offer FTP access, so we could actually use an FTP connector in KNIME or the FTP protocol in nextflow.

**Comment by timosachsenberg** [comment]
Galaxy test data is needed for galaxy ice workflow

**Comment by timosachsenberg** [comment]
done?

**Comment by poshul** [comment]
@enetz does this need anything more or can I close it?

**Comment by enetz** [comment]
I created a new folder openms/Tutorials/Example_Data with all the data currently used in the KNIME workflows. It's less deep into the file tree and can be downloaded as one 10 GB tar file. We could also put it there as a < 6 GB zip file.
But to finalize this, we need to make sure the workflows all run through with this data. And the DIAMetAlyzer data is not included yet, since the only dataset we have is > 25 GB and that workflow has an issue with SIRIUS.

I also need update the workflow descriptions to the correct download path later.

**Comment by timosachsenberg** [comment]
is this considered done?
