### ISSUE TITLE
Inconsistent behavior in DeistopeAndSingleCharge function

### ISSUE THREAD

**Issue by birdday** [OpenMS/OpenMS#7062]
(In pyOpenMS) Inconsistent summed intensities and charge annotation in Deisotoper.deisotopeAndSingleCharge depending on options, notably fragement_unit_ppm: 

Example 1 (Correct Behavior):
Code :
```
newSpectrum = MSSpectrum()
mz = [100.0, 100.5, 101.0, 101.5, 102.0]
ints = [1000, 500, 200, 10, 5]
newSpectrum.setPeaks([mz, ints])

Deisotoper.deisotopeAndSingleCharge(newSpectrum, 100, True, 1, 10, False, 2, 20, False, True, True, False, 1, True)
print(newSpectrum.size())
print([peak.getMZ() for peak in newSpectrum])
print([peak.getIntensity() for peak in newSpectrum])
print(list(newSpectrum.getIntegerDataArrays()[0]))  # Charges
print(list(newSpectrum.getIntegerDataArrays()[1]))  # NumPeaks
```

Output: 
```
1
[100.0]
[1715.0]
[2]
[5]
```

Example 2 (Incorrect Behavior):
Code :
```
newSpectrum = MSSpectrum()
mz = [100.0, 100.5, 101.0, 101.5, 102.0]
ints = [1000, 500, 200, 10, 5]
newSpectrum.setPeaks([mz, ints])

Deisotoper.deisotopeAndSingleCharge(newSpectrum, 100, False, 1, 10, False, 2, 20, False, True, True, False, 1, True)
print(newSpectrum.size())
print([peak.getMZ() for peak in newSpectrum])
print([peak.getIntensity() for peak in newSpectrum])
print(list(newSpectrum.getIntegerDataArrays()[0]))  # Charges
print(list(newSpectrum.getIntegerDataArrays()[1]))  # NumPeaks
```

Output: 
```
1
[100.0]
[6560.0].  # Intensity of peaks multiplied by seemingly random integers before sum? (1000*3 + 500*5 + 200*5 +  10*5 + 5*2)
[10] # Charge definitely not +10
[20] # Not even 20 peaks in initial spectrum
```

Note: Fixed a typo in the examples (was swapping between computers so just retyped it here)

**Comment by jpfeuffer** [comment]
Hi!

Definitely a bug, but probably because of the absolute value of your tolerances and not the fact if it is ppm or Da.
With this huge tolerance everything is just counted everytime.

Implementation is [here](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FILTERING/DATAREDUCTION/Deisotoper.cpp#L346), maybe someone finds something quickly.

**Comment by timosachsenberg** [comment]
I think a possible fix would be to throw an exception if the absolute tolerance is larger than 0.1 Da (in the case of absolute tolerances) and e.g., more than 100 ppm for relative tolerances.

edited for more realistic tolerances

**Comment by birdday** [comment]
Lowering the tolerance to 0.5 with fragment_unit_ppm = False still gives the same results.

Code :
```
newSpectrum = MSSpectrum()
mz = [100.0, 100.5, 101.0, 101.5, 102.0]
ints = [1000, 500, 200, 10, 5]
newSpectrum.setPeaks([mz, ints])

Deisotoper.deisotopeAndSingleCharge(newSpectrum, 0.5, False, 1, 10, False, 2, 20, False, True, True, False, 1, True)
print(newSpectrum.size())
print([peak.getMZ() for peak in newSpectrum])
print([peak.getIntensity() for peak in newSpectrum])
print(list(newSpectrum.getIntegerDataArrays()[0]))  # Charges
print(list(newSpectrum.getIntegerDataArrays()[1]))  # NumPeaks
```

Output: 
```
1
[100.0]
[6560.0]
[10]
[20]
```

However, lowering it further to 0.1 gives the 'correct' results of the first example.

Code :
```
newSpectrum = MSSpectrum()
mz = [100.0, 100.5, 101.0, 101.5, 102.0]
ints = [1000, 500, 200, 10, 5]
newSpectrum.setPeaks([mz, ints])

Deisotoper.deisotopeAndSingleCharge(newSpectrum, 0.1, False, 1, 10, False, 2, 20, False, True, True, False, 1, True)
print(newSpectrum.size())
print([peak.getMZ() for peak in newSpectrum])
print([peak.getIntensity() for peak in newSpectrum])
print(list(newSpectrum.getIntegerDataArrays()[0]))  # Charges
print(list(newSpectrum.getIntegerDataArrays()[1]))  # NumPeaks
```

Output: 
```
1
[100.0]
[1715.0]
[2]
[5]
```

Am I misunderstanding the option? The peaks in the examples are greater than 0.1 dalton apart, so I'd assume lowering the tolerance to 0.1 would result in no deisotoping.

**Comment by timosachsenberg** [comment]
The peak tolerance indicates how much left or right to the next *expected* isotopic peak position is still allowed - e.g., how accurate the mass spectrometer measured the peaks. This is usually a very small value (e.g., 0.01 Da or 5 ppm on modern instruments) - that's why we were a bit confused about the huge mass tolerance.
The algorithm internally looks for the next isotopic peaks at a distance of C13C12_MASSDIFF_U / charge. Where C13C12_MASSDIFF_U  = 1.0033548378 (the additional mass caused by an adding one neutron to a carbon atom).

Note: for high mass accuracies (e.g., small ppm values) your test data mz = [100.0, 100.5, 101.0, 101.5, 102.0] will not be properly deisotoped because the expected isotopic peak position would be 100.50168 instead of 100.5.

**Comment by birdday** [comment]
Ah okay, that makes much more sense. In that case, an exception sounds like a reasonable solution. Appreciate the clarification!

**Comment by timosachsenberg** [comment]
Thanks! I added an issue to improve the documentation.
