### ISSUE TITLE
Install 3.x.0 for single user in windows doesn't create shortcuts

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#7204]
I discovered that the "install for this user only" doesn't create shortcuts.

**Comment by poshul** [comment]
@enetz, can you take a look at this while you are looking at the KNIME Thirdparties stuff?

**Comment by enetz** [comment]
@poshul what exactly do you mean with "shortcuts"? The bin and Thirdparty paths in the system path?
I tried the 3.1 release installer on Win 10. For a single user install, it adds the paths to the user specific "path" system variable, instead of the system wide "path", so it worked for me.
Maybe a Win 11 specific problem?

**Comment by poshul** [comment]
OpenMS didn't show up in the start menu by default with the per-user install. It could be win 11 specific.

**Comment by enetz** [comment]
For me on Win 10 the GUIs show up in the start menu. I don't have a Win 11 PC to test it right now.

**Comment by poshul** [comment]
Okay. I think we can probably close this then, unless we get another report.
