### ISSUE TITLE
(nightly) Docs still not uploading

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7551]
There is still something wrong with rsync.
I wanted to check on the version selector.
Will be needed for a release as well.

**Comment by poshul** [comment]
There is an issue with how IT has configured Ceph, which they are now using for back end storage for our archive. Some of the OSD's advertise their internal cluster address to everyone, so when you trying to read/write it hangs trying to lock the file. I've told them this since December but they have refused to fix it. I just wrote static routing rules to override their problem yesterday, and this should fix *this* issue.

**Comment by poshul** [comment]
Fixed now.
