### ISSUE TITLE
Copyright questions for files outside of OpenMS

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#7571]
Greetings,

What is the license of these files: src/tests/class_tests/openms/data/PepNovoOutfile.out, ./src/tests/class_tests/openms/data/PepNovoOutfile_version_file.txt .

The whole directory share/OpenMS/SCHEMAS has numerous files for which both Copyright and License are difficult to establish, could you provide me with some specifics about these files, please ?

I think I have working packages that I'll upload to the NEW queue of the Debian repositories in the experimental distribution. Waiting to fix the copyright questions above because this is compulsory for uploading software to the Debian servers.

Most sincerely,
Filippo

**Comment by jpfeuffer** [comment]
The class test outputs are outputs from our tools and maximally outputs from third-party tools that we wrap.
I am not a lawyer but I think I have read before that program output does not follow the license of the tools.
Since one of our developers produced this output and contributed it to this repo it should follow our BSD license and the copyright of the rest of the project.

**Comment by jpfeuffer** [comment]
The inputs are excerpts from public data (creative commons), contributed by collaborators or manually created input data. I would also say if follows our BSD license.

**Comment by lopippo** [comment]
Great, thank you for the explanation !
