### ISSUE TITLE
Retention Time Correction

### ISSUE THREAD

**Issue by LeonSaal** [OpenMS/OpenMS#7604]
Dear OpenMS-Team,

thank you for your work!

I want to perform retention time correction on mzML-files using a TOPPAS (3.2.0, e231942) pipeline, where I read in a mzML-file, correct the RTs and save a modified mzML.
This is what I have so far:

![image](https://github.com/user-attachments/assets/bfbbfa3f-205e-48fd-a3d3-4a661133d41f)

Unfortunately, an error occurs within the output node:

```console
==============================================================================
14:46:46 NOTICE: MapRTTransformer of node #5 started. Processing ...
Cannot write output file given from parameter '-out'!
Error: Unable to write file (the file '...\005_MapRTTransformer\out\2493-r003.unknown' could not be created. )

==============================================================================
14:46:46 ERROR: MapRTTransformer failed!
```
It seems like the file type from the input data is not properly channeled to the output, resulting in an _.unknown_ type.
Invoking the `MapRTTranformer` command with .mzML as output format and .trafoXML from the previous node from the command line yields the desired output.

Am I missing an important node in the pipeline?

Kind regards,

Leon

**Comment by cbielow** [comment]
Hi Leon,

thanks for reporting this.
<strike>The error occurs due to an internal re-write of what is allowed as output filename. The MapRTTransformer internally requests an `mzML` file output, but TOPPAS cannot know what the output format is, so it temporarily uses an `.unknown` suffix (until it can inspect the file to see what is actually is). The internal procedure wants to write an mzML, but does not like the `.unknown` suffix and bails out.

For now, there is nothing you can do to change that, other than wait for OpenMS 2.3.1.
Sorry.
In the meantime you can try any other pipeline engine where you have control over the output names of the nodes (e.g. snakemake, or write a bash script).
</strike>

One note: The Alignment may not be optimal since it's done using raw data. This may work for edge cases, but usually one is better off using features, i.e. call a `FeatureFinder...` on the raw data first and align on the resulting `.featureXML` files to obtain a transformation in RT.

**Comment by cbielow** [comment]
ok, following up on this, I double checked the code, and tried to reproduce your example.
However, both the current develop branch, as well as the binaries we provide for OpenMS 3.2 can run the above pipeline just fine:

![image](https://github.com/user-attachments/assets/06766202-11df-4fea-aa75-34934a394bed)

Following up on the changes inside the code which I mentioned above: this was fixed in 08/2023.
So, are you sure the OpenMS you are running is really 3.2?

**Comment by LeonSaal** [comment]
Thank you for the prompt answer and tips for the pipeline!

And yes, it is 3.2.0 on Windows, which I downloaded just yesterday.
![image](https://github.com/user-attachments/assets/6154b460-5e85-402d-92c3-f2f86fc584c4)

I also ran a test using other input files, namely the _BSA....mzML_ example files from `OpenMS\share\OpenMS\examples\FRACTIONS` and it finished without a problem!

So I guess there is something off with my input files (although it works from the command line).
I'm using msconvert with the following settings:
![image](https://github.com/user-attachments/assets/e634b69c-4334-4863-9680-aa74b9c173ac)
Any idea what could cause the problem?

Kind regards,

Leon

**Comment by LeonSaal** [comment]
Another observation:
When I add a feature finding node prior to Map Alignment as suggested, there also is no problem.
As my original used case is advised against, one could say there is no problem at all.

**Comment by LeonSaal** [comment]
Now I know what caused the problem: The TEMP-directory (which is on another, smaller drive than the target directory of the pipeline) was blowing up until the point where no space was left on disk. I moved TEMP to another drive and resolved the problem.

**Comment by cbielow** [comment]
ok, thanks for following up on this and finding the root cause.
