### ISSUE TITLE
Epifany score error 

### ISSUE THREAD

**Issue by prvst** [OpenMS/OpenMS#7640]
Hello, I'm trying to run Epifany 3.1 on an isobaric-labelled data, and getting this error:

`Error: Unexpected internal error (Epifany needs Posterior Error Probabilities in the Peptide Hits. Use Percolator with PEP score or run IDPosteriorErrorProbability first.)
`

Before Epifany, I ran PercolatorAdapter with `-score_type pep`

My idXML/consensusXML files have q-score in the ProteinID headers:
```ProteinIdentification score_type="q-value" higher_score_better="false" significance_threshold="0">```

But they also have the PEP attributes inside them:
`<UserParam type="float" name="MS:1001493" value="2.88973e-04"/>`

I appreciate any help.

Thanks!

**Comment by jpfeuffer** [comment]
Hi!

Which FDR settings did you use in percolator for the non-protein level?
Peptide_fdr or psm_fdr?

Did you also activate protein_fdr?

Can you look for a peptideidentification element and check the situation of scores there?

If you used peptide FDR, I might have an idea. With peptide FDR not all psms (only the best) get their score "updated" and Epifany checks the score of every PSM.

**Comment by prvst** [comment]
Using only the PSM FDR solved the issue, thanks.

**Comment by jpfeuffer** [comment]
Cool, if I find the time, I can adapt it to the newer peptide FDR.
The problem is that we do not have a separate data structure for peptides in our old identification classes.
I would need to move to our new structure or continue with the hack of some psms just not having scores, which would actually be relatively easy since I'm aggregating for peptides anyway in Epifany. I just have to make sure that we can distinguish between "missing by error" and "missing intended".
