### ISSUE TITLE
NASequence.fromString phosphothiolate

### ISSUE THREAD

**Issue by Scott1451** [OpenMS/OpenMS#7641]
Hi,

I have a heavily modified RNA with 2'OMe and a phosphothiolated backbone - this modification does not appear to be part of the DB:

```
from pyopenms import *
oligo = NASequence.fromString("[mA][mA*][mA]")
seq_formula = oligo.getFormula()
print(seq_formula)
```

`RuntimeError: the element 'mA*' could not be found`

More generally how can I access the RibonucleotidesDB to print the modifications available?

Thanks
Scott

**Comment by poshul** [comment]
Hi Scott, custom RNA mods can be added in https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Custom_RNA_modifications.tsv I think adding:
`2'O-Me-thio-adenosine	mA*	mA*	A	A	A	C11O4N5H15	281.112404	281.27`
to the end of that file should do the trick.

We don't currently have a way of dumping the DB, since we've just looked at the mods in the files. But if that would be helpful to you I can put it on our feature request list.

**Comment by Scott1451** [comment]
> Hi Scott, custom RNA mods can be added in https://github.com/OpenMS/OpenMS/blob/develop/share/OpenMS/CHEMISTRY/Custom_RNA_modifications.tsv I think adding: `2'O-Me-thio-adenosine mA* mA* A A A C11O4N5H15 281.112404 281.27` to the end of that file should do the trick.
> 
> We don't currently have a way of dumping the DB, since we've just looked at the mods in the files. But if that would be helpful to you I can put it on our feature request list.

Awesome - thanks!

Another quick question.  I am trying to do add/subtract operations on chemical formula - the example in the docs works well but this does not:

```
from pyopenms import *

methanol = EmpiricalFormula("CH3OH")
water = EmpiricalFormula("H2O")
wm = EmpiricalFormula(str(water) - str(methanol))
print(wm)

TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

Any workaround?

**Comment by jpfeuffer** [comment]
Hi, I think that could just be:
`wm = water - methanol`
The minus operator is implemented for the formula objects but not for strings.
