### ISSUE TITLE
MassCalculator error

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#7696]
```
MassCalculator
Error: Residue::getResidueTypeName - residue type has no name. The developer should add a residue name to Residue.cpp
Error: Residue::getResidueTypeName - residue type has no name. The developer should add a residue name to Residue.cpp
```

**Comment by bernt-matthias** [comment]
https://github.com/OpenMS/OpenMS/issues/4678

**Comment by timosachsenberg** [comment]
TODO:
following cases are not handled in the switch statement:
```
case Residue::Zp1Ion:
  return "z+1-ion";

case Residue::Zp2Ion:
  return "z+2-ion";
```

Better would be to add names to a
```
std::array<char*, Residue::SizeOfResidueType> names_of_ResidueType = { ...};
```
and return the names from this array instead of hard-coding it into the switch statement.
This way we could ensure that the number of entries need to match during compile time.

For reference:
this is the enum: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/CHEMISTRY/Residue.h#L148-L170
and this is where we need to add it:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/Residue.cpp#L83
